/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.notify.conf 17455 2009-04-05 09:53:29Z magfr $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "tlv_enc_dec.h"
#include "bs_events.h"
#include "enbAlarms.h"

extern const oid snmptrap_oid;
extern const size_t snmptrap_oid_len;

int
send_enbAlarmInd_trap( NotiObj *notiMsg )
{
    unsigned int uiVal;
    netsnmp_variable_list  *var_list = NULL;
    const oid enbAlarmInd_oid[] = { 1,3,6,1,4,1,9344,501,500,1,1 };
    const oid enodebId_oid[] = { 1,3,6,1,4,1,9344,501,52,1,1,1,1 };
    const oid alarmSequenceNumber_oid[] = { 1,3,6,1,4,1,9344,501,500,0,1, 0 };
    const oid dateAndTimeStamp_oid[] = { 1,3,6,1,4,1,9344,501,600,2, 0 };
    const oid alarmId_oid[] = { 1,3,6,1,4,1,9344,501,500,0,3, 0 };
    const oid alarmType_oid[] = { 1,3,6,1,4,1,9344,501,500,0,2, 0 };
    const oid alarmSeverity_oid[] = { 1,3,6,1,4,1,9344,501,500,0,4, 0 };
    const oid alarmCause_oid[] = { 1,3,6,1,4,1,9344,501,500,0,5, 0 };
    const oid alarmLocation_oid[] = { 1,3,6,1,4,1,9344,501,500,0,6, 0 };
    const oid alarmAdditionalText_oid[] = { 1,3,6,1,4,1,9344,501,500,0,7, 0 };

    logInfo("Sending Alarm Notification ID = %d ", notiMsg->notiId);
    /*
     * Set the snmpTrapOid.0 value
     */
    snmp_varlist_add_variable(&var_list,
        &snmptrap_oid, snmptrap_oid_len,
        ASN_OBJECT_ID,
        enbAlarmInd_oid, sizeof(enbAlarmInd_oid));
    
    /*
     * Add any objects from the trap definition
     */
    uiVal = getUint32FromArray(notiMsg->notiTlvInfo[COL_ALARMNOTIFICATION_ENODEBID-1].data);
    snmp_varlist_add_variable(&var_list,
        enodebId_oid, OID_LENGTH(enodebId_oid),
        ASN_UNSIGNED,
        &uiVal,
        notiMsg->notiTlvInfo[COL_ALARMNOTIFICATION_ENODEBID-1].len);

    uiVal = getUint32FromArray(notiMsg->notiTlvInfo[COL_ALARMNOTIFICATION_ALARMSEQUENCENUMBER-1].data);
    snmp_varlist_add_variable(&var_list,
        alarmSequenceNumber_oid, OID_LENGTH(alarmSequenceNumber_oid),
        ASN_INTEGER,
        &uiVal,
        notiMsg->notiTlvInfo[COL_ALARMNOTIFICATION_ALARMSEQUENCENUMBER-1].len);

    snmp_varlist_add_variable(&var_list,
        dateAndTimeStamp_oid, OID_LENGTH(dateAndTimeStamp_oid),
        ASN_OCTET_STR,
        notiMsg->notiTlvInfo[COL_ALARMNOTIFICATION_DATEANDTIMESTAMP-1].data,
        notiMsg->notiTlvInfo[COL_ALARMNOTIFICATION_DATEANDTIMESTAMP-1].len);

    uiVal = getUint32FromArray(notiMsg->notiTlvInfo[COL_ALARMNOTIFICATION_ALARMID-1].data);
    snmp_varlist_add_variable(&var_list,
        alarmId_oid, OID_LENGTH(alarmId_oid),
        ASN_INTEGER,
        &uiVal,
        notiMsg->notiTlvInfo[COL_ALARMNOTIFICATION_ALARMID-1].len);

    uiVal = getUint32FromArray(notiMsg->notiTlvInfo[COL_ALARMNOTIFICATION_ALARMTYPE-1].data);
    snmp_varlist_add_variable(&var_list,
        alarmType_oid, OID_LENGTH(alarmType_oid),
        ASN_INTEGER,
        &uiVal,
        notiMsg->notiTlvInfo[COL_ALARMNOTIFICATION_ALARMTYPE-1].len);

    uiVal = getUint32FromArray(notiMsg->notiTlvInfo[COL_ALARMNOTIFICATION_ALARMSEVERITY-1].data);
    snmp_varlist_add_variable(&var_list,
        alarmSeverity_oid, OID_LENGTH(alarmSeverity_oid),
        ASN_INTEGER,
        &uiVal,
        notiMsg->notiTlvInfo[COL_ALARMNOTIFICATION_ALARMSEVERITY-1].len);

    uiVal = getUint32FromArray(notiMsg->notiTlvInfo[COL_ALARMNOTIFICATION_ALARMCAUSE-1].data);
    snmp_varlist_add_variable(&var_list,
        alarmCause_oid, OID_LENGTH(alarmCause_oid),
        ASN_INTEGER,
        &uiVal,
        notiMsg->notiTlvInfo[COL_ALARMNOTIFICATION_ALARMCAUSE-1].len);

    snmp_varlist_add_variable(&var_list,
        alarmLocation_oid, OID_LENGTH(alarmLocation_oid),
        ASN_OCTET_STR,
        notiMsg->notiTlvInfo[COL_ALARMNOTIFICATION_ALARMLOCATION-1].data,
        notiMsg->notiTlvInfo[COL_ALARMNOTIFICATION_ALARMLOCATION-1].len);

    snmp_varlist_add_variable(&var_list,
        alarmAdditionalText_oid, OID_LENGTH(alarmAdditionalText_oid),
        ASN_OCTET_STR,
        notiMsg->notiTlvInfo[COL_ALARMNOTIFICATION_ALARMADDITIONALTEXT-1].data,
        notiMsg->notiTlvInfo[COL_ALARMNOTIFICATION_ALARMADDITIONALTEXT-1].len);

    /*
     * Send the trap to the list of configured destinations
     *  and clean up
     */
    send_v2trap( var_list );
    snmp_free_varbind( var_list );

    return SNMP_ERR_NOERROR;
}
