/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef SWACTIVATION_H
#define SWACTIVATION_H

/* function declarations */
void init_swActivation(void);
void initialize_table_swActivationTable(void);

/* column number definitions for table swActivationTable */
       #define COLUMN_SWACTIVATIONINDEX		1
       #define COLUMN_ACTIVATIONSWTYPE		2
       #define COLUMN_SWACTIVATIONVERSION		3

#define SW_ACTIVATION_MAX_COL     COLUMN_SWACTIVATIONVERSION

#define SWACTIVATIONVERSION_BUF_LEN   20

    /* Typical data structure for a row entry */
typedef struct swActivationTable_entry {
    /* Index values */
    unsigned int index;

    /* Column values */
    unsigned int swType;
    char version[SWACTIVATIONVERSION_BUF_LEN];
    size_t version_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct swActivationTable_entry *next;
} swActivationTableEntry; 

#endif /* SWACTIVATION_H */
