#!/usr/bin/perl
# generate msg name strings correcponsing to msgIds
# Manu. 21July09
$file=shift;
if (!defined($file))
{
  print "usage: $0 bs_modules.h";
  exit;
}
open(IN, "<$file") || die "cannot open $file";

my $now = localtime time;
print "/* generated by $0 on $now */\n";
print "#include \"basic_types.h\"\n";
# include module_names.h to ensure that prototype matchees with generated stuff */
print "#include \"module_names.h\"\n"; 
print "#include \"bs_modules.h\"\n";
print "typedef struct s_ModName {\n  UINT32 id;\n  const String32 name;\n} ModName;\n";
print "const ModName c_modNameTab[] =\n";
print "{\n";

while (<IN>)
{
  if (/(MODID_.*),/)
  {
    $modId = $1;
    $modId =~ s/[\s]//g;
    printf "  {$modId, %30s},\n", "\"$modId\"";
  }
}

printf "  {0, %30s}\n", "\"\"";
print "};\n";
close IN;

print "\n";
print "inline const UINT8* getModuleName(IN ModuleId modId)\n";
print "{\n";
print "  return &c_modNameTab[modId].name[0];\n";
print "}\n\n";
