/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17695 2009-07-21 12:22:18Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "bs_modules.h"
#include "all_cfg.h"
#include "all_cmn.h"
#include "tlv_enc_dec.h"

#include "sih.h"
#include "syslog.h"

#include "enbConfig.h"

Netsnmp_Node_Handler enbConfigTable_handler;
Netsnmp_First_Data_Point  enbConfigTable_get_first_data_point;
Netsnmp_Next_Data_Point   enbConfigTable_get_next_data_point;

struct enbConfigTable_entry  *enbConfigTable_head = NULL;
static TBOOL g_sihEnbConfigSetReqProcessed = FALSE;
static TBOOL g_sihEnbConfigGetReqProcessed = FALSE;
static UINT32 g_prevEnbConfigReqCount = 0;
static UINT32 g_enbConfigFirstCall = 0;

/* free_enbConfigTable */
/**
* @details 
*          This is the routine which frees the enodeb config entry. 
*/
void free_enbConfigTable(void)
{
  enbConfigTableEntry  * current = enbConfigTable_head;

  if (current) 
  {
  for (current = enbConfigTable_head->next ; current != NULL; current = current->next) {
    SNMP_FREE( current );  
    }
   
  SNMP_FREE(enbConfigTable_head);
  enbConfigTable_head = NULL;
  }
  return;
}


/**
* @details 
*          This is the routine which handles get response from SIH Get Processor
*          and prepare the SNMP GET response for EMS. 
* @param tlvArray contains pointer to TLV array.     
*/
TBOOL sendEnbConfigSnmpGetResponse (
  IO TlvArray    *tlvArray
  )
{
  int  totalNumRow, totalNumCol, i=0, colmn=0;
  enbConfigTableEntry * prevPtr = NULL;

  printTLV(tlvArray);

  /* Total no. of Colmns */
  totalNumCol = ENODEB_CONFIG_MAX_COL;
  /* Total no. of Row = (No. of TLV)/(No. of Columns) */
  totalNumRow = tlvArray->numTlvs/totalNumCol;

  for (i=1;  i <= totalNumRow;  i++) 
      {
      enbConfigTableEntry *ptr=(enbConfigTableEntry *)malloc(sizeof(enbConfigTableEntry));

      clearBytes(ptr,sizeof(enbConfigTableEntry));

      /* Fill Data in TLV */
      for(colmn = 1 ; colmn <= totalNumCol ; colmn++)
        {
       if (colmn EQ COLUMN_ENODEBID)
           {
            ptr->enodebId = getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }        
       if (colmn EQ COLUMN_ENODEBNAME)
           {
            clearBytes (ptr->enodebName, ENODEB_BUFFER_LEN_MAX);
            if (tlvArray->tlvInfo[colmn-1].len > 0) 
                {    
                 copyBytes (tlvArray->tlvInfo[colmn-1].data, tlvArray->tlvInfo[colmn-1].len, ptr->enodebName);
                }
            ptr->enodebName_len = strlen(ptr->enodebName);
            continue;
           }
	if (colmn EQ COLUMN_USESTATICIPADDRESS)
	   {
	    ptr->useStaticIpAddress = getUint8FromArray(tlvArray->tlvInfo[colmn-1].data);
	    continue;		
	   }        
        if (colmn EQ COLUMN_ENODEBSTATICIPADDR)
           {
            ptr->enodebStaticIpAddr = inet_addr(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }        
        if (colmn EQ COLUMN_ENODEBNETMASKADDR)
           {
            ptr->enodebNetmaskAddr = inet_addr(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }        
        if (colmn EQ COLUMN_ENBREGISTRATIONACCEPTED)
           {
            ptr->enbRegistrationAccepted = getUint8FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_CONFIGCHANGEACKBYEMS)
           {
            ptr->configChangeAckByEms = getUint8FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        }

       ptr->next = NULL;

      if (prevPtr == NULL) {
           enbConfigTable_head =  prevPtr = ptr;
       }

      prevPtr->next = ptr;
      prevPtr = ptr;
     }
    prevPtr->next = NULL;

    if (enbConfigTable_head)
        return TRUE;
    else
        return FALSE;
}

/**
* @details 
*          This routine sends enodeb config set request to BSM, it uses SIH Set 
*          Processor to create and send the message to BSM. 
* @param sihTagInfo is used to have the tag information for set request.
*/
TBOOL sendEnbConfigSnmpSetRequest ( 
      IO TagInfo   sihTagInfo,
      IO TlvArray *tlvArray
      )
{
   enbConfigTableEntry * setReqData = NULL;   
   TBOOL status = FALSE;
   int colmn = 0;
   unsigned char * ipAddr;
   struct in_addr ip;
   
   setReqData = enbConfigTable_head;

   /* Fill Data in TLV */
   for(colmn = 0; colmn < tlvArray->numTlvs; colmn++)
      {
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_ENODEBID)
         {
           putUint32InArray( setReqData->enodebId, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->enodebId);     
         }
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_ENODEBNAME)
         {
           copyBytes (setReqData->enodebName, strlen(setReqData->enodebName), tlvArray->tlvInfo[colmn].data);
           tlvArray->tlvInfo[colmn].len = ENODEB_BUFFER_LEN_MAX-1; 
         }
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_USESTATICIPADDRESS)
         {
           putUint8InArray( setReqData->useStaticIpAddress, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->useStaticIpAddress);
         }	
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_ENODEBSTATICIPADDR)
         {
           ip.s_addr = setReqData->enodebStaticIpAddr;
           ipAddr = inet_ntoa(ip);
           copyBytes (ipAddr, strlen(ipAddr), tlvArray->tlvInfo[colmn].data);
           tlvArray->tlvInfo[colmn].len = ENODEBSTATICIPADDR_BUF_LEN_MAX; 
         }       
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_ENODEBNETMASKADDR)
         {
           ip.s_addr = setReqData->enodebNetmaskAddr;
           ipAddr = inet_ntoa(ip);
           copyBytes (ipAddr, strlen(ipAddr), tlvArray->tlvInfo[colmn].data);
           tlvArray->tlvInfo[colmn].len = ENODEBSTATICIPADDR_BUF_LEN_MAX;
         }       
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_ENBREGISTRATIONACCEPTED)
         {
           putUint8InArray( setReqData->enbRegistrationAccepted, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->enbRegistrationAccepted);     
         }          
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_CONFIGCHANGEACKBYEMS)
         {
           putUint8InArray( setReqData->configChangeAckByEms, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->configChangeAckByEms);
         }
      }

   /* Invoke SIH Set Processor */
   status = sihSetProcessor (sihTagInfo,  tlvArray);
   if (status EQ TRUE)
     {
      g_sihEnbConfigSetReqProcessed = TRUE;
      g_sihEnbConfigGetReqProcessed = FALSE;
      /* free the resources */      
      free_enbConfigTable(); 
     }
   return status;
}


/**
* @details 
*          This is the routine for initializing enbConfig module.
*/
void
init_enbConfig(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_enbConfigTable();
}

/*  # Determine the first/last column names */

/** Initialize the enbConfigTable table by defining its contents and how it's structured */
void
initialize_table_enbConfigTable(void)
{
    const oid enbConfigTable_oid[] = {1,3,6,1,4,1,9344,501,ENODEBCONFIG,1};
    const size_t enbConfigTable_oid_len   = OID_LENGTH(enbConfigTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("enbConfig:init", "initializing table enbConfigTable\n"));

    reg = netsnmp_create_handler_registration(
              "enbConfigTable",     enbConfigTable_handler,
              enbConfigTable_oid, enbConfigTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_UNSIGNED,  /* index: enodebId */
                           0);
    table_info->min_column = COLUMN_ENODEBID;
    table_info->max_column = COLUMN_CONFIGCHANGEACKBYEMS;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = enbConfigTable_get_first_data_point;
    iinfo->get_next_data_point  = enbConfigTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}


#ifndef PWAV_SIH 
/* create a new row in the (unsorted) table */
struct enbConfigTable_entry *
enbConfigTable_createEntry(
                 u_long  enodebId,
                ) {
    struct enbConfigTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct enbConfigTable_entry);
    if (!entry)
        return NULL;

    entry->enodebId = enodebId;
    entry->next = enbConfigTable_head;
    enbConfigTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
enbConfigTable_removeEntry( struct enbConfigTable_entry *entry ) {
    struct enbConfigTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = enbConfigTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        enbConfigTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}
#endif /* PWAV_SIH */


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
enbConfigTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    TagInfo sihTagInfo;
    TBOOL status = FALSE;

    if (g_sihEnbConfigGetReqProcessed EQ FALSE)
        {
        /* Set SIH Get Request Tag Info */
        sihTagInfo.tableId = ENODEBCONFIG;
        sihTagInfo.rowId = CONFIG_ROW_ID_NONE; 
        sihTagInfo.colId = CONFIG_COL_ID_NONE;                

        status = sihGetProcessor (sihTagInfo);
        if ( status EQ TRUE )
            {
            logInfo("%s","Get Processor Succedded");
            if (enbConfigTable_head)
                {
                g_enbConfigFirstCall = 1;
                g_sihEnbConfigGetReqProcessed = TRUE;
                }
            }
        else
            logError("%s","Get Processor Failed");
        }        
    
     *my_loop_context = enbConfigTable_head;
    return enbConfigTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
enbConfigTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct enbConfigTable_entry *entry = (struct enbConfigTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_UNSIGNED, entry->enodebId );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the enbConfigTable table */
int
enbConfigTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request = NULL;
    netsnmp_table_request_info *table_info = NULL;
    struct enbConfigTable_entry          *table_entry = NULL;
    int loopCount = 0;
    int ret;
    TagInfo sihTagInfo;
    TlvArray tlvArray;
    int rowIndex = 0, colId = 0;
    TBOOL status = FALSE;    


    DEBUGMSGTL(("enbConfig:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {

            loopCount++;
            if (request->processed != 0)
            {
             g_prevEnbConfigReqCount = 0;
             g_sihEnbConfigGetReqProcessed = FALSE;

             /* free the resources */
             free_enbConfigTable();
             /* Here loopCount is decremented, Due to calling of free function two times in SNMP-GETNEXT
              * on single parameter -- 20/07/11 */
             loopCount--;
             continue;
            }

            /* perform anything here that you need to do before each
               request is processed. */           

            /* the following extracts the my_data_context pointer set in
               the loop functions above.  You can then use the results to
               help return data for the columns of the enbConfigTable table 
               in question */    

            table_entry = (struct enbConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);

            if ( table_entry == NULL) {
                if (reqinfo->mode == MODE_GET) {
                    netsnmp_set_request_error(reqinfo, request,SNMP_NOSUCHINSTANCE);
                    continue;
                }
                /* XXX: no row existed, if you support creation and this is a
                   set, start dealing with it here, else continue */
            }

            table_info  =   netsnmp_extract_table_info(request);

            /* table_info->colnum contains the column number requested */
            /* table_info->indexes contains a linked list of snmp variable
               bindings for the indexes of the table.  Values in the list
               have been set corresponding to the indexes of the
               request */
            if (table_info==NULL) {
                continue;
            }             

            switch (table_info->colnum) {
            case COLUMN_ENODEBID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->enodebId);
                break;
            case COLUMN_ENODEBNAME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->enodebName,
                                          table_entry->enodebName_len);
                break;
            case COLUMN_USESTATICIPADDRESS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->useStaticIpAddress);
                break;
            case COLUMN_ENODEBSTATICIPADDR:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_IPADDRESS,
                                            table_entry->enodebStaticIpAddr);
                break;
            case COLUMN_ENODEBNETMASKADDR:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_IPADDRESS,
                                            table_entry->enodebNetmaskAddr);
                break;
            case COLUMN_ENBREGISTRATIONACCEPTED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->enbRegistrationAccepted);
                break;
            case COLUMN_CONFIGCHANGEACKBYEMS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->configChangeAckByEms);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        if(g_enbConfigFirstCall EQ 1)
        {
          g_enbConfigFirstCall = 0;
          g_prevEnbConfigReqCount = loopCount;
          // This will occur in case of, when SNMP-GET or SNMP-GETNEXT of Single Parameter occurred.
          // In the first call itself loopCount becomes one.
          // In General Case, the loopCount will be always > 1 because every table contains index column to fetch the row
          // and remaining columns contain table attributes.
          if(loopCount EQ 1)
          {
            //Setting it to false in case of SNMP-GET request for single parameter.
            g_sihEnbConfigGetReqProcessed = FALSE;
            // Free all resources.
            free_moduleStatusTable();
          }
        }
        else if(loopCount > 1 || g_prevEnbConfigReqCount > 1)
        {
          //update g_prevReqCount with current loopCount for next call of Table_handler
          g_prevEnbConfigReqCount = loopCount;
          //nothing to be done because previous request contain more than one column.
        }
        else if(loopCount EQ 1)
        {
           //Setting it to false in case of SNMP-GET request for single parameter.
          g_sihEnbConfigGetReqProcessed = FALSE;
           // Free all resources.
          free_enbConfigTable();
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
#ifndef PWAV_SIH        
        for (request=requests; request; request=request->next) {
            table_entry = (struct enbConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ENODEBID:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ENODEBNAME:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->enodebName));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_PAGINGDRXCYCLE:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_MMEIPADDR:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_SECUREMMELINK:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_SECURESGWLINK:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ENODEBSTATICIPADDR:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_SCTPNUMINBOUNDSTREAMS:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_SCTPNUMOUTBOUNDSTREAMS:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ACTIVECELLID:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_UERESPONSETIMER:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_RRCCONNREJWAITTIME:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_LOCALTIME:
                /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->localTime));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_LOCALTIMEOFFSETFROMUTC:
                /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->localTimeOffsetFromUTC));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
#endif /* PWAV_SIH */            
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        g_sihEnbConfigSetReqProcessed = FALSE; 

        clearBytes(&sihTagInfo, sizeof(TagInfo));
        clearBytes(&tlvArray, sizeof(TlvArray));
        
        for (request=requests; request; request=request->next) {
            table_entry = (struct enbConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(request);

            if(table_entry == NULL){
                logInfo(" %s\n", "table_entry is NULL");
                if (reqinfo->mode == MODE_SET_ACTION) {
                    netsnmp_set_request_error(reqinfo, request,SNMP_NOSUCHINSTANCE);
                    continue;
                }
                /* XXX: no row existed, if you support creation and this is a
                   set, start dealing with it here, else continue */
            }

            if(table_info == NULL){
                logInfo(" %s\n", "table_info is NULL");
                continue;
            }
    
            colId = table_info->colnum;
            /* set the row index */
            rowIndex = requests->index;

            switch (table_info->colnum) {
            case COLUMN_ENODEBID:
                table_entry->enodebId     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENODEBCONFIG, rowIndex, COLUMN_ENODEBID);
                tlvArray.numTlvs++;
                break;
            case COLUMN_ENODEBNAME:
                memset( table_entry->enodebName, 0,
                        sizeof(table_entry->enodebName));
                memcpy( table_entry->enodebName,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->enodebName_len =
                        request->requestvb->val_len;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENODEBCONFIG, rowIndex, COLUMN_ENODEBNAME);
                tlvArray.numTlvs++;
                break;
            case COLUMN_USESTATICIPADDRESS:
                table_entry->useStaticIpAddress     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENODEBCONFIG, rowIndex, COLUMN_USESTATICIPADDRESS);
                tlvArray.numTlvs++;
                break;
            case COLUMN_ENODEBSTATICIPADDR:
                table_entry->enodebStaticIpAddr     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENODEBCONFIG, rowIndex, COLUMN_ENODEBSTATICIPADDR);
                tlvArray.numTlvs++;
                break;
            case COLUMN_ENODEBNETMASKADDR:
                table_entry->enodebNetmaskAddr     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENODEBCONFIG, rowIndex, COLUMN_ENODEBNETMASKADDR);
                tlvArray.numTlvs++;
                break;
            case COLUMN_ENBREGISTRATIONACCEPTED:
                table_entry->enbRegistrationAccepted = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENODEBCONFIG, rowIndex, COLUMN_ENBREGISTRATIONACCEPTED);
                tlvArray.numTlvs++;
                break;
            case COLUMN_CONFIGCHANGEACKBYEMS:
                table_entry->configChangeAckByEms  = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENODEBCONFIG, rowIndex, COLUMN_CONFIGCHANGEACKBYEMS);
                tlvArray.numTlvs++;
                break;
            }
        }

        if ((request == NULL) && (g_sihEnbConfigSetReqProcessed EQ FALSE))
            /* Processed all requests and table entry is filled with
             * requested data. */
            {
            /* Set SIH Set Request Tag Info */
            sihTagInfo.tableId = ENODEBCONFIG;

            sihTagInfo.rowId = rowIndex; 

            status = sendEnbConfigSnmpSetRequest (sihTagInfo, &tlvArray);
            if (status EQ TRUE)
            {
                logInfo("%s","SET Succedded");
            }
            else
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_GENERR );
            }
        break;

    case MODE_SET_UNDO:
#ifndef PWAV_SIH 
        for (request=requests; request; request=request->next) {
            table_entry = (struct enbConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ENODEBID:
                table_entry->enodebId     = table_entry->old_enodebId;
                table_entry->old_enodebId = 0;
                break;
            case COLUMN_ENODEBNAME:
                memcpy( table_entry->enodebName,
                        table_entry->old_enodebName,
                        sizeof(table_entry->enodebName));
                memset( table_entry->old_enodebName, 0,
                        sizeof(table_entry->enodebName));
                table_entry->enodebName_len =
                        table_entry->old_enodebName_len;
                break;
            case COLUMN_PAGINGDRXCYCLE:
                table_entry->pagingDrxCycle     = table_entry->old_pagingDrxCycle;
                table_entry->old_pagingDrxCycle = 0;
                break;
            case COLUMN_MMEIPADDR:
                table_entry->mmeIpAddr     = table_entry->old_mmeIpAddr;
                table_entry->old_mmeIpAddr = 0;
                break;
            case COLUMN_SECUREMMELINK:
                table_entry->secureMmeLink     = table_entry->old_secureMmeLink;
                table_entry->old_secureMmeLink = 0;
                break;
            case COLUMN_SECURESGWLINK:
                table_entry->secureSgwLink     = table_entry->old_secureSgwLink;
                table_entry->old_secureSgwLink = 0;
                break;
            case COLUMN_ENODEBSTATICIPADDR:
                table_entry->enodebStaticIpAddr     = table_entry->old_enodebStaticIpAddr;
                table_entry->old_enodebStaticIpAddr = 0;
                break;
            case COLUMN_SCTPNUMINBOUNDSTREAMS:
                table_entry->sctpNumInboundStreams     = table_entry->old_sctpNumInboundStreams;
                table_entry->old_sctpNumInboundStreams = 0;
                break;
            case COLUMN_SCTPNUMOUTBOUNDSTREAMS:
                table_entry->sctpNumOutboundStreams     = table_entry->old_sctpNumOutboundStreams;
                table_entry->old_sctpNumOutboundStreams = 0;
                break;
            case COLUMN_ACTIVECELLID:
                table_entry->activeCellId     = table_entry->old_activeCellId;
                table_entry->old_activeCellId = 0;
                break;
            case COLUMN_UERESPONSETIMER:
                table_entry->ueResponseTimer     = table_entry->old_ueResponseTimer;
                table_entry->old_ueResponseTimer = 0;
                break;
            case COLUMN_RRCCONNREJWAITTIME:
                table_entry->rrcConnRejWaitTime     = table_entry->old_rrcConnRejWaitTime;
                table_entry->old_rrcConnRejWaitTime = 0;
                break;
            case COLUMN_LOCALTIME:
                memcpy( table_entry->localTime,
                        table_entry->old_localTime,
                        sizeof(table_entry->localTime));
                memset( table_entry->old_localTime, 0,
                        sizeof(table_entry->localTime));
                table_entry->localTime_len =
                        table_entry->old_localTime_len;
                break;
            case COLUMN_LOCALTIMEOFFSETFROMUTC:
                memcpy( table_entry->localTimeOffsetFromUTC,
                        table_entry->old_localTimeOffsetFromUTC,
                        sizeof(table_entry->localTimeOffsetFromUTC));
                memset( table_entry->old_localTimeOffsetFromUTC, 0,
                        sizeof(table_entry->localTimeOffsetFromUTC));
                table_entry->localTimeOffsetFromUTC_len =
                        table_entry->old_localTimeOffsetFromUTC_len;
                break;
            }
        }
#endif /* PWAV_SIH */
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
