/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef ENBREGCONFIG_H
#define ENBREGCONFIG_H

/* function declarations */
void init_enbRegConfig(void);
void initialize_table_enbRegConfigTable(void);

/* column number definitions for table enbRegConfigTable */
       #define COLUMN_BSID		1
       #define COLUMN_PUBLICDNSSERVER1		2
       #define COLUMN_PUBLICDNSSERVER2		3
       #define COLUMN_PRIVATEDNSSERVER1		4
       #define COLUMN_PRIVATEDNSSERVER2		5
       #define COLUMN_SECURITYGW1		6
       #define COLUMN_SECURITYGW2		7
       #define COLUMN_EMSADDR		8
       #define COLUMN_CONFIGUREDLATITUDE		9
       #define COLUMN_CONFIGUREDLONGITUDE		10
       #define COLUMN_SNMPCOMMUNITYSTRING		11
       #define COLUMN_TIMEANDLOCATIONSOURCETOUSE        12
       #define COLUMN_INITIALLOCALTIME			13
       #define COLUMN_INITIALLOCALTIMEOFFSETFROMUTC     14

#define ENB_REG_CONFIG_MAX_COL        COLUMN_INITIALLOCALTIMEOFFSETFROMUTC

#define ENB_REG_SNMPCOMMUNITYSTRING_LEN_MAX           64
#define ENB_REG_CONFIG_CONFIGUREDLATITUDE_LEN_MAX     13
#define ENB_REG_CONFIG_CONFIGUREDLONGITUDE_LEN_MAX    14
#define ENB_REG_CONFIG_IP_BUF_LEN_MAX	15
#define ENB_REG_CONFIG_TIME_LEN_MAX     18
#define ENB_REG_CONFIG_OFFSET_LEN_MAX   6           

    /* Typical data structure for a row entry */
typedef struct enbRegConfigTable_entry {
    /* Index values */
    unsigned int bsId;

    /* Column values */
    in_addr_t publicDNSServer1;
    in_addr_t publicDNSServer2;
    in_addr_t privateDNSServer1;
    in_addr_t privateDNSServer2;
    in_addr_t securityGW1;
    in_addr_t securityGW2;
    in_addr_t emsAddr;
    char configuredLatitude[ENB_REG_CONFIG_CONFIGUREDLATITUDE_LEN_MAX];
    size_t configuredLatitude_len;
    char configuredLongitude[ENB_REG_CONFIG_CONFIGUREDLONGITUDE_LEN_MAX];
    size_t configuredLongitude_len;
    char snmpCommunityString[ENB_REG_SNMPCOMMUNITYSTRING_LEN_MAX];
    size_t snmpCommunityString_len;
    unsigned int timeAndLocationSourceToUse;
    char initialLocalTime[ENB_REG_CONFIG_TIME_LEN_MAX];
    size_t initialLocalTime_len;
    char initialLocalTimeOffsetFromUTC[ENB_REG_CONFIG_OFFSET_LEN_MAX];
    size_t initialLocalTimeOffsetFromUTC_len;
    

    /* Illustrate using a simple linked list */
    int   valid;
    struct enbRegConfigTable_entry *next;
} enbRegConfigTableEntry;

#endif /* ENBREGCONFIG_H */
