/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "bs_modules.h"
#include "all_cfg.h"
#include "all_cmn.h"
#include "tlv_enc_dec.h"

#include "sih.h"
#include "syslog.h"
#include "enbRegConfig.h"

Netsnmp_Node_Handler      enbRegConfigTable_handler;
Netsnmp_First_Data_Point  enbRegConfigTable_get_first_data_point;
Netsnmp_Next_Data_Point   enbRegConfigTable_get_next_data_point;

struct enbRegConfigTable_entry  *enbRegConfigTable_head = NULL;
static TBOOL g_sihEnbRegConfigSetReqProcessed = FALSE;
static TBOOL g_sihEnbRegConfigGetReqProcessed = FALSE;
static UINT32 g_prevEnbRegConfigReqCount = 0;
static UINT32 g_enbRegConfigFirstCall = 0;

/* free_enbRegConfigTable */
/**
* @details 
*          This is the routine which frees the enb reg config entry.
*/
void free_enbRegConfigTable(void)
{
  enbRegConfigTableEntry  * current = enbRegConfigTable_head;

  if (current)
  {
  for (current = enbRegConfigTable_head->next ; current != NULL; current = current->next) {
    SNMP_FREE( current );
    }

  SNMP_FREE(enbRegConfigTable_head);
  enbRegConfigTable_head = NULL;
  }
  return;
}


/**
* @details 
*          This is the routine which handles get response from SIH Get Processor
*          and prepare the SNMP GET response for EMS.
* @param tlvArray contains pointer to TLV array.
*/
TBOOL sendEnbRegConfigSnmpGetResponse (
  IO TlvArray    *tlvArray
  )
{
  int  totalNumRow, totalNumCol, i=0, colmn=0;
  enbRegConfigTableEntry * prevPtr = NULL;

  printTLV(tlvArray);

  /* Total no. of Colmns */
  totalNumCol = ENB_REG_CONFIG_MAX_COL;
  /* Total no. of Row = (No. of TLV)/(No. of Columns) */
  totalNumRow = tlvArray->numTlvs/totalNumCol;

  for (i=1;  i <= totalNumRow;  i++)
      {
      enbRegConfigTableEntry *ptr=(enbRegConfigTableEntry *)malloc(sizeof(enbRegConfigTableEntry));

      clearBytes(ptr,sizeof(enbRegConfigTableEntry));

      /* Fill Data in TLV */
      for(colmn = 1 ; colmn <= totalNumCol ; colmn++)
        {
       if (colmn EQ COLUMN_BSID)
           {
            ptr->bsId = getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_PUBLICDNSSERVER1)
           {
            ptr->publicDNSServer1 = inet_addr(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_PUBLICDNSSERVER2)
           {
            ptr->publicDNSServer2 = inet_addr(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_PRIVATEDNSSERVER1)
           {
            ptr->privateDNSServer1 = inet_addr(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_PRIVATEDNSSERVER2)
           {
            ptr->privateDNSServer2 = inet_addr(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_SECURITYGW1)
           {
            ptr->securityGW1 = inet_addr(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_SECURITYGW2)
           {
            ptr->securityGW2 = inet_addr(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_EMSADDR)
           {
            ptr->emsAddr = inet_addr(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
       if (colmn EQ COLUMN_CONFIGUREDLATITUDE)
           {
            clearBytes (ptr->configuredLatitude, ENB_REG_CONFIG_CONFIGUREDLATITUDE_LEN_MAX);
            if (tlvArray->tlvInfo[colmn-1].len > 0)
                {
                 copyBytes (tlvArray->tlvInfo[colmn-1].data, tlvArray->tlvInfo[colmn-1].len, ptr->configuredLatitude);
                }
            ptr->configuredLatitude_len = strlen(ptr->configuredLatitude);
            continue;
           }
       if (colmn EQ COLUMN_CONFIGUREDLONGITUDE)
           {
            clearBytes (ptr->configuredLongitude, ENB_REG_CONFIG_CONFIGUREDLONGITUDE_LEN_MAX);
            if (tlvArray->tlvInfo[colmn-1].len > 0)
                {
                 copyBytes (tlvArray->tlvInfo[colmn-1].data, tlvArray->tlvInfo[colmn-1].len, ptr->configuredLongitude);
                }
            ptr->configuredLongitude_len = strlen(ptr->configuredLongitude);
            continue;
           }
       if (colmn EQ COLUMN_SNMPCOMMUNITYSTRING)
           {
            clearBytes (ptr->snmpCommunityString, ENB_REG_SNMPCOMMUNITYSTRING_LEN_MAX);
            if (tlvArray->tlvInfo[colmn-1].len > 0)
                {
                 copyBytes (tlvArray->tlvInfo[colmn-1].data, tlvArray->tlvInfo[colmn-1].len, ptr->snmpCommunityString);
                }
            ptr->snmpCommunityString_len = strlen(ptr->snmpCommunityString);
            continue;
           }
       if (colmn EQ COLUMN_TIMEANDLOCATIONSOURCETOUSE)
           {
            ptr->timeAndLocationSourceToUse = getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
       if (colmn EQ COLUMN_INITIALLOCALTIME)
           {
            clearBytes (ptr->initialLocalTime, ENB_REG_CONFIG_TIME_LEN_MAX);
            if (tlvArray->tlvInfo[colmn-1].len > 0)
                {
                 copyBytes (tlvArray->tlvInfo[colmn-1].data, tlvArray->tlvInfo[colmn-1].len, ptr->initialLocalTime);
                }
            ptr->initialLocalTime_len = strlen(ptr->initialLocalTime);
            continue;
           }
       if (colmn EQ COLUMN_INITIALLOCALTIMEOFFSETFROMUTC)
           {
            clearBytes (ptr->initialLocalTimeOffsetFromUTC, ENB_REG_CONFIG_OFFSET_LEN_MAX);
            if (tlvArray->tlvInfo[colmn-1].len > 0)
                {
                 copyBytes (tlvArray->tlvInfo[colmn-1].data, tlvArray->tlvInfo[colmn-1].len, ptr->initialLocalTimeOffsetFromUTC);
                }
            ptr->initialLocalTimeOffsetFromUTC_len = strlen(ptr->initialLocalTimeOffsetFromUTC);
            continue;
           }
        }

       ptr->next = NULL;

      if (prevPtr == NULL) {
           enbRegConfigTable_head =  prevPtr = ptr;
       }

      prevPtr->next = ptr;
      prevPtr = ptr;
     }
    prevPtr->next = NULL;

    if (enbRegConfigTable_head)
        return TRUE;
    else
        return FALSE;
}


/**
* @details 
*          This routine sends enodeb config set request to BSM, it uses SIH Set
*          Processor to create and send the message to BSM.
* @param sihTagInfo is used to have the tag information for set request.
*/
TBOOL sendEnbRegConfigSnmpSetRequest (
      IO TagInfo  sihTagInfo,
      IO TlvArray *tlvArray
      )
{
   enbRegConfigTableEntry * setReqData = NULL;
   TBOOL status = FALSE;
   int colmn = 0;
   unsigned char * ipAddr;
   struct in_addr ip;


   setReqData = enbRegConfigTable_head;

   /* Fill Data in TLV */
   for(colmn = 0; colmn < tlvArray->numTlvs; colmn++)
      {
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_BSID)
         {
           putUint32InArray( setReqData->bsId, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->bsId);
         }
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_PUBLICDNSSERVER1)
         {
           ip.s_addr = setReqData->publicDNSServer1;
           ipAddr = inet_ntoa(ip);
           copyBytes (ipAddr, strlen(ipAddr), tlvArray->tlvInfo[colmn].data);
           tlvArray->tlvInfo[colmn].len = ENB_REG_CONFIG_IP_BUF_LEN_MAX;
         }
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_PUBLICDNSSERVER2)
         {
           ip.s_addr = setReqData->publicDNSServer2;
           ipAddr = inet_ntoa(ip);
           copyBytes (ipAddr, strlen(ipAddr), tlvArray->tlvInfo[colmn].data);
           tlvArray->tlvInfo[colmn].len = ENB_REG_CONFIG_IP_BUF_LEN_MAX;
         }
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_PRIVATEDNSSERVER1)
         {
           ip.s_addr = setReqData->privateDNSServer1;
           ipAddr = inet_ntoa(ip);
           copyBytes (ipAddr, strlen(ipAddr), tlvArray->tlvInfo[colmn].data);
           tlvArray->tlvInfo[colmn].len = ENB_REG_CONFIG_IP_BUF_LEN_MAX;
         }
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_PRIVATEDNSSERVER2)
         {
           ip.s_addr = setReqData->privateDNSServer2;
           ipAddr = inet_ntoa(ip);
           copyBytes (ipAddr, strlen(ipAddr), tlvArray->tlvInfo[colmn].data);
           tlvArray->tlvInfo[colmn].len = ENB_REG_CONFIG_IP_BUF_LEN_MAX;
         }
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_SECURITYGW1)
         {
           ip.s_addr = setReqData->securityGW1;
           ipAddr = inet_ntoa(ip);
           copyBytes (ipAddr, strlen(ipAddr), tlvArray->tlvInfo[colmn].data);
           tlvArray->tlvInfo[colmn].len = ENB_REG_CONFIG_IP_BUF_LEN_MAX;
         }
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_SECURITYGW2)
         {
           ip.s_addr = setReqData->securityGW2;
           ipAddr = inet_ntoa(ip);
           copyBytes (ipAddr, strlen(ipAddr), tlvArray->tlvInfo[colmn].data);
           tlvArray->tlvInfo[colmn].len = ENB_REG_CONFIG_IP_BUF_LEN_MAX;
         }
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_EMSADDR)
         {
           ip.s_addr = setReqData->emsAddr;
           ipAddr = inet_ntoa(ip);
           copyBytes (ipAddr, strlen(ipAddr), tlvArray->tlvInfo[colmn].data);
           tlvArray->tlvInfo[colmn].len = ENB_REG_CONFIG_IP_BUF_LEN_MAX;
         }
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_CONFIGUREDLATITUDE)
         {
           copyBytes (setReqData->configuredLatitude, strlen(setReqData->configuredLatitude), tlvArray->tlvInfo[colmn].data);
           tlvArray->tlvInfo[colmn].len = ENB_REG_CONFIG_CONFIGUREDLATITUDE_LEN_MAX-1;
         }
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_CONFIGUREDLONGITUDE)
         {
           copyBytes (setReqData->configuredLongitude, strlen(setReqData->configuredLongitude), tlvArray->tlvInfo[colmn].data);
           tlvArray->tlvInfo[colmn].len = ENB_REG_CONFIG_CONFIGUREDLONGITUDE_LEN_MAX-1;
         }
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_SNMPCOMMUNITYSTRING)
         {
           copyBytes (setReqData->snmpCommunityString, strlen(setReqData->snmpCommunityString), tlvArray->tlvInfo[colmn].data);
           tlvArray->tlvInfo[colmn].len = ENB_REG_SNMPCOMMUNITYSTRING_LEN_MAX-1;
         }
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_TIMEANDLOCATIONSOURCETOUSE)
         {
           putUint32InArray( setReqData->timeAndLocationSourceToUse, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->timeAndLocationSourceToUse);
         }
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_INITIALLOCALTIME)
         {
           copyBytes (setReqData->initialLocalTime, strlen(setReqData->initialLocalTime), tlvArray->tlvInfo[colmn].data);
           tlvArray->tlvInfo[colmn].len = ENB_REG_CONFIG_TIME_LEN_MAX-1; 
         }
         if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_INITIALLOCALTIMEOFFSETFROMUTC)
         {
           copyBytes (setReqData->initialLocalTimeOffsetFromUTC, strlen(setReqData->initialLocalTimeOffsetFromUTC), tlvArray->tlvInfo[colmn].data);
           tlvArray->tlvInfo[colmn].len = ENB_REG_CONFIG_OFFSET_LEN_MAX-1; 
         }
       }

   /* Invoke SIH Set Processor */
   status = sihSetProcessor (sihTagInfo,  tlvArray);
   if (status EQ TRUE)
     {
      g_sihEnbRegConfigSetReqProcessed = TRUE;
      g_sihEnbRegConfigGetReqProcessed = FALSE;
      /* free the resources */
      free_enbRegConfigTable();
     }
   return status;
}


/**
* @details 
*          This is the routine for initializing enbRegConfig module.
*/
void
init_enbRegConfig(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_enbRegConfigTable();
}

/*  # Determine the first/last column names */

/** Initialize the enbRegConfigTable table by defining its contents and how it's structured */
void
initialize_table_enbRegConfigTable(void)
{
    const oid enbRegConfigTable_oid[] = {1,3,6,1,4,1,9344,501,ENBREGISTRATIONCONFIG,1};
    const size_t enbRegConfigTable_oid_len   = OID_LENGTH(enbRegConfigTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("enbRegConfig:init", "initializing table enbRegConfigTable\n"));

    reg = netsnmp_create_handler_registration(
              "enbRegConfigTable",     enbRegConfigTable_handler,
              enbRegConfigTable_oid, enbRegConfigTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_UNSIGNED,  /* index: bsId */
                           0);
    table_info->min_column = COLUMN_BSID;
    table_info->max_column = COLUMN_INITIALLOCALTIMEOFFSETFROMUTC;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = enbRegConfigTable_get_first_data_point;
    iinfo->get_next_data_point  = enbRegConfigTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}


#ifndef PWAV_SIH
/* create a new row in the (unsorted) table */
struct enbRegConfigTable_entry *
enbRegConfigTable_createEntry(
                 u_long  bsId,
                ) {
    struct enbRegConfigTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct enbRegConfigTable_entry);
    if (!entry)
        return NULL;

    entry->bsId = bsId;
    entry->next = enbRegConfigTable_head;
    enbRegConfigTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
enbRegConfigTable_removeEntry( struct enbRegConfigTable_entry *entry ) {
    struct enbRegConfigTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = enbRegConfigTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        enbRegConfigTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}
#endif /* PWAV_SIH */


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
enbRegConfigTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    TagInfo sihTagInfo;
    TBOOL status = FALSE;

    if (g_sihEnbRegConfigGetReqProcessed EQ FALSE)
        {
        /* Set SIH Get Request Tag Info */
        sihTagInfo.tableId = ENBREGISTRATIONCONFIG;
        sihTagInfo.rowId = CONFIG_ROW_ID_NONE;
        sihTagInfo.colId = CONFIG_COL_ID_NONE;

        status = sihGetProcessor (sihTagInfo);
        if ( status EQ TRUE )
            {
            logInfo("%s","Get Processor Succedded");
            if (enbRegConfigTable_head)
                {
		g_enbRegConfigFirstCall = 1;	
                g_sihEnbRegConfigGetReqProcessed = TRUE;
                }
            }
        else
            logError("%s","Get Processor Failed");
        }

    *my_loop_context = enbRegConfigTable_head;
    return enbRegConfigTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
enbRegConfigTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct enbRegConfigTable_entry *entry = (struct enbRegConfigTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_UNSIGNED, entry->bsId );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the enbRegConfigTable table */
int
enbRegConfigTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request = NULL;
    netsnmp_table_request_info *table_info = NULL;
    struct enbRegConfigTable_entry          *table_entry = NULL;
    int loopCount = 0;
    int ret;
    TagInfo sihTagInfo;
    TlvArray tlvArray;
    int rowIndex = 0, colId = 0;
    TBOOL status = FALSE;

    DEBUGMSGTL(("enbRegConfig:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {

            loopCount++;
            if (request->processed != 0)
            {
	     g_prevEnbRegConfigReqCount = 0;	
             g_sihEnbRegConfigGetReqProcessed = FALSE;

             /* free the resources */
             free_enbRegConfigTable();
             /* Here loopCount is decremented, Due to calling of free function two times in SNMP-GETNEXT
              * on single parameter -- 20/07/11 */
             loopCount--;
             continue;
            }

            /* perform anything here that you need to do before each
               request is processed. */

            /* the following extracts the my_data_context pointer set in
               the loop functions above.  You can then use the results to
               help return data for the columns of the enbRegConfigTable table
               in question */

            table_entry = (struct enbRegConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);

            if ( table_entry == NULL) {
                if (reqinfo->mode == MODE_GET) {
                    netsnmp_set_request_error(reqinfo, request,SNMP_NOSUCHINSTANCE);
                    continue;
                }
                /* XXX: no row existed, if you support creation and this is a
                   set, start dealing with it here, else continue */
            }

            table_info  =     netsnmp_extract_table_info(request);

            /* table_info->colnum contains the column number requested */
            /* table_info->indexes contains a linked list of snmp variable
               bindings for the indexes of the table.  Values in the list
               have been set corresponding to the indexes of the
               request */
            if (table_info==NULL) {
                continue;
            }
    
            switch (table_info->colnum) {
            case COLUMN_BSID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->bsId);
                break;
            case COLUMN_PUBLICDNSSERVER1:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_IPADDRESS,
                                            table_entry->publicDNSServer1);
                break;
            case COLUMN_PUBLICDNSSERVER2:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_IPADDRESS,
                                            table_entry->publicDNSServer2);
                break;
            case COLUMN_PRIVATEDNSSERVER1:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_IPADDRESS,
                                            table_entry->privateDNSServer1);
                break;
            case COLUMN_PRIVATEDNSSERVER2:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_IPADDRESS,
                                            table_entry->privateDNSServer2);
                break;
            case COLUMN_SECURITYGW1:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_IPADDRESS,
                                            table_entry->securityGW1);
                break;
            case COLUMN_SECURITYGW2:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_IPADDRESS,
                                            table_entry->securityGW2);
                break;
            case COLUMN_EMSADDR:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_IPADDRESS,
                                            table_entry->emsAddr);
                break;
            case COLUMN_CONFIGUREDLATITUDE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->configuredLatitude,
                                          table_entry->configuredLatitude_len);
                break;
            case COLUMN_CONFIGUREDLONGITUDE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->configuredLongitude,
                                          table_entry->configuredLongitude_len);
                break;
            case COLUMN_SNMPCOMMUNITYSTRING:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->snmpCommunityString,
                                          table_entry->snmpCommunityString_len);
                break;
            case COLUMN_TIMEANDLOCATIONSOURCETOUSE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->timeAndLocationSourceToUse);
                break;
            case COLUMN_INITIALLOCALTIME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->initialLocalTime,
                                          table_entry->initialLocalTime_len);
                break;
            case COLUMN_INITIALLOCALTIMEOFFSETFROMUTC:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->initialLocalTimeOffsetFromUTC,
                                          table_entry->initialLocalTimeOffsetFromUTC_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
	if(g_enbRegConfigFirstCall EQ 1)
         {
            g_enbRegConfigFirstCall = 0;
            g_prevEnbRegConfigReqCount = loopCount;
            // This will occur in case of, when SNMP-GET or SNMP-GETNEXT of Single Parameter occurred.
            // In the first call itself loopCount becomes one.
            // In General Case, the loopCount will be always > 1 because every table contains 
            // index column to fetch the row and remaining columns contain table attributes.
            if(loopCount EQ 1)
            {
               //Setting it to false in case of SNMP-GET request for single parameter.
               g_sihEnbRegConfigGetReqProcessed = FALSE;
               // Free all resources.
               free_enbRegConfigTable();
            }
         }
         else if(loopCount > 1 || g_prevEnbRegConfigReqCount > 1)
         {
            //update g_prevReqCount with current loopCount for next call of Table_handler
            g_prevEnbRegConfigReqCount = loopCount;
         }
         else if(loopCount EQ 1)
         {
            //Setting it to false in case of SNMP-GET request for single parameter.
            g_sihEnbRegConfigGetReqProcessed = FALSE;
            // Free all resources.
            free_enbRegConfigTable();
         }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
#ifndef PWAV_SIH
        for (request=requests; request; request=request->next) {
            table_entry = (struct enbRegConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_BSID:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_PUBLICDNSSERVER1:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_PUBLICDNSSERVER2:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_PRIVATEDNSSERVER1:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_PRIVATEDNSSERVER2:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_SECURITYGW1:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_SECURITYGW2:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_EMSADDR:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_CONFIGUREDLATITUDE:
                /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->configuredLatitude));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_CONFIGUREDLONGITUDE:
                /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->configuredLongitude));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_SNMPCOMMUNITYSTRING:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->snmpCommunityString));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
#endif /* PWAV_SIH */
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        g_sihEnbRegConfigSetReqProcessed = FALSE;

        clearBytes(&sihTagInfo, sizeof(TagInfo));
        clearBytes(&tlvArray, sizeof(TlvArray));

        for (request=requests; request; request=request->next) {
            table_entry = (struct enbRegConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            if(table_entry == NULL){
                logInfo(" %s\n", "table_entry is NULL");
                if (reqinfo->mode == MODE_SET_ACTION) {
                    netsnmp_set_request_error(reqinfo, request,SNMP_NOSUCHINSTANCE);
                    continue;
                }
                /* XXX: no row existed, if you support creation and this is a
                   set, start dealing with it here, else continue */
            }

            if(table_info == NULL){
                logInfo(" %s\n", "table_info is NULL");
                continue;
            }

            colId = table_info->colnum;
            /* set the row index */
            rowIndex = requests->index;
    
            switch (table_info->colnum) {
            case COLUMN_BSID:
                table_entry->bsId     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENBREGISTRATIONCONFIG, rowIndex, COLUMN_BSID);
                tlvArray.numTlvs++;
                break;
            case COLUMN_PUBLICDNSSERVER1:
                table_entry->publicDNSServer1     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENBREGISTRATIONCONFIG, rowIndex, COLUMN_PUBLICDNSSERVER1);
                tlvArray.numTlvs++;
                break;
            case COLUMN_PUBLICDNSSERVER2:
                table_entry->publicDNSServer2     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENBREGISTRATIONCONFIG, rowIndex, COLUMN_PUBLICDNSSERVER2);
                tlvArray.numTlvs++;
                break;
            case COLUMN_PRIVATEDNSSERVER1:
                table_entry->privateDNSServer1     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENBREGISTRATIONCONFIG, rowIndex, COLUMN_PRIVATEDNSSERVER1);
                tlvArray.numTlvs++;
                break;
            case COLUMN_PRIVATEDNSSERVER2:
                table_entry->privateDNSServer2     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENBREGISTRATIONCONFIG, rowIndex, COLUMN_PRIVATEDNSSERVER2);
                tlvArray.numTlvs++;
                break;
            case COLUMN_SECURITYGW1:
                table_entry->securityGW1     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENBREGISTRATIONCONFIG, rowIndex, COLUMN_SECURITYGW1);
                tlvArray.numTlvs++;
                break;
            case COLUMN_SECURITYGW2:
                table_entry->securityGW2     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENBREGISTRATIONCONFIG, rowIndex, COLUMN_SECURITYGW2);
                tlvArray.numTlvs++;
                break;
            case COLUMN_EMSADDR:
                table_entry->emsAddr     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENBREGISTRATIONCONFIG, rowIndex, COLUMN_EMSADDR);
                tlvArray.numTlvs++;
                break;
            case COLUMN_CONFIGUREDLATITUDE:
                memset( table_entry->configuredLatitude, 0,
                        sizeof(table_entry->configuredLatitude));
                memcpy( table_entry->configuredLatitude,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->configuredLatitude_len =
                        request->requestvb->val_len;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENBREGISTRATIONCONFIG, rowIndex, COLUMN_CONFIGUREDLATITUDE);
                tlvArray.numTlvs++;
                break;
            case COLUMN_CONFIGUREDLONGITUDE:
                memset( table_entry->configuredLongitude, 0,
                        sizeof(table_entry->configuredLongitude));
                memcpy( table_entry->configuredLongitude,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->configuredLongitude_len =
                        request->requestvb->val_len;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENBREGISTRATIONCONFIG, rowIndex, COLUMN_CONFIGUREDLONGITUDE);
                tlvArray.numTlvs++;
                break;
            case COLUMN_SNMPCOMMUNITYSTRING:
                memset( table_entry->snmpCommunityString, 0,
                        sizeof(table_entry->snmpCommunityString));
                memcpy( table_entry->snmpCommunityString,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->snmpCommunityString_len =
                        request->requestvb->val_len;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENBREGISTRATIONCONFIG, rowIndex, COLUMN_SNMPCOMMUNITYSTRING);
                tlvArray.numTlvs++;
                break;
            case COLUMN_TIMEANDLOCATIONSOURCETOUSE:
                table_entry->timeAndLocationSourceToUse     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENBREGISTRATIONCONFIG, rowIndex, COLUMN_TIMEANDLOCATIONSOURCETOUSE);
                tlvArray.numTlvs++;
                break;
            case COLUMN_INITIALLOCALTIME:
                memset( table_entry->initialLocalTime, 0,
                        sizeof(table_entry->initialLocalTime));
                memcpy( table_entry->initialLocalTime,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->initialLocalTime_len =
                        request->requestvb->val_len;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENBREGISTRATIONCONFIG, rowIndex, COLUMN_INITIALLOCALTIME);
                tlvArray.numTlvs++;
                break;
            case COLUMN_INITIALLOCALTIMEOFFSETFROMUTC:
                memset( table_entry->initialLocalTimeOffsetFromUTC, 0,
                        sizeof(table_entry->initialLocalTimeOffsetFromUTC));
                memcpy( table_entry->initialLocalTimeOffsetFromUTC,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->initialLocalTimeOffsetFromUTC_len =
                        request->requestvb->val_len;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, ENBREGISTRATIONCONFIG, rowIndex, COLUMN_INITIALLOCALTIMEOFFSETFROMUTC);
                tlvArray.numTlvs++;
                break;
            }
        }

        if ((request == NULL) && (g_sihEnbRegConfigSetReqProcessed EQ FALSE))
            /* Processed all requests and table entry is filled with
             * requested data. */
            {
            /* Set SIH Set Request Tag Info */
            sihTagInfo.tableId = ENBREGISTRATIONCONFIG;

            sihTagInfo.rowId = rowIndex;

            status = sendEnbRegConfigSnmpSetRequest (sihTagInfo, &tlvArray);
            if (status EQ TRUE)
            {
                logInfo("%s","SET Succedded");
            }
            else
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_GENERR );
            }

        break;

    case MODE_SET_UNDO:
#ifndef PWAV_SIH
        for (request=requests; request; request=request->next) {
            table_entry = (struct enbRegConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_BSID:
                table_entry->bsId     = table_entry->old_bsId;
                table_entry->old_bsId = 0;
                break;
            case COLUMN_PUBLICDNSSERVER1:
                table_entry->publicDNSServer1     = table_entry->old_publicDNSServer1;
                table_entry->old_publicDNSServer1 = 0;
                break;
            case COLUMN_PUBLICDNSSERVER2:
                table_entry->publicDNSServer2     = table_entry->old_publicDNSServer2;
                table_entry->old_publicDNSServer2 = 0;
                break;
            case COLUMN_PRIVATEDNSSERVER1:
                table_entry->privateDNSServer1     = table_entry->old_privateDNSServer1;
                table_entry->old_privateDNSServer1 = 0;
                break;
            case COLUMN_PRIVATEDNSSERVER2:
                table_entry->privateDNSServer2     = table_entry->old_privateDNSServer2;
                table_entry->old_privateDNSServer2 = 0;
                break;
            case COLUMN_SECURITYGW1:
                table_entry->securityGW1     = table_entry->old_securityGW1;
                table_entry->old_securityGW1 = 0;
                break;
            case COLUMN_SECURITYGW2:
                table_entry->securityGW2     = table_entry->old_securityGW2;
                table_entry->old_securityGW2 = 0;
                break;
            case COLUMN_EMSADDR:
                table_entry->emsAddr     = table_entry->old_emsAddr;
                table_entry->old_emsAddr = 0;
                break;
            case COLUMN_CONFIGUREDLATITUDE:
                memcpy( table_entry->configuredLatitude,
                        table_entry->old_configuredLatitude,
                        sizeof(table_entry->configuredLatitude));
                memset( table_entry->old_configuredLatitude, 0,
                        sizeof(table_entry->configuredLatitude));
                table_entry->configuredLatitude_len =
                        table_entry->old_configuredLatitude_len;
                break;
            case COLUMN_CONFIGUREDLONGITUDE:
                memcpy( table_entry->configuredLongitude,
                        table_entry->old_configuredLongitude,
                        sizeof(table_entry->configuredLongitude));
                memset( table_entry->old_configuredLongitude, 0,
                        sizeof(table_entry->configuredLongitude));
                table_entry->configuredLongitude_len =
                        table_entry->old_configuredLongitude_len;
                break;
            case COLUMN_SNMPCOMMUNITYSTRING:
                memcpy( table_entry->snmpCommunityString,
                        table_entry->old_snmpCommunityString,
                        sizeof(table_entry->snmpCommunityString));
                memset( table_entry->old_snmpCommunityString, 0,
                        sizeof(table_entry->snmpCommunityString));
                table_entry->snmpCommunityString_len =
                        table_entry->old_snmpCommunityString_len;
                break;
            }
        }
#endif /* PWAV_SIH */
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
