/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef ETHERNETCOUNTERS_H
#define ETHERNETCOUNTERS_H

/* function declarations */
void init_ethernetCounters(void);
void initialize_table_ethernetCountersTable(void);

/* column number definitions for table ethernetCountersTable */
       #define COLUMN_PWAV_IFINDEX		1
       #define COLUMN_PWAV_IFDESCR		2
       #define COLUMN_PWAV_IFTYPE		3
       #define COLUMN_PWAV_IFMTU		4
       #define COLUMN_PWAV_IFSPEED		5
       #define COLUMN_PWAV_IFPHYSADDRESS		6
       #define COLUMN_PWAV_IFADMINSTATUS		7
       #define COLUMN_PWAV_IFOPERSTATUS		8
       #define COLUMN_PWAV_IFLASTCHANGE		9
       #define COLUMN_PWAV_IFINOCTETS		10
       #define COLUMN_PWAV_IFINUCASTPKTS		11
       #define COLUMN_PWAV_IFINNUCASTPKTS		12
       #define COLUMN_PWAV_IFINDISCARDS		13
       #define COLUMN_PWAV_IFINERRORS		14
       #define COLUMN_PWAV_IFINUNKNOWNPROTOS		15
       #define COLUMN_PWAV_IFOUTOCTETS		16
       #define COLUMN_PWAV_IFOUTUCASTPKTS		17
       #define COLUMN_PWAV_IFOUTNUCASTPKTS		18
       #define COLUMN_PWAV_IFOUTDISCARDS		19
       #define COLUMN_PWAV_IFOUTERRORS		20
       #define COLUMN_PWAV_IFOUTQLEN		21
       #define COLUMN_PWAV_ETHERNET_COUNTERS_LASTCOLLECTEDAT   22

#define ETHERNET_COUNTERS_MAX_COL COLUMN_PWAV_ETHERNET_COUNTERS_LASTCOLLECTEDAT

#define ETHERNET_COUNTERS_IFDESC_LEN_MAX  256

#define ETHERNET_COUNTERS_PHY_ADDR_LEN_MAX  18

#define ETHERNET_COUNTERS_LCOLLECT_BUF_LEN_MAX 18

    /* Typical data structure for a row entry */
typedef struct ethernetCountersTable_entry {
    /* Index values */
    unsigned int ifIndex;

    /* Column values */
    char ifDescr[ETHERNET_COUNTERS_IFDESC_LEN_MAX];
    size_t ifDescr_len;
    unsigned int ifType;
    int ifMtu;
    unsigned int ifSpeed;
    char ifPhysAddress[ETHERNET_COUNTERS_PHY_ADDR_LEN_MAX];
    size_t ifPhysAddress_len;
    unsigned int ifAdminStatus;
    unsigned int ifOperStatus;
    unsigned int ifLastChange;
    unsigned int ifInOctets;
    unsigned int ifInUcastPkts;
    unsigned int ifInNUcastPkts;
    unsigned int ifInDiscards;
    unsigned int ifInErrors;
    unsigned int ifInUnknownProtos;
    unsigned int ifOutOctets;
    unsigned int ifOutUcastPkts;
    unsigned int ifOutNUcastPkts;
    unsigned int ifOutDiscards;
    unsigned int ifOutErrors;
    unsigned int ifOutQLen;
    char lastCollectedAt[ETHERNET_COUNTERS_LCOLLECT_BUF_LEN_MAX];
    size_t lastCollectedAt_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct ethernetCountersTable_entry *next;
}ethernetCountersTableEntry;

#endif /* ETHERNETCOUNTERS_H */
