/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17695 2009-07-21 12:22:18Z dts12 $
 */
#ifndef FILEUPLOADSTATUS_H
#define FILEUPLOADSTATUS_H

/* defines */
/* column number definitions for table fileUploadStatusTable */
#define COLUMN_UPINDEX            1
#define COLUMN_FILEUPLOADCOMMANDRECEIVED              2
#define COLUMN_UPSTSFILENAME                        3
#define COLUMN_UPLOADSTATUS               4
#define COLUMN_UPPERCENTAGECOMPLETE             5

#define FILE_UPLOAD_STATUS_MAX_COL    COLUMN_UPPERCENTAGECOMPLETE

#define FILE_UPLOAD_BUFFER_LEN_MAX                  257

/* function declarations */
void init_fileUploadStatus(void);
void initialize_table_fileUploadStatusTable(void);

/* structures */
/* Typical data structure for a row entry */
struct fileUploadStatusTable_entry {
    /* Index values */
    unsigned int index;

    /* Column values */
    unsigned int  fileUploadCommandReceived;
    char fileName[FILE_UPLOAD_BUFFER_LEN_MAX];
    size_t fileName_len;
    unsigned int  uploadStatus;
    unsigned int  percentageComplete;

    /* Illustrate using a simple linked list */
    int   valid;
    struct fileUploadStatusTable_entry *next;
};
#endif /* FILEUPLOADSTATUS_H */
