/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef LOCATIONSTATUS_H
#define LOCATIONSTATUS_H

/* function declarations */
void init_locationStatus(void);
void initialize_table_locationStatusTable(void);

/* column number definitions for table locationStatusTable */
       #define COLUMN_LOCATION_STATUS_INDEX		1
       #define COLUMN_LOCATIONSOURCE		2
       #define COLUMN_LATITUDE		3
       #define COLUMN_LONGITUDE		4

#define LOCATION_STATUS_MAX_COL   COLUMN_LONGITUDE
#define LOCATION_STATUS_LATI_MAX_BUF_LEN        13
#define LOCATION_STATUS_LONG_MAX_BUF_LEN        14

    /* Typical data structure for a row entry */
typedef struct locationStatusTable_entry {
    /* Index values */
    unsigned int index;

    /* Column values */
    unsigned int locationSource;
    char latitude[LOCATION_STATUS_LATI_MAX_BUF_LEN];
    size_t latitude_len;
    char longitude[LOCATION_STATUS_LONG_MAX_BUF_LEN];
    size_t longitude_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct locationStatusTable_entry *next;
}locationStatusTableEntry;

#endif /* LOCATIONSTATUS_H */
