/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef MACGENCOUNTERS_H
#define MACGENCOUNTERS_H

/* function declarations */
void init_macGenCounters(void);
void initialize_table_macGenCountersTable(void);

/* column number definitions for table macGenCountersTable */
       #define COLUMN_MAC_GEN_COUNTERS_INDEX		1
       #define COLUMN_NUMHARQFAIL			2
       #define COLUMN_NUMUECFG				3
       #define COLUMN_NUMCELLCFG			4
       #define COLUMN_MAC_GEN_COUNTERS_LASTCOLLECTEDAT	5

#define MAC_GEN_COUNTERS_MAX_COL COLUMN_MAC_GEN_COUNTERS_LASTCOLLECTEDAT

#define MAC_GEN_COUNTERS_LCOLLECT_BUF_LEN_MAX 18

    /* Typical data structure for a row entry */
typedef struct macGenCountersTable_entry {
    /* Index values */
    unsigned int index;

    /* Column values */
    unsigned int numHarqFail;
    unsigned int numUeCfg;
    unsigned short numCellCfg;
    char lastCollectedAt[MAC_GEN_COUNTERS_LCOLLECT_BUF_LEN_MAX];
    size_t lastCollectedAt_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct macGenCountersTable_entry *next;
}macGenCountersTableEntry;

#endif /* MACGENCOUNTERS_H */
