/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef QOSCONFIG_H
#define QOSCONFIG_H

/* function declarations */
void init_qosConfig(void);
void initialize_table_qosConfigTable(void);

/* column number definitions for table qosConfigTable */
       #define COLUMN_QOSPROFILEID		1
       #define COLUMN_QOSPROFILENAME		2
       #define COLUMN_QCI			3
       #define COLUMN_RLCMODE			4
       #define COLUMN_AMRLCTPOLLRETRANSMIT	5
       #define COLUMN_AMRLCPOLLPDU		6
       #define COLUMN_AMRLCPOLLBYTE		7
       #define COLUMN_AMRLCMAXRETXTHRESHOLD	8
       #define COLUMN_AMRLCTREORDERING		9
       #define COLUMN_AMRLCTSTATUSPROHIBIT	10
       #define COLUMN_DISCARDTIMER		11
       #define COLUMN_STATUSREPORTREQUIRED	12
       #define COLUMN_DRBPRIORITY       	13
       #define COLUMN_DRBPRIORITISEDBITRATE     14
       #define COLUMN_DRBBUCKETSIZEDURATION     15
       #define COLUMN_LOGICALCHANNELGROUP       16

#define QOS_CONFIG_MAX_COL COLUMN_LOGICALCHANNELGROUP

#define QOS_CONFIG_BUF_LEN_MAX  15
#define QOS_BUFFER_LEN_MAX   16

  /* Typical data structure for a row entry */
typedef struct qosConfigTable_entry {
    /* Index values */
    unsigned int qosProfileId;

    /* Column values */
    char qosProfileName[QOS_BUFFER_LEN_MAX];
    size_t qosProfileName_len;
    unsigned char qci;
    unsigned int rlcMode;
    unsigned int amRlcTPollRetransmit;
    unsigned int amRlcPollPDU;
    unsigned int amRlcPollByte;
    unsigned int amRlcMaxRetxThreshold;
    unsigned int amRlcTReordering;
    unsigned int amRlcTStatusProhibit;
    unsigned int discardTimer;
    unsigned char statusReportRequired;
    unsigned char drbPriority;
    unsigned int  drbPrioritisedBitRate;
    unsigned int  drbBucketSizeDuration;
    unsigned char logicalChannelGroup;
    
    /* Illustrate using a simple linked list */
    int   valid;
    struct qosConfigTable_entry *next;
}qosConfigTableEntry;

#endif /* QOSCONFIG_H */
