/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef RLCGENCOUNTERS_H
#define RLCGENCOUNTERS_H

/* function declarations */
void init_rlcGenCounters(void);
void initialize_table_rlcGenCountersTable(void);

/* column number definitions for table rlcGenCountersTable */
       #define COLUMN_RLC_GEN_COUNTERS_INDEX		1
       #define COLUMN_RLC_GEN_COUNTERS_NUMUECFG		2
       #define COLUMN_PDUSRECV				3
       #define COLUMN_PDUSSENT				4
       #define COLUMN_PDUSRETX				5
       #define COLUMN_BYTESRECV				6
       #define COLUMN_BYTESSENT				7
       #define COLUMN_UNEXPPDUSRECV			8
       #define COLUMN_ERRORPDUSRECV			9
       #define COLUMN_PROTTIMEOUT			10
       #define COLUMN_NUMOFRB				11
       #define COLUMN_NUMSDUDISC			12
       #define COLUMN_RLC_GEN_COUNTERS_LASTCOLLECTEDAT  	13
	

#define RLC_GEN_COUNTERS_MAX_COL  COLUMN_RLC_GEN_COUNTERS_LASTCOLLECTEDAT

#define RLC_GEN_COUNTERS_LCOLLECT_BUF_LEN_MAX 18

    /* Typical data structure for a row entry */
typedef struct rlcGenCountersTable_entry {
    /* Index values */
    unsigned int index;

    /* Column values */
    unsigned int numUeCfg;
    unsigned int pdusRecv;
    unsigned int pdusSent;
    unsigned int pdusRetx;
    unsigned int bytesRecv;
    unsigned int bytesSent;
    unsigned int unexpPdusRecv;
    unsigned int errorPdusRecv;
    unsigned int protTimeOut;
    unsigned int numOfRb;
    unsigned int numSduDisc;
    char lastCollectedAt[RLC_GEN_COUNTERS_LCOLLECT_BUF_LEN_MAX];
    size_t lastCollectedAt_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct rlcGenCountersTable_entry *next;
}rlcGenCountersTableEntry;

#endif /* RLCGENCOUNTERS_H */
