/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef SWACTIVATIONSTATUS_H
#define SWACTIVATIONSTATUS_H

/* function declarations */
void init_swActivationStatus(void);
void initialize_table_swActivationStatusTable(void);

/* column number definitions for table swActivationStatusTable */
       #define COLUMN_SWACTIVATION_STATUS_INDEX		1
       #define COLUMN_SWACTIVATION_STATUS_VERSION		2
       #define COLUMN_SWSTATUS		3

#define SWACTIVATION_STATUS_MAX_COL    COLUMN_SWSTATUS

#define SWACTIVATION_STATUS_VERSION_BUFFER_LEN_MAX    20

    /* Typical data structure for a row entry */
struct swActivationStatusTable_entry {
    /* Index values */
    unsigned int index;

    /* Column values */
    char version[SWACTIVATION_STATUS_VERSION_BUFFER_LEN_MAX];
    size_t version_len;
    unsigned int swStatus;

    /* Illustrate using a simple linked list */
    int   valid;
    struct swActivationStatusTable_entry *next;
};

#endif /* SWACTIVATIONSTATUS_H */
