/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "bs_modules.h"
#include "all_cfg.h"
#include "all_cmn.h"
#include "tlv_enc_dec.h"

#include "sih.h"
#include "syslog.h"

#include "sysInfo3Config.h"

Netsnmp_Node_Handler sysInfo3ConfigTable_handler;
Netsnmp_First_Data_Point  sysInfo3ConfigTable_get_first_data_point;
Netsnmp_Next_Data_Point   sysInfo3ConfigTable_get_next_data_point;

struct sysInfo3ConfigTable_entry  *sysInfo3ConfigTable_head = NULL;
static TBOOL g_sihSysInfo3ConfigSetReqProcessed = FALSE;
static TBOOL g_sihSysInfo3ConfigGetReqProcessed = FALSE;
static UINT32 g_prevSysInfo3ConfigReqCount = 0;
static UINT32 g_sysInfo3ConfigFirstCall = 0;

/* free_sysInfo3ConfigTable */
/**
* @details 
*          This is the routine which frees the sysInfo3 config entry. 
*/
void free_sysInfo3ConfigTable(void)
{
  sysInfo3ConfigTableEntry  * current = sysInfo3ConfigTable_head;

  if (current) 
  {
  for (current = sysInfo3ConfigTable_head->next ; current != NULL; current = current->next) {
    SNMP_FREE( current );  
    }
   
  SNMP_FREE(sysInfo3ConfigTable_head);
  sysInfo3ConfigTable_head = NULL;
  }
  return;
}


/**
* @details 
*          This is the routine which handles get response from SIH Get Processor
*          and prepare the SNMP GET response for EMS. 
* @param tlvArray contains pointer to TLV array.     
*/
TBOOL sendSysInfo3ConfigSnmpGetResponse (
  IO TlvArray    *tlvArray
  )
{
  int  totalNumRow, totalNumCol, i=0, colmn=0;
  sysInfo3ConfigTableEntry * prevPtr = NULL;

  printTLV(tlvArray);

  /* Total no. of Colmns */
  totalNumCol = SYSINFO3_CONFIG_MAX_COL;
  /* Total no. of Row = (No. of TLV)/(No. of Columns) */
  totalNumRow = tlvArray->numTlvs/totalNumCol;

  for (i=1;  i <= totalNumRow;  i++) 
      {
      sysInfo3ConfigTableEntry *ptr=(sysInfo3ConfigTableEntry *)malloc(sizeof(sysInfo3ConfigTableEntry));

      clearBytes(ptr,sizeof(sysInfo3ConfigTableEntry));

      /* Fill Data in TLV */
      for(colmn = 1 ; colmn <= totalNumCol ; colmn++)
        {
       if (colmn EQ COLUMN_SYSINFO3PROFILEID)
           {
            ptr->sysInfo3ProfileId = getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }        
       if (colmn EQ COLUMN_QHYST)
           {
            ptr->qHyst = getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }        
       if (colmn EQ COLUMN_THRESHSERVINGLOW)
           {
            ptr->threshServingLow = getUint8FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }        
        if (colmn EQ COLUMN_CELLRESELECTIONPRIORITY)
           {
            ptr->cellReselectionPriority = getUint8FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_SYSINFO3QRXLEVMIN)
           {
            ptr->qRxLevMin = getUint8FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_SYSINFO3PMAX)
           {
            ptr->pMax = getUint8FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_SINTRASEARCH)
           {
            ptr->sIntraSearch = getUint8FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }        
        if (colmn EQ COLUMN_ALLOWMEASBW)
           {
            ptr->allowMeasBw = getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_NEIGHCELLCONFIG)
           {
            ptr->neighCellConfig = getUint8FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_TRESELECTIONEUTRA)
           {
            ptr->tReselectionEutra = getUint8FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_PRESENCEANTENNAPORT1)
           {
            ptr->presenceAntennaPort1 = getUint8FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        }

       ptr->next = NULL;

      if (prevPtr == NULL) {
           sysInfo3ConfigTable_head =  prevPtr = ptr;
       }

      prevPtr->next = ptr;
      prevPtr = ptr;
     }
    prevPtr->next = NULL;

    if (sysInfo3ConfigTable_head)
        return TRUE;
    else
        return FALSE;
}

/**
* @details 
*          This routine sends sysInfo3 config set request to BSM, it uses SIH Set 
*          Processor to create and send the message to BSM. 
* @param sihTagInfo is used to have the tag information for set request.
*/
TBOOL sendSysInfo3ConfigSnmpSetRequest ( 
      IO TagInfo  sihTagInfo,
      IO TlvArray *tlvArray
      )
{
   sysInfo3ConfigTableEntry * setReqData = NULL;   
   TBOOL status = FALSE;
   int colmn = 0;
   unsigned char * ipAddr;
   struct in_addr ip;
 
   setReqData = sysInfo3ConfigTable_head;

   /* Fill Data in TLV */
   for(colmn = 0; colmn < tlvArray->numTlvs; colmn++)
   {
       if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_SYSINFO3PROFILEID)
       {
           putUint32InArray( setReqData->sysInfo3ProfileId, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->sysInfo3ProfileId);     
       }
       if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_QHYST)
       {
           putUint32InArray( setReqData->qHyst, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->qHyst);   
       }
       if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_THRESHSERVINGLOW)
       {
           putUint8InArray( setReqData->threshServingLow, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->threshServingLow); 
       }
       if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_CELLRESELECTIONPRIORITY)
       {
           putUint8InArray( setReqData->cellReselectionPriority, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->cellReselectionPriority); 
       }
       if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_SYSINFO3QRXLEVMIN)
       {
           putUint8InArray( setReqData->qRxLevMin, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->qRxLevMin);     
       }          
       if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_SYSINFO3PMAX)
       {
           putUint8InArray( setReqData->pMax, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->pMax);     
       }          
       if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_SINTRASEARCH)
       {
           putUint8InArray( setReqData->sIntraSearch, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->sIntraSearch);
       }       
       if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_ALLOWMEASBW)
       {
           putUint32InArray( setReqData->allowMeasBw, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->allowMeasBw);     
       }   
       if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_NEIGHCELLCONFIG)
       {
           putUint8InArray( setReqData->neighCellConfig, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->neighCellConfig);     
       }          
       if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_TRESELECTIONEUTRA)
       {
           putUint8InArray( setReqData->tReselectionEutra, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->tReselectionEutra);     
       }          
       if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_PRESENCEANTENNAPORT1)
       {
           putUint8InArray( setReqData->presenceAntennaPort1, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->presenceAntennaPort1);     
       }          
   }

   /* Invoke SIH Set Processor */
   status = sihSetProcessor (sihTagInfo, tlvArray);
   if (status EQ TRUE)
     {
      g_sihSysInfo3ConfigSetReqProcessed = TRUE;
      g_sihSysInfo3ConfigGetReqProcessed = FALSE;
      /* free the resources */      
      free_sysInfo3ConfigTable(); 
     }
   return status;
}


/**
* @details 
*          This is the routine for initializing sysInfo3Config module.
*/
void
init_sysInfo3Config(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_sysInfo3ConfigTable();
}

/*   Determine the first/last column names

* Initialize the sysInfo3ConfigTable table by defining its contents and how it's structured */
void
initialize_table_sysInfo3ConfigTable(void)
{
    const oid sysInfo3ConfigTable_oid[] = {1,3,6,1,4,1,9344,501,SYSINFO3CONFIG,1};
    const size_t sysInfo3ConfigTable_oid_len   = OID_LENGTH(sysInfo3ConfigTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("sysInfo3Config:init", "initializing table sysInfo3ConfigTable\n"));

    reg = netsnmp_create_handler_registration(
              "sysInfo3ConfigTable",     sysInfo3ConfigTable_handler,
              sysInfo3ConfigTable_oid, sysInfo3ConfigTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_UNSIGNED,  /* index: sysInfo3ProfileId */
                           0);
    table_info->min_column = COLUMN_SYSINFO3PROFILEID;
    table_info->max_column = COLUMN_PRESENCEANTENNAPORT1;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = sysInfo3ConfigTable_get_first_data_point;
    iinfo->get_next_data_point  = sysInfo3ConfigTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}


#ifndef PWAV_SIH 
/* create a new row in the (unsorted) table */
struct sysInfo3ConfigTable_entry *
sysInfo3ConfigTable_createEntry(
                 unsigned int  sysInfo3ProfileId,
                ) {
    struct sysInfo3ConfigTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct sysInfo3ConfigTable_entry);
    if (!entry)
        return NULL;

    entry->sysInfo3ProfileId = sysInfo3ProfileId;
    entry->next = sysInfo3ConfigTable_head;
    sysInfo3ConfigTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
sysInfo3ConfigTable_removeEntry( struct sysInfo3ConfigTable_entry *entry ) {
    struct sysInfo3ConfigTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = sysInfo3ConfigTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        sysInfo3ConfigTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}
#endif /* PWAV_SIH */


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
sysInfo3ConfigTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    TagInfo sihTagInfo;
    TBOOL status = FALSE;

    if (g_sihSysInfo3ConfigGetReqProcessed EQ FALSE)
        {
        /* Set SIH Get Request Tag Info */
        sihTagInfo.tableId = SYSINFO3CONFIG;
        sihTagInfo.rowId = CONFIG_ROW_ID_NONE; 
        sihTagInfo.colId = CONFIG_COL_ID_NONE;                

        status = sihGetProcessor (sihTagInfo);
        if ( status EQ TRUE )
            {
            logInfo("%s","Get Processor Succedded");
            if (sysInfo3ConfigTable_head)
                {
		g_sysInfo3ConfigFirstCall = 1;
                g_sihSysInfo3ConfigGetReqProcessed = TRUE;
                }
            }
        else
            logError("%s","Get Processor Failed");
        }        
    
    *my_loop_context = sysInfo3ConfigTable_head;
    return sysInfo3ConfigTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
sysInfo3ConfigTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct sysInfo3ConfigTable_entry *entry = (struct sysInfo3ConfigTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_UNSIGNED, entry->sysInfo3ProfileId );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the sysInfo3ConfigTable table */
int
sysInfo3ConfigTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request = NULL;
    netsnmp_table_request_info *table_info = NULL;
    struct sysInfo3ConfigTable_entry          *table_entry = NULL;
    int loopCount = 0;
    int ret;
    TagInfo sihTagInfo;
    TlvArray tlvArray;
    int rowIndex = 0, colId = 0;
    TBOOL status = FALSE;    


    DEBUGMSGTL(("sysInfo3Config:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {

            loopCount++;
            if (request->processed != 0)
            {
	     g_prevSysInfo3ConfigReqCount = 0;	
             g_sihSysInfo3ConfigGetReqProcessed = FALSE;

             /* free the resources */
             free_sysInfo3ConfigTable(); 
             /* Here loopCount is decremented, Due to calling of free function two times in SNMP-GETNEXT
              * on single parameter -- 20/07/11 */
             loopCount--;
             continue;
            }

            /* perform anything here that you need to do before each
               request is processed. */           

            /* the following extracts the my_data_context pointer set in
               the loop functions above.  You can then use the results to
               help return data for the columns of the sysInfo3ConfigTable table 
               in question */    

            table_entry = (struct sysInfo3ConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);

            if ( table_entry == NULL) {
                if (reqinfo->mode == MODE_GET) {
                    netsnmp_set_request_error(reqinfo, request,SNMP_NOSUCHINSTANCE);
                    continue;
                }
                /* XXX: no row existed, if you support creation and this is a
                   set, start dealing with it here, else continue */
            }

            table_info  =     netsnmp_extract_table_info(      request);

            /* table_info->colnum contains the column number requested */
            /* table_info->indexes contains a linked list of snmp variable
               bindings for the indexes of the table.  Values in the list
               have been set corresponding to the indexes of the
               request */
            if (table_info==NULL) {
                continue;
            }             
    
            switch (table_info->colnum) {
            case COLUMN_SYSINFO3PROFILEID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->sysInfo3ProfileId);
                break;
            case COLUMN_QHYST:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->qHyst);
                break;
            case COLUMN_THRESHSERVINGLOW:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->threshServingLow);
                break;
            case COLUMN_CELLRESELECTIONPRIORITY:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->cellReselectionPriority);
                break;
            case COLUMN_SYSINFO3QRXLEVMIN:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->qRxLevMin);
                break;
            case COLUMN_SYSINFO3PMAX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->pMax);
                break;
            case COLUMN_SINTRASEARCH:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->sIntraSearch);
                break;
            case COLUMN_ALLOWMEASBW:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->allowMeasBw);
                break;
            case COLUMN_NEIGHCELLCONFIG:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->neighCellConfig);
                break;
            case COLUMN_TRESELECTIONEUTRA:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->tReselectionEutra);
                break;
            case COLUMN_PRESENCEANTENNAPORT1:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->presenceAntennaPort1);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
	if(g_sysInfo3ConfigFirstCall EQ 1)
         {
            g_sysInfo3ConfigFirstCall = 0;
            g_prevSysInfo3ConfigReqCount = loopCount;
            // This will occur in case of, when SNMP-GET or SNMP-GETNEXT of Single Parameter occurred.
            // In the first call itself loopCount becomes one.
            // In General Case, the loopCount will be always > 1 because every table contains 
            // index column to fetch the row and remaining columns contain table attributes.
            if(loopCount EQ 1)
            {
               //Setting it to false in case of SNMP-GET request for single parameter.
               g_sihSysInfo3ConfigGetReqProcessed = FALSE;
               // Free all resources.
               free_sysInfo3ConfigTable();
            }
         }
         else if(loopCount > 1 || g_prevSysInfo3ConfigReqCount > 1)
         {
            //update g_prevReqCount with current loopCount for next call of Table_handler
            g_prevSysInfo3ConfigReqCount = loopCount;
         }
         else if(loopCount EQ 1)
         {
            //Setting it to false in case of SNMP-GET request for single parameter.
            g_sihSysInfo3ConfigGetReqProcessed = FALSE;
            // Free all resources.
            free_sysInfo3ConfigTable();
         }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
#ifndef PWAV_SIH    
        for (request=requests; request; request=request->next) {
            table_entry = (struct sysInfo3ConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_SYSINFO3PROFILEID:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_QHYST:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_THRESHSERVINGLOW:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_CELLRESELECTIONPRIORITY:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_SYSINFO3QRXLEVMIN:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_SYSINFO3PMAX:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_SINTRASEARCH:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_ALLOWMEASBW:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_NEIGHCELLCONFIG:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_TRESELECTIONEUTRA:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_PRESENCEANTENNAPORT1:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
#endif /* PWAV_SIH */  
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        g_sihSysInfo3ConfigSetReqProcessed = FALSE; 

        clearBytes(&sihTagInfo, sizeof(TagInfo));
        clearBytes(&tlvArray, sizeof(TlvArray));
        
        for (request=requests; request; request=request->next) {
            table_entry = (struct sysInfo3ConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            if(table_entry == NULL){
                logInfo(" %s\n", "table_entry is NULL");
                if (reqinfo->mode == MODE_SET_ACTION) {
                    netsnmp_set_request_error(reqinfo, request,SNMP_NOSUCHINSTANCE);
                    continue;
                }
                /* XXX: no row existed, if you support creation and this is a
                   set, start dealing with it here, else continue */
            }

            if(table_info == NULL){
                logInfo(" %s\n", "table_info is NULL");
                continue;
            }

            colId = table_info->colnum;
            /* set the row index */
            rowIndex = requests->index;
    
            switch (table_info->colnum) {
            case COLUMN_SYSINFO3PROFILEID:
                table_entry->sysInfo3ProfileId     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, SYSINFO3CONFIG, rowIndex, COLUMN_SYSINFO3PROFILEID);
                tlvArray.numTlvs++;
                break;
            case COLUMN_QHYST:
                table_entry->qHyst     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, SYSINFO3CONFIG, rowIndex, COLUMN_QHYST);
                tlvArray.numTlvs++;
                break;
            case COLUMN_THRESHSERVINGLOW:
                table_entry->threshServingLow     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, SYSINFO3CONFIG, rowIndex, COLUMN_THRESHSERVINGLOW);
                tlvArray.numTlvs++;
                break;
            case COLUMN_CELLRESELECTIONPRIORITY:
                table_entry->cellReselectionPriority     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, SYSINFO3CONFIG, rowIndex, COLUMN_CELLRESELECTIONPRIORITY);
                tlvArray.numTlvs++;
                break;
            case COLUMN_SYSINFO3QRXLEVMIN:
                table_entry->qRxLevMin     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, SYSINFO3CONFIG, rowIndex, COLUMN_SYSINFO3QRXLEVMIN);
                tlvArray.numTlvs++;
                break;
            case COLUMN_SYSINFO3PMAX:
                table_entry->pMax     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, SYSINFO3CONFIG, rowIndex, COLUMN_SYSINFO3PMAX);
                tlvArray.numTlvs++;
                break;
            case COLUMN_SINTRASEARCH:
                table_entry->sIntraSearch     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, SYSINFO3CONFIG, rowIndex, COLUMN_SINTRASEARCH);
                tlvArray.numTlvs++;
                break;
            case COLUMN_ALLOWMEASBW:
                table_entry->allowMeasBw     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, SYSINFO3CONFIG, rowIndex, COLUMN_ALLOWMEASBW);
                tlvArray.numTlvs++;
                break;
            case COLUMN_NEIGHCELLCONFIG:
                table_entry->neighCellConfig     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, SYSINFO3CONFIG, rowIndex, COLUMN_NEIGHCELLCONFIG);
                tlvArray.numTlvs++;
                break;
            case COLUMN_TRESELECTIONEUTRA:
                table_entry->tReselectionEutra     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, SYSINFO3CONFIG, rowIndex, COLUMN_TRESELECTIONEUTRA);
                tlvArray.numTlvs++;
                break;
            case COLUMN_PRESENCEANTENNAPORT1:
                table_entry->presenceAntennaPort1     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, SYSINFO3CONFIG, rowIndex, COLUMN_PRESENCEANTENNAPORT1);
                tlvArray.numTlvs++;
                break;
            }
        }

        if ((request == NULL) && (g_sihSysInfo3ConfigSetReqProcessed EQ FALSE))
            /* Processed all requests and table entry is filled with
             * requested data. */
            {
            /* Set SIH Set Request Tag Info */
            sihTagInfo.tableId = SYSINFO3CONFIG;

            sihTagInfo.rowId = rowIndex;

            status = sendSysInfo3ConfigSnmpSetRequest (sihTagInfo, &tlvArray);
            if (status EQ TRUE)
                {
                logInfo("%s","SET Succedded");
                }
            else
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_GENERR );
            }
        break;

    case MODE_SET_UNDO:
#ifndef PWAV_SIH 
        for (request=requests; request; request=request->next) {
            table_entry = (struct sysInfo3ConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_SYSINFO3PROFILEID:
                table_entry->sysInfo3ProfileId     = table_entry->old_sysInfo3ProfileId;
                table_entry->old_sysInfo3ProfileId = 0;
                break;
            case COLUMN_QHYST:
                table_entry->qHyst     = table_entry->old_qHyst;
                table_entry->old_qHyst = 0;
                break;
            case COLUMN_THRESHSERVINGLOW:
                table_entry->threshServingLow     = table_entry->old_threshServingLow;
                table_entry->old_threshServingLow = 0;
                break;
            case COLUMN_CELLRESELECTIONPRIORITY:
                table_entry->cellReselectionPriority     = table_entry->old_cellReselectionPriority;
                table_entry->old_cellReselectionPriority = 0;
                break;
            case COLUMN_SYSINFO3QRXLEVMIN:
                table_entry->qRxLevMin     = table_entry->old_qRxLevMin;
                table_entry->old_qRxLevMin = 0;
                break;
            case COLUMN_SYSINFO3PMAX:
                table_entry->pMax     = table_entry->old_pMax;
                table_entry->old_pMax = 0;
                break;
            case COLUMN_SINTRASEARCH:
                table_entry->sIntraSearch     = table_entry->old_sIntraSearch;
                table_entry->old_sIntraSearch = 0;
                break;
            case COLUMN_ALLOWMEASBW:
                table_entry->allowMeasBw     = table_entry->old_allowMeasBw;
                table_entry->old_allowMeasBw = 0;
                break;
            case COLUMN_NEIGHCELLCONFIG:
                table_entry->neighCellConfig     = table_entry->old_neighCellConfig;
                table_entry->old_neighCellConfig = 0;
                break;
            case COLUMN_TRESELECTIONEUTRA:
                table_entry->tReselectionEutra     = table_entry->old_tReselectionEutra;
                table_entry->old_tReselectionEutra = 0;
                break;
            case COLUMN_PRESENCEANTENNAPORT1:
                table_entry->presenceAntennaPort1     = table_entry->old_presenceAntennaPort1;
                table_entry->old_presenceAntennaPort1 = 0;
                break;
            }
        }
#endif /* PWAV_SIH */
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
