/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17695 2009-07-21 12:22:18Z dts12 $
 */
#ifndef SYSINFO1CONFIG_H
#define SYSINFO1CONFIG_H

/* function declarations */
void init_sysInfo1Config(void);
void initialize_table_sysInfo1ConfigTable(void);

/* column number definitions for table sysInfo1ConfigTable */
       #define COLUMN_SYSINFO1PROFILEID		1
       #define COLUMN_INTRAFREQRESELECTION		2
       #define COLUMN_QRXLEVMIN		3
       #define COLUMN_QRXLEVMINOFFSET		4
       #define COLUMN_SIB2PERIODICITY		5
       #define COLUMN_SIB3PERIODICITY		6
       #define COLUMN_SIB4PERIODICITY		7
       #define COLUMN_SIWINDOWLENGTH		8

#define SYS_INFO1_CONFIG_MAX_COL           COLUMN_SIWINDOWLENGTH

    /* Typical data structure for a row entry */
typedef struct sysInfo1ConfigTable_entry {
    /* Column values */
    unsigned char sysInfo1ProfileId; /* Index values */
    unsigned int intraFreqReselection;
    char qRxLevMin;
    unsigned char qRxLevMinOffset;
    unsigned int sib2Periodicity;
    unsigned int sib3Periodicity;
    unsigned int sib4Periodicity;
    unsigned int siWindowLength;

    /* Illustrate using a simple linked list */
    int   valid;
    struct sysInfo1ConfigTable_entry *next;
} sysInfo1ConfigTableEntry ;


#endif /* SYSINFO1CONFIG_H */
