/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef TRACESTATUS_H
#define TRACESTATUS_H

/* function declarations */
void init_traceStatus(void);
void initialize_table_traceStatusTable(void);

/* column number definitions for table traceStatusTable */
       #define COLUMN_TRACE_STATUS_INDEX 1
       #define COLUMN_TRACEID 2
       #define COLUMN_TRACESTATE 3
       #define COLUMN_TRACEDURATIONCONFIGUREDINMINS 4
       #define COLUMN_TRACEDURATIONELAPSEDINMINS 5
       #define COLUMN_TRACEMESSAGECOUNTER 6
       #define COLUMN_TRACEDESTINATION 7

#define TRACE_STATUS_MAX_COL COLUMN_TRACEDESTINATION

    /* Typical data structure for a row entry */
struct traceStatusTable_entry {
    /* Index values */
    unsigned int index;

    /* Column values */
    unsigned int traceId;
    unsigned int traceState;
    unsigned int traceDurationConfiguredInMins;
    unsigned int traceDurationElapsedInMins;
    unsigned int traceMessageCounter;
    unsigned int traceDestination;

    /* Illustrate using a simple linked list */
    int   valid;
    struct traceStatusTable_entry *next;
};

#endif /* TRACESTATUS_H */
