/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "bs_modules.h"
#include "all_cfg.h"
#include "all_cmn.h"
#include "tlv_enc_dec.h"

#include "sih.h"
#include "syslog.h"
#include "rrcCellCounters.h"

/* function declarations */
Netsnmp_Node_Handler rrcCellCountersTable_handler;
Netsnmp_First_Data_Point  rrcCellCountersTable_get_first_data_point;
Netsnmp_Next_Data_Point   rrcCellCountersTable_get_next_data_point;

/* globals */
struct rrcCellCountersTable_entry  *rrcCellCountersTable_head = NULL;
static TBOOL g_sihRrcCellCountersGetReqProcessed = FALSE;
static UINT32 g_prevRrcCellCountersReqCount = 0;
static UINT32 g_rrcCellCountersFirstCall = 0;

/* free_rrcCellCountersTable */
/**
* @details 
*          This is the routine which frees the rrcCellCounters entry.
*/
void free_rrcCellCountersTable(void)
{
  rrcCellCountersTableEntry  * current = rrcCellCountersTable_head;

  if (current) 
  {
  for (current = rrcCellCountersTable_head->next ; current != NULL; current = current->next) {
    SNMP_FREE( current );  
    }
  }
   
  SNMP_FREE(rrcCellCountersTable_head);
  rrcCellCountersTable_head = NULL;

  return;
}


/**
* @details 
*          This is the routine which handles get response from SIH Get Processor
*          and prepare the SNMP GET response for EMS.
* @param tlvArray contains pointer to TLV array.
*/
TBOOL sendRrcCellCountersSnmpGetResponse (
  IO TlvArray    *tlvArray
  )
{
  int  totalNumRow, totalNumCol, i=0, colmn=0;
  rrcCellCountersTableEntry * prevPtr = NULL;

  printTLV(tlvArray);

  /* Total no. of Colmns */
  totalNumCol = RRC_CELL_COUNTERS_MAX_COL;
  /* Total no. of Row = (No. of TLV)/(No. of Columns) */
  totalNumRow = tlvArray->numTlvs/totalNumCol;

  logInfo("Total No. of Row %d & Col %d", totalNumRow, totalNumCol);
  for (i=1;  i <= totalNumRow;  i++)
      {
      rrcCellCountersTableEntry *ptr=(rrcCellCountersTableEntry *)malloc(sizeof(rrcCellCountersTableEntry));

      clearBytes (ptr, sizeof(rrcCellCountersTableEntry));

      /* Fill Data in TLV */
      for(colmn = 1 ; colmn <= totalNumCol ; colmn++)
        {
        if (colmn EQ COLUMN_RRC_CELL_COUNTERS_INDEX)
           {
            ptr->index =  getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_RRC_CELL_COUNTERS_CELLID)
           {
            ptr->cellId =  getUint16FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_PAG)
           {
            ptr->pag =  getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_CONNSETUP)
           {
            ptr->connSetup =  getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_CONNREJECT)
           {
            ptr->connReject =  getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_CONNREQ)
           {
            ptr->connReq = getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_CONNREESTABREQ)
           {
            ptr->connReestabReq = getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_CONNREESTAB)
           {
            ptr->connReestab = getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_CONNREESTABREJ)
           {
            ptr->connReestabRej = getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_NUMUES)
           {
            ptr->numUEs = getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_HOTOEUTRASUCC)
           {
            ptr->hoToEUTRASucc = getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_HOFROMEUTRAFAIL)
           {
            ptr->hoFromEUTRAFail = getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
	if (colmn EQ COLUMN_RRC_CELL_COUNTERS_LASTCOLLECTEDAT)
           {
            clearBytes (ptr->lastCollectedAt, RRC_CELL_COUNTERS_LCOLLECT_BUF_LEN_MAX);
            copyBytes (tlvArray->tlvInfo[colmn-1].data, tlvArray->tlvInfo[colmn-1].len, ptr->lastCollectedAt);
            ptr->lastCollectedAt_len = strlen(ptr->lastCollectedAt);
            continue;
           }
        }

       ptr->next = NULL;

      if (prevPtr == NULL) {
           rrcCellCountersTable_head =  prevPtr = ptr;
       }

      prevPtr->next = ptr;
      prevPtr = ptr;
     }
    prevPtr->next = NULL;

    if (rrcCellCountersTable_head)
        return TRUE;
    else
        return FALSE;
}

/** Initializes the rrcCellCounters module */
void
init_rrcCellCounters(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_rrcCellCountersTable();
}

 /*  Determine the first/last column names */

/** Initialize the rrcCellCountersTable table by defining its contents and how it's structured */
void
initialize_table_rrcCellCountersTable(void)
{
    const oid rrcCellCountersTable_oid[] = {1,3,6,1,4,1,9344,501,RRCCELLCOUNTERS,1};
    const size_t rrcCellCountersTable_oid_len   = OID_LENGTH(rrcCellCountersTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("rrcCellCounters:init", "initializing table rrcCellCountersTable\n"));

    reg = netsnmp_create_handler_registration(
              "rrcCellCountersTable",     rrcCellCountersTable_handler,
              rrcCellCountersTable_oid, rrcCellCountersTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_UNSIGNED,  /* index: index */
                           0);
    table_info->min_column = COLUMN_RRC_CELL_COUNTERS_INDEX;
    table_info->max_column = COLUMN_RRC_CELL_COUNTERS_LASTCOLLECTEDAT;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = rrcCellCountersTable_get_first_data_point;
    iinfo->get_next_data_point  = rrcCellCountersTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}


#ifndef PWAV_SIH
/* create a new row in the (unsorted) table */
struct rrcCellCountersTable_entry *
rrcCellCountersTable_createEntry(
                 u_long  index,
                ) {
    struct rrcCellCountersTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct rrcCellCountersTable_entry);
    if (!entry)
        return NULL;

    entry->index = index;
    entry->next = rrcCellCountersTable_head;
    rrcCellCountersTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
rrcCellCountersTable_removeEntry( struct rrcCellCountersTable_entry *entry ) {
    struct rrcCellCountersTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = rrcCellCountersTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        rrcCellCountersTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}
#endif /* PWAV_SIH */


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
rrcCellCountersTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    TagInfo sihTagInfo;
    TBOOL status = FALSE;


    if (g_sihRrcCellCountersGetReqProcessed EQ FALSE)
        {
        /* Set SIH Get Request Tag Info */
        sihTagInfo.tableId = RRCCELLCOUNTERS;
        sihTagInfo.rowId = CONFIG_ROW_ID_NONE;
        sihTagInfo.colId = CONFIG_COL_ID_NONE;

        status = sihGetProcessor (sihTagInfo);
        if ( status EQ TRUE )
            {
            logInfo("%s","Get Processor Succedded");
            if (rrcCellCountersTable_head)
                {
		g_rrcCellCountersFirstCall = 1;
                g_sihRrcCellCountersGetReqProcessed = TRUE;
                }
            }
        else
            logError("%s","Get Processor Failed");
        }

    *my_loop_context = rrcCellCountersTable_head;
    return rrcCellCountersTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
rrcCellCountersTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct rrcCellCountersTable_entry *entry = (struct rrcCellCountersTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_UNSIGNED, entry->index );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the rrcCellCountersTable table */
int
rrcCellCountersTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request = NULL;
    netsnmp_table_request_info *table_info = NULL;
    struct rrcCellCountersTable_entry          *table_entry = NULL;
    int loopCount = 0;

    DEBUGMSGTL(("rrcCellCounters:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {

            loopCount++;
            if (request->processed != 0) /*Processed all requests, rows and colmns */
                {
		g_prevRrcCellCountersReqCount = 0;
                g_sihRrcCellCountersGetReqProcessed = FALSE;
                /* free the resources */
                free_rrcCellCountersTable();
                /* Here loopCount is decremented, Due to calling of free function two times in SNMP-GETNEXT
                 * on single parameter -- 20/07/11 */
                loopCount--;
                continue;
                }

            /* perform anything here that you need to do before each
               request is processed. */

            /* the following extracts the my_data_context pointer set in
               the loop functions above.  You can then use the results to
               help return data for the columns of the rrcCellCountersTable table
               in question */

            table_entry = (struct rrcCellCountersTable_entry *)
                              netsnmp_extract_iterator_context(request);

            if ( table_entry == NULL) {
                if (reqinfo->mode == MODE_GET) {
                    netsnmp_set_request_error(reqinfo, request,SNMP_NOSUCHINSTANCE);
                    continue;
                }
                /* XXX: no row existed, if you support creation and this is a
                   set, start dealing with it here, else continue */
            }

            table_info  =     netsnmp_extract_table_info(      request);

            /* table_info->colnum contains the column number requested */
            /* table_info->indexes contains a linked list of snmp variable
               bindings for the indexes of the table.  Values in the list
               have been set corresponding to the indexes of the
               request */
            if (table_info==NULL) {
                continue;
            }
        
            switch (table_info->colnum) {
            case COLUMN_RRC_CELL_COUNTERS_INDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->index);
                break;
            case COLUMN_RRC_CELL_COUNTERS_CELLID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->cellId);
                break;
            case COLUMN_PAG:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->pag);
                break;
            case COLUMN_CONNSETUP:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->connSetup);
                break;
            case COLUMN_CONNREJECT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->connReject);
                break;
            case COLUMN_CONNREQ:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->connReq);
                break;
            case COLUMN_CONNREESTABREQ:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->connReestabReq);
                break;
            case COLUMN_CONNREESTAB:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->connReestab);
                break;
            case COLUMN_CONNREESTABREJ:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->connReestabRej);
                break;
            case COLUMN_NUMUES:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->numUEs);
                break;
            case COLUMN_HOTOEUTRASUCC:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->hoToEUTRASucc);
                break;
            case COLUMN_HOFROMEUTRAFAIL:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER,
                                            table_entry->hoFromEUTRAFail);
                break;
	    case COLUMN_RRC_CELL_COUNTERS_LASTCOLLECTEDAT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->lastCollectedAt,
                                          table_entry->lastCollectedAt_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
	if(g_rrcCellCountersFirstCall EQ 1)
         {
            g_rrcCellCountersFirstCall = 0;
            g_prevRrcCellCountersReqCount = loopCount;
            // This will occur in case of, when SNMP-GET or SNMP-GETNEXT of Single Parameter occurred.
            // In the first call itself loopCount becomes one.
            // In General Case, the loopCount will be always > 1 because every table contains 
            // index column to fetch the row and remaining columns contain table attributes.
            if(loopCount EQ 1)
            {
               //Setting it to false in case of SNMP-GET request for single parameter.
               g_sihRrcCellCountersGetReqProcessed = FALSE;
               // Free all resources.
               free_rrcCellCountersTable();
            }
         }
         else if(loopCount > 1 || g_prevRrcCellCountersReqCount > 1)
         {
            //update g_prevReqCount with current loopCount for next call of Table_handler
            g_prevRrcCellCountersReqCount = loopCount;
         }
         else if(loopCount EQ 1)
         {
            //Setting it to false in case of SNMP-GET request for single parameter.
            g_sihRrcCellCountersGetReqProcessed = FALSE;
            // Free all resources.
            free_rrcCellCountersTable();
         }
        break;

    }
    return SNMP_ERR_NOERROR;
}
