/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef LOGINSTATUS_H
#define LOGINSTATUS_H

/* function declarations */
void init_loginStatus(void);
void initialize_table_loginStatusTable(void);

/* column number definitions for table loginStatusTable */
       #define COLUMN_LOGIN_STATUS_INDEX		1
       #define COLUMN_WHO		2
       #define COLUMN_PRIVILEDGELEVEL		3
       #define COLUMN_OAMINTERFACETYPE		4
       #define COLUMN_OAMINTERFACESESSIONNUMBER		5
       #define COLUMN_LOGGEDINAT		6

#define LOGIN_STATUS_MAX_COL  COLUMN_LOGGEDINAT
#define LOGIN_STATUS_WHO_MAX_LEN_BUF       17
#define LOGIN_STATUS_TIME_MAX_LEN_BUF      17

    /* Typical data structure for a row entry */
typedef struct loginStatusTable_entry {
    /* Index values */
    unsigned int index;

    /* Column values */
    char who[LOGIN_STATUS_WHO_MAX_LEN_BUF];
    size_t who_len;
    unsigned int priviledgeLevel;
    unsigned int oamInterfaceType;
    unsigned int oamInterfaceSessionNumber;
    char loggedInAt[LOGIN_STATUS_TIME_MAX_LEN_BUF];
    size_t loggedInAt_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct loginStatusTable_entry *next;
}loginStatusTableEntry;

#endif /* LOGINSTATUS_H */
