/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef TRACECONFIG_H
#define TRACECONFIG_H

/* function declarations */
void init_traceConfig(void);
void initialize_table_traceConfigTable(void);

/* column number definitions for table traceConfigTable */
       #define COLUMN_TRACEPROFILEID	1
       #define COLUMN_TRACERRC		2
       #define COLUMN_TRACES1AP		3
       #define COLUMN_TRACEX2AP		4
       #define COLUMN_TRACERESERVED1    5
       #define COLUMN_TRACERESERVED2    6
       #define COLUMN_TRACERESERVED3    7
       #define COLUMN_TRACEDEST  8
       #define COLUMN_TRACEDESTUDPPORT  9
       #define COLUMN_TRACEDESTIPADDRESS 10


#define TRACE_CONFIG_MAX_COL	COLUMN_TRACEDESTIPADDRESS

#define MAX_SIZE_TRACEDESTIPADDRESS 16

    /* Typical data structure for a row entry */
typedef struct traceConfigTable_entry {
    /* Index values */
    unsigned int traceProfileId;

    /* Column values */
    unsigned char traceRRC;
    unsigned char traceS1AP;
    unsigned char traceX2AP;
    unsigned char traceReserved1;
    unsigned char traceReserved2;
    unsigned char traceReserved3;
    unsigned int traceDestination;
    unsigned short traceDestUdpPort;
    char traceDestIpAddress[MAX_SIZE_TRACEDESTIPADDRESS];
    size_t traceDestIpAddress_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct traceConfigTable_entry *next;
}traceConfigTableEntry;

#endif /* TRACECONFIG_H */
