#define OBJECTNUMBER_LTEPHYDESC                         1
#define OBJECTNUMBER_BS                                 2
#define OBJECTNUMBER_BS_TX                              3
#define OBJECTNUMBER_BS_RX                              4
#define OBJECTNUMBER_BS_RX_PRACH                        5
#define OBJECTNUMBER_BS_RX_PRACHDet                     6
#define OBJECTNUMBER_BS_DL_INIT_MEMBUF                  7
#define OBJECTNUMBER_BS_DL_INIT_PARAM                   8
#define OBJECTNUMBER_DLTXFECPARAMS                      9
#define OBJECTNUMBER_PBCH_INIT_MEM_BUFFER               10
#define OBJECTNUMBER_DLCELLSPECIFICSCRSEQ               11
#define OBJECTNUMBER_CRC24ABUF                          12
#define OBJECTNUMBER_SCRBUF0                            13
#define OBJECTNUMBER_SCRBUF1                            14
#define OBJECTNUMBER_PCFICH_INIT_MEM_BUFFER             15
#define OBJECTNUMBER_PCFICH_INIT_RE_BUFFER              16
#define OBJECTNUMBER_PHICH_INIT_MEM_BUFFER              17
#define OBJECTNUMBER_PHICH_INIT_RE_BUFFER               18
#define OBJECTNUMBER_PDCCH_INIT_PERMUTE_TABLE_BUFFER    19
#define OBJECTNUMBER_PDCCH_INIT_RE_BUFFER               20
#define OBJECTNUMBER_PDCCH_INIT_NUM_QUADRUPLETS_BUFFER  21
#define OBJECTNUMBER_DL_CRS_INIT_SYM_BUFFER             22
#define OBJECTNUMBER_TXSYS                              23
#define OBJECTNUMBER_A                                  24
#define OBJECTNUMBER_SYNC2_D0                           25
#define OBJECTNUMBER_SYNC2_D1                           26
#define OBJECTNUMBER_SCR_INDEX_0                        27
#define OBJECTNUMBER_SCR_INDEX_1                        28
#define OBJECTNUMBER_SCR_OUT_0                          29
#define OBJECTNUMBER_SCR_OUT_1                          30
#define OBJECTNUMBER_IOPARAMS_DLCONTROL                 31
#define OBJECTNUMBER_DLTXINPUTPARAMS                    32
#define OBJECTNUMBER_INPUTPDCCH                         33
#define OBJECTNUMBER_PDCCHRNTI                          34
#define OBJECTNUMBER_STARTPBCH                          35
#define OBJECTNUMBER_STARTPDCCH                         36
#define OBJECTNUMBER_GENBUF                             37
#define OBJECTNUMBER_BS_RX_POINTERS                     38
#define OBJECTNUMBER_LTE_PHY_UL_SDU_DESC                39
#define OBJECTNUMBER_RS_GRID                            40
#define OBJECTNUMBER_DEPENDENCYARRAY                    41
#define OBJECTNUMBER_DEPENDENCYARRAY1                   42
#define OBJECTNUMBER_DEPENDENCYARRAY2                   43
#define OBJECTNUMBER_DEPENDENCYARRAY3                   44
#define OBJECTNUMBER_DEPENDENCYARRAY4                   45
#define OBJECTNUMBER_EXPO_MAT                           46
#define OBJECTNUMBER_EXPO_CH_PUSCH                      47
#define OBJECTNUMBER_EXPO_CH_PUCCH                      48
#define OBJECTNUMBER_EXPO_NORM_REEST                    49
#define OBJECTNUMBER_CHEST_UL                           50
#define OBJECTNUMBER_ERRAVGOUT                          51
#define OBJECTNUMBER_ERREXPO                            52
#define OBJECTNUMBER_MPERRTEMP                          53
#define OBJECTNUMBER_MPERREXPOTEMP                      54
#define OBJECTNUMBER_SNRPERRB_PILOTS                    55
#define OBJECTNUMBER_SNRPERRB                           56
#define OBJECTNUMBER_NOISEVAR                           57
#define OBJECTNUMBER_PUCCHCHAN                          58
#define OBJECTNUMBER_REDET0                             59
#define OBJECTNUMBER_MUXCTRL_SOFTDEC                    60
#define OBJECTNUMBER_ULRXINPUTPARAMS                    61
#define OBJECTNUMBER_ULRXSDUPARAMS                      62
#define OBJECTNUMBER_ISYM_EFF                           63
#define OBJECTNUMBER_BS_APILOTS                         64
#define OBJECTNUMBER_BS_PUSCH                           65
#define OBJECTNUMBER_ADET                               66
#define OBJECTNUMBER_DEROTATION                         67
#define OBJECTNUMBER_BS_APILOTS_PUCCH                   68
#define OBJECTNUMBER_R_ALPHA_UV                         69
#define OBJECTNUMBER_ERRAVG                             70
#define OBJECTNUMBER_RXINPWRAVG_PERRBPILOT              71
#define OBJECTNUMBER_PWRAVG_PILOT_EXPO                  72
#define OBJECTNUMBER_RXINPWRAVG_PERRBDATASYM            73
#define OBJECTNUMBER_PWRAVG_DATA_EXPO                   74
#define OBJECTNUMBER_SNRPILOT                           75
#define OBJECTNUMBER_NOC                                76
#define OBJECTNUMBER_SDESCRAMB                          77
#define OBJECTNUMBER_PAVGREDET_PUCCHACK                 78
#define OBJECTNUMBER_PAVGREDET_PUCCHCQI                 79
#define OBJECTNUMBER_CHEST_PUCCH                        80
#define OBJECTNUMBER_ALLPUCCHPWRAVG_ANTSLOT             81
#define OBJECTNUMBER_PUCCHPWRAVG                        82
#define OBJECTNUMBER_SRSCHEST                           83
#define OBJECTNUMBER_RAWSRSCHEST                        84
#define OBJECTNUMBER_SRSPILOTS                          85
#define OBJECTNUMBER_LENGTHSRSPILOTS                    86
#define OBJECTNUMBER_NCSSRS                             87
#define OBJECTNUMBER_SRSSNRPERRB                        88
#define OBJECTNUMBER_SRSAVGSNRPERRBDB                   89
#define OBJECTNUMBER_SRSCHMEAS                          90
#define OBJECTNUMBER_BS_RX_CHAN_SRS                     91
#define OBJECTNUMBER_ULRXFECPARAMS                      92
#define OBJECTNUMBER_BS_PRACH                           93
#define OBJECTNUMBER_BS_SRS                             94
#define OBJECTNUMBER_SRSBANDWIDTHCONFIGTABLE            95
#define OBJECTNUMBER_DESCRINDEX                         96
#define OBJECTNUMBER_DEMAPOUTSIZE                       97
#define OBJECTNUMBER_DESCRINBUFS                        98
#define OBJECTNUMBER_CHEST_UL_PUCCH                     99
#define OBJECTNUMBER_ERRSUB_PUCCH                       100
#define OBJECTNUMBER_ERRSUBEXPO_PUCCH                   101
#define OBJECTNUMBER_MAP_SETUP_DESCRIPTOR               102
#define OBJECTNUMBER_CEVA_IDFT_TABLES                   103





//information for coredump parsing
#define OBJECTTYPE_PBCH_INIT_MEM_BUFFER                 U8
#define OBJECTTYPE_DLCELLSPECIFICSCRSEQ                 U8
#define OBJECTTYPE_CRC24ABUF                            U8
#define OBJECTTYPE_SCRBUF0                              U8
#define OBJECTTYPE_SCRBUF1                              U8
#define OBJECTTYPE_PCFICH_INIT_MEM_BUFFER               U8
#define OBJECTTYPE_PCFICH_INIT_RE_BUFFER                U8
#define OBJECTTYPE_PHICH_INIT_MEM_BUFFER                U8
#define OBJECTTYPE_PHICH_INIT_RE_BUFFER                 U8
#define OBJECTTYPE_PDCCH_INIT_PERMUTE_TABLE_BUFFER      U8
#define OBJECTTYPE_PDCCH_INIT_RE_BUFFER                 U8
#define OBJECTTYPE_PDCCH_INIT_NUM_QUADRUPLETS_BUFFER    U8
#define OBJECTTYPE_DL_CRS_INIT_SYM_BUFFER               U8
#define OBJECTTYPE_TXSYS                                U8
#define OBJECTTYPE_A                                    U8
#define OBJECTTYPE_SYNC2_D0                             U8
#define OBJECTTYPE_SYNC2_D1                             U8
#define OBJECTTYPE_SCR_INDEX_0                          U8
#define OBJECTTYPE_SCR_INDEX_1                          U8
#define OBJECTTYPE_SCR_OUT_0                            U8
#define OBJECTTYPE_SCR_OUT_1                            U8
#define OBJECTTYPE_IOPARAMS_DLCONTROL                   U8
#define OBJECTTYPE_INPUTPDCCH                           U8
#define OBJECTTYPE_PDCCHRNTI                            U8
#define OBJECTTYPE_STARTPBCH                            U8
#define OBJECTTYPE_STARTPDCCH                           U8
#define OBJECTTYPE_GENBUF                               U8
#define OBJECTTYPE_RS_GRID                              U8
#define OBJECTTYPE_DEPENDENCYARRAY                      U8
#define OBJECTTYPE_DEPENDENCYARRAY1                     U8
#define OBJECTTYPE_DEPENDENCYARRAY2                     U8
#define OBJECTTYPE_DEPENDENCYARRAY3                     U8
#define OBJECTTYPE_DEPENDENCYARRAY4                     U8
#define OBJECTTYPE_EXPO_MAT                             U8
#define OBJECTTYPE_EXPO_CH_PUSCH                        U8
#define OBJECTTYPE_EXPO_CH_PUCCH                        U8
#define OBJECTTYPE_EXPO_NORM_REEST                      U8
#define OBJECTTYPE_CHEST_UL                             U8
#define OBJECTTYPE_ERRAVGOUT                            U8
#define OBJECTTYPE_ERREXPO                              U8
#define OBJECTTYPE_MPERRTEMP                            U8
#define OBJECTTYPE_MPERREXPOTEMP                        U8
#define OBJECTTYPE_SNRPERRB_PILOTS                      U8
#define OBJECTTYPE_SNRPERRB                             U8
#define OBJECTTYPE_NOISEVAR                             U8
#define OBJECTTYPE_PUCCHCHAN                            U8
#define OBJECTTYPE_REDET0                               U8
#define OBJECTTYPE_MUXCTRL_SOFTDEC                      U8
#define OBJECTTYPE_ISYM_EFF                             U8
#define OBJECTTYPE_BS_APILOTS                           U8
#define OBJECTTYPE_ADET                                 U8
#define OBJECTTYPE_DEROTATION                           U8
#define OBJECTTYPE_BS_APILOTS_PUCCH                     U8
#define OBJECTTYPE_R_ALPHA_UV                           U8
#define OBJECTTYPE_ERRAVG                               U8
#define OBJECTTYPE_RXINPWRAVG_PERRBPILOT                U8
#define OBJECTTYPE_PWRAVG_PILOT_EXPO                    U8
#define OBJECTTYPE_RXINPWRAVG_PERRBDATASYM              U8
#define OBJECTTYPE_PWRAVG_DATA_EXPO                     U8
#define OBJECTTYPE_SNRPILOT                             U8
#define OBJECTTYPE_NOC                                  U8
#define OBJECTTYPE_SDESCRAMB                            U8
#define OBJECTTYPE_PAVGREDET_PUCCHACK                   U8
#define OBJECTTYPE_PAVGREDET_PUCCHCQI                   U8
#define OBJECTTYPE_CHEST_PUCCH                          U8
#define OBJECTTYPE_ALLPUCCHPWRAVG_ANTSLOT               U8
#define OBJECTTYPE_PUCCHPWRAVG                          U8
#define OBJECTTYPE_SRSCHEST                             U8
#define OBJECTTYPE_RAWSRSCHEST                          U8
#define OBJECTTYPE_SRSPILOTS                            U8
#define OBJECTTYPE_LENGTHSRSPILOTS                      U8
#define OBJECTTYPE_NCSSRS                               U8
#define OBJECTTYPE_SRSSNRPERRB                          U8
#define OBJECTTYPE_SRSAVGSNRPERRBDB                     U8
#define OBJECTTYPE_SRSCHMEAS                            U8
#define OBJECTTYPE_SRSBANDWIDTHCONFIGTABLE              U8
#define OBJECTTYPE_DESCRINDEX                           U8
#define OBJECTTYPE_DEMAPOUTSIZE                         U8
#define OBJECTTYPE_DESCRINBUFS                          U8
#define OBJECTTYPE_CHEST_UL_PUCCH                       U8
#define OBJECTTYPE_ERRSUB_PUCCH                         U8
#define OBJECTTYPE_ERRSUBEXPO_PUCCH                     U8
#define OBJECTTYPE_MAP_SETUP_DESCRIPTOR                 U8
#define OBJECTTYPE_CEVA_IDFT_TABLES                     U8


