/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "bs_modules.h"
#include "all_cfg.h"
#include "all_cmn.h"
#include "tlv_enc_dec.h"

#include "sih.h"
#include "syslog.h"
#include "swInstall.h"

/* function declarations */
Netsnmp_Node_Handler swInstallTable_handler;
Netsnmp_First_Data_Point  swInstallTable_get_first_data_point;
Netsnmp_Next_Data_Point   swInstallTable_get_next_data_point;

/* globals */
struct swInstallTable_entry  *swInstallTable_head = NULL;
static TBOOL g_sihSwInstallSetReqProcessed = FALSE;
static TBOOL g_sihSwInstallGetReqProcessed = FALSE;
static UINT32 g_prevSwInstallReqCount = 0;
static UINT32 g_swInstallFirstCall = 0;

/* free_swInstallTable */
/**
* @details 
*          This is the routine which frees the sw install entry.
*/
void free_swInstallTable(void)
{
  swInstallTableEntry  * current = swInstallTable_head;

  if (current)
  {
  for (current = swInstallTable_head->next ; current != NULL; current = current->next) {
    SNMP_FREE( current );
    }

  SNMP_FREE(swInstallTable_head);
  swInstallTable_head = NULL;
  }
  return;
}


/**
* @details 
*          This is the routine which handles get response from SIH Get Processor
*          and prepare the SNMP GET response for EMS.
* @param tlvArray contains pointer to TLV array.
*/
TBOOL sendSwInstallSnmpGetResponse (
  IO TlvArray    *tlvArray
  )
{
  int  totalNumRow, totalNumCol, i=0, colmn=0;
  swInstallTableEntry * prevPtr = NULL;

  printTLV(tlvArray);

  logInfo("%s","sendSwInstallSnmpGetResponse");
  /* Total no. of Colmns */
  totalNumCol = SW_INSTALL_MAX_COL;
  /* Total no. of Row = (No. of TLV)/(No. of Columns) */
  totalNumRow = tlvArray->numTlvs/totalNumCol;

  logInfo("Total No. of Row %d & Col %d", totalNumRow, totalNumCol);
  for (i=1;  i <= totalNumRow;  i++)
      {
      swInstallTableEntry *ptr=(swInstallTableEntry *)malloc(sizeof(swInstallTableEntry));

      clearBytes (ptr, sizeof(swInstallTableEntry));

      /* Fill Data in TLV */
      for(colmn = 1 ; colmn <= totalNumCol ; colmn++)
        {
        if (colmn EQ COLUMN_SWINSTALLINDEX)
           {
            ptr->index =  getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_INSTALLATIONTYPE)
           {
            ptr->installationType =  getUint32FromArray(tlvArray->tlvInfo[colmn-1].data);
            continue;
           }
        if (colmn EQ COLUMN_SWINSTALLFILENAME)
           {
            clearBytes (ptr->fileName, SWINSTALLFILENAME_BUF_LEN);
            if (tlvArray->tlvInfo[colmn-1].len > 0)
            {
                copyBytes (tlvArray->tlvInfo[colmn-1].data, tlvArray->tlvInfo[colmn-1].len, ptr->fileName);
            }
            ptr->fileName_len = strlen(ptr->fileName);
            continue;
           }
        if (colmn EQ COLUMN_INSTALLER)
           {
            clearBytes (ptr->installer, SWINSTALLFILENAME_BUF_LEN);
            if (tlvArray->tlvInfo[colmn-1].len > 0)
            {
                copyBytes (tlvArray->tlvInfo[colmn-1].data, tlvArray->tlvInfo[colmn-1].len, ptr->installer);
            }
            ptr->installer_len = strlen(ptr->installer);
            continue;
           }
        }

       ptr->next = NULL;

      if (prevPtr == NULL) {
           swInstallTable_head =  prevPtr = ptr;
       }

      prevPtr->next = ptr;
      prevPtr = ptr;
     }
    prevPtr->next = NULL;

    if (swInstallTable_head)
        return TRUE;
    else
        return FALSE;
}


/**
* @details 
*          This routine sends file download set request to BSM, it uses SIH Set
*          Processor to create and send the message to BSM.
* @param sihTagInfo is used to have the tag information for set request.
*/
TBOOL sendSwInstallSnmpSetRequest (
      TagInfo  sihTagInfo
      )
{
   TlvArray tlvArray;
   swInstallTableEntry * setReqData = NULL;
   TBOOL status = FALSE;
   int colmn = 0, maxCols = 0;

   clearBytes(&tlvArray,sizeof(tlvArray));

   setReqData = swInstallTable_head;

  /* max columns in row */
   maxCols = SW_INSTALL_MAX_COL;

   /* Set the Tags */
   if (sihTagInfo.colId)
   {
    /* Tag for setting an element in table */
    tlvArray.tlvInfo[0].tag = sihTagInfo;
   }
   else
   {
   /* Tag for setting a row in table */
   for(colmn = 1 ; colmn <= maxCols ; colmn++)
      {
      tlvArray.tlvInfo[colmn-1].tag.tableId  = sihTagInfo.tableId;
      tlvArray.tlvInfo[colmn-1].tag.rowId    = sihTagInfo.rowId;
      tlvArray.tlvInfo[colmn-1].tag.colId    = colmn;
      }
    }

   /* Fill Data in TLV */
   for(colmn = 1; colmn <= maxCols ; colmn++)
      {
       if (((sihTagInfo.colId EQ CONFIG_COL_ID_NONE) && (colmn EQ COLUMN_SWINSTALLINDEX)) ||
           (sihTagInfo.colId EQ COLUMN_SWINSTALLINDEX))
           {
           putUint32InArray( setReqData->index, tlvArray.tlvInfo[colmn-1].data );
           tlvArray.tlvInfo[colmn-1].len = sizeof(setReqData->index);
           tlvArray.numTlvs++;
           if (sihTagInfo.colId EQ COLUMN_SWINSTALLINDEX)
               break;
           }
       if (((sihTagInfo.colId EQ CONFIG_COL_ID_NONE) && (colmn EQ COLUMN_INSTALLATIONTYPE)) ||
           (sihTagInfo.colId EQ COLUMN_INSTALLATIONTYPE))
           {
           putUint32InArray( setReqData->installationType, tlvArray.tlvInfo[colmn-1].data );
           tlvArray.tlvInfo[colmn-1].len = sizeof(setReqData->installationType);
           tlvArray.numTlvs++;
           if (sihTagInfo.colId EQ COLUMN_INSTALLATIONTYPE)
               break;
           }
       if (((sihTagInfo.colId EQ CONFIG_COL_ID_NONE) && (colmn EQ COLUMN_SWINSTALLFILENAME)) ||
           (sihTagInfo.colId EQ COLUMN_SWINSTALLFILENAME))
           {
           clearBytes (tlvArray.tlvInfo[colmn-1].data, sizeof(tlvArray.tlvInfo[colmn-1].data));
           copyBytes (setReqData->fileName, strlen(setReqData->fileName),
                      tlvArray.tlvInfo[colmn-1].data);
           tlvArray.tlvInfo[colmn-1].len = SWINSTALLFILENAME_BUF_LEN-1;
           tlvArray.numTlvs++;
           if (sihTagInfo.colId EQ COLUMN_SWINSTALLFILENAME)
               break;
           }
       if (((sihTagInfo.colId EQ CONFIG_COL_ID_NONE) && (colmn EQ COLUMN_INSTALLER)) ||
           (sihTagInfo.colId EQ COLUMN_INSTALLER))
           {
           clearBytes (tlvArray.tlvInfo[colmn-1].data, sizeof(tlvArray.tlvInfo[colmn-1].data));
           copyBytes (setReqData->installer, strlen(setReqData->installer),
                      tlvArray.tlvInfo[colmn-1].data);
           tlvArray.tlvInfo[colmn-1].len = SWINSTALLFILENAME_BUF_LEN-1;
           tlvArray.numTlvs++;
           if (sihTagInfo.colId EQ COLUMN_INSTALLER)
               break;
           }
       }

   /* Invoke SIH Set Processor */
   status = sihSetProcessor (sihTagInfo,  &tlvArray);
   if (status EQ TRUE)
     {
      g_sihSwInstallSetReqProcessed = TRUE;
      g_sihSwInstallGetReqProcessed = FALSE;
      /* free the resources */
      free_swInstallTable();
     }

   return status;
}


/** Initializes the swInstall module */
void
init_swInstall(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_swInstallTable();
}

/*  # Determine the first/last column names */

/** Initialize the swInstallTable table by defining its contents and how it's structured */
void
initialize_table_swInstallTable(void)
{
    const oid swInstallTable_oid[] = {1,3,6,1,4,1,9344,501,SWINSTALL,1};
    const size_t swInstallTable_oid_len   = OID_LENGTH(swInstallTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("swInstall:init", "initializing table swInstallTable\n"));

    reg = netsnmp_create_handler_registration(
              "swInstallTable",     swInstallTable_handler,
              swInstallTable_oid, swInstallTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_UNSIGNED,  /* index: index */
                           0);
    table_info->min_column = COLUMN_SWINSTALLINDEX;
    table_info->max_column = COLUMN_INSTALLER;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = swInstallTable_get_first_data_point;
    iinfo->get_next_data_point  = swInstallTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}


#ifndef PWAV_SIH
/* create a new row in the (unsorted) table */
struct swInstallTable_entry *
swInstallTable_createEntry(
                 u_long  index,
                ) {
    struct swInstallTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct swInstallTable_entry);
    if (!entry)
        return NULL;

    entry->index = index;
    entry->next = swInstallTable_head;
    swInstallTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
swInstallTable_removeEntry( struct swInstallTable_entry *entry ) {
    struct swInstallTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = swInstallTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        swInstallTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}
#endif /* PWAV_SIH */


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
swInstallTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    TagInfo sihTagInfo;
    TBOOL status = FALSE;

    if (g_sihSwInstallGetReqProcessed EQ FALSE)
        {
        /* Set SIH Get Request Tag Info */
        sihTagInfo.tableId = SWINSTALL;
        sihTagInfo.rowId = CONFIG_ROW_ID_NONE;
        sihTagInfo.colId = CONFIG_COL_ID_NONE;

        status = sihGetProcessor (sihTagInfo);
        if ( status EQ TRUE )
            {
            logInfo("%s","Get Processor Succedded");
            if (swInstallTable_head)
                {
		g_swInstallFirstCall = 1;
                g_sihSwInstallGetReqProcessed = TRUE;
                }
            }
        else
            logError("%s","Get Processor Failed");
        }

    *my_loop_context = swInstallTable_head;
    return swInstallTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
swInstallTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct swInstallTable_entry *entry = (struct swInstallTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_UNSIGNED, entry->index );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the swInstallTable table */
int
swInstallTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request = NULL;
    netsnmp_table_request_info *table_info = NULL;
    struct swInstallTable_entry          *table_entry = NULL;
    int loopCount = 0;
    int ret;
    TagInfo sihTagInfo;
    int noofColms = 0, rowIndex = 0, colId = 0;
    TBOOL status = FALSE;

    DEBUGMSGTL(("swInstall:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {

            loopCount++;
            if (request->processed != 0)
            /* When Processed all requests, rows and colmns */
            {
	    g_prevSwInstallReqCount = 0;
            g_sihSwInstallGetReqProcessed = FALSE;
            /* free the resources */
            free_swInstallTable();
            /* Here loopCount is decremented, Due to calling of free function two times in SNMP-GETNEXT
             * on single parameter -- 20/07/11 */
            loopCount--;
            continue;
            }

            /* perform anything here that you need to do before each
               request is processed. */

            /* the following extracts the my_data_context pointer set in
               the loop functions above.  You can then use the results to
               help return data for the columns of the enbRegConfigTable table
               in question */

            table_entry = (struct swInstallTable_entry *)
                              netsnmp_extract_iterator_context(request);

            if ( table_entry == NULL) {
                if (reqinfo->mode == MODE_GET) {
                    netsnmp_set_request_error(reqinfo, request,SNMP_NOSUCHINSTANCE);
                    continue;
                }
                /* XXX: no row existed, if you support creation and this is a
                   set, start dealing with it here, else continue */
            }

            table_info  =     netsnmp_extract_table_info(      request);

            /* table_info->colnum contains the column number requested */
            /* table_info->indexes contains a linked list of snmp variable
               bindings for the indexes of the table.  Values in the list
               have been set corresponding to the indexes of the
               request */
            if (table_info==NULL) {
                continue;
            }
    
            switch (table_info->colnum) {
            case COLUMN_SWINSTALLINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->index);
                break;
            case COLUMN_INSTALLATIONTYPE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->installationType);
                break;
            case COLUMN_SWINSTALLFILENAME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->fileName,
                                          table_entry->fileName_len);
                break;
            case COLUMN_INSTALLER:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->installer,
                                          table_entry->installer_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
	if(g_swInstallFirstCall EQ 1)
         {
            g_swInstallFirstCall = 0;
            g_prevSwInstallReqCount = loopCount;
            // This will occur in case of, when SNMP-GET or SNMP-GETNEXT of Single Parameter occurred.
            // In the first call itself loopCount becomes one.
            // In General Case, the loopCount will be always > 1 because every table contains 
            // index column to fetch the row and remaining columns contain table attributes.
            if(loopCount EQ 1)
            {
               //Setting it to false in case of SNMP-GET request for single parameter.
               g_sihSwInstallGetReqProcessed = FALSE;
               // Free all resources.
               free_swInstallTable();
            }
         }
         else if(loopCount > 1 || g_prevSwInstallReqCount > 1)
         {
            //update g_prevReqCount with current loopCount for next call of Table_handler
            g_prevSwInstallReqCount = loopCount;
         }
         else if(loopCount EQ 1)
         {
            //Setting it to false in case of SNMP-GET request for single parameter.
            g_sihSwInstallGetReqProcessed = FALSE;
            // Free all resources.
            free_swInstallTable();
         }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
#ifndef PWAV_SIH
        for (request=requests; request; request=request->next) {
            table_entry = (struct swInstallTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_INDEX:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_FILENAME:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->fileName));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_INSTALLER:
	        /* or possibly 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->installer));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
#endif /* PWAV_SIH */
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
        g_sihSwInstallSetReqProcessed = FALSE;

            table_entry = (struct swInstallTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            if(table_entry == NULL){
                logInfo(" %s\n", "table_entry is NULL");
                if (reqinfo->mode == MODE_SET_ACTION) {
                    netsnmp_set_request_error(reqinfo, request,SNMP_NOSUCHINSTANCE);
                    continue;
                }
                /* XXX: no row existed, if you support creation and this is a
                   set, start dealing with it here, else continue */
            }

            if(table_info == NULL){
                logInfo(" %s\n", "table_info is NULL");
                continue;
            }

            colId = table_info->colnum;
            /* set the row index */
            rowIndex = requests->index;
    
            switch (table_info->colnum) {
            case COLUMN_SWINSTALLINDEX:
                table_entry->index     = *request->requestvb->val.integer;
                break;
            case COLUMN_INSTALLATIONTYPE:
                table_entry->installationType     = *request->requestvb->val.integer;
                break;
            case COLUMN_SWINSTALLFILENAME:
                memset( table_entry->fileName, 0,
                        sizeof(table_entry->fileName));
                memcpy( table_entry->fileName,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->fileName_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_INSTALLER:
                memset( table_entry->installer, 0,
                        sizeof(table_entry->installer));
                memcpy( table_entry->installer,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->installer_len =
                        request->requestvb->val_len;
                break;
            }
        }

        if ((request == NULL) && (g_sihSwInstallSetReqProcessed EQ FALSE))
            /* Processed all requests and table entry is filled with
             * requested data. */
            {
            /* Set SIH Set Request Tag Info */
            sihTagInfo.tableId = SWINSTALL;

            sihTagInfo.rowId = rowIndex;

            if (noofColms EQ 1)
                {
                sihTagInfo.colId = colId;
                }
            else
                {
                sihTagInfo.colId = CONFIG_COL_ID_NONE;
                }

            status = sendSwInstallSnmpSetRequest (sihTagInfo);
            if (status EQ TRUE)
                {
                logInfo("%s","SET Succedded");
                }
            else
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_GENERR );
            }

        break;

    case MODE_SET_UNDO:
#ifndef PWAV_SIH
        for (request=requests; request; request=request->next) {
            table_entry = (struct swInstallTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_INDEX:
                table_entry->index     = table_entry->old_index;
                table_entry->old_index = 0;
                break;
            case COLUMN_FILENAME:
                memcpy( table_entry->fileName,
                        table_entry->old_fileName,
                        sizeof(table_entry->fileName));
                memset( table_entry->old_fileName, 0,
                        sizeof(table_entry->fileName));
                table_entry->fileName_len =
                        table_entry->old_fileName_len;
                break;
            case COLUMN_INSTALLER:
                memcpy( table_entry->installer,
                        table_entry->old_installer,
                        sizeof(table_entry->installer));
                memset( table_entry->old_installer, 0,
                        sizeof(table_entry->installer));
                table_entry->installer_len =
                        table_entry->old_installer_len;
                break;
            }
        }
#endif /* PWAV_SIH */
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
