/*
 * enumstr_counterIds.c
 *
 *  Created on: 27-Aug-2012
 *      Author: jugaji
 */

#include "enumstr.h"

char *getCounterIdStr(
  IN CounterId counterId
  )
{
  switch (counterId)
  {
    case COUNTERID_AVGNUMACTVUESQCI1: return "COUNTERID_AVGNUMACTVUESQCI1";
    case COUNTERID_AVGNUMACTVUESQCI2: return "COUNTERID_AVGNUMACTVUESQCI2";
    case COUNTERID_AVGNUMACTVUESQCI3: return "COUNTERID_AVGNUMACTVUESQCI3";
    case COUNTERID_AVGNUMACTVUESQCI4: return "COUNTERID_AVGNUMACTVUESQCI4";
    case COUNTERID_AVGNUMACTVUESQCI5: return "COUNTERID_AVGNUMACTVUESQCI5";
    case COUNTERID_AVGNUMACTVUESQCI6: return "COUNTERID_AVGNUMACTVUESQCI6";
    case COUNTERID_AVGNUMACTVUESQCI7: return "COUNTERID_AVGNUMACTVUESQCI7";
    case COUNTERID_AVGNUMACTVUESQCI8: return "COUNTERID_AVGNUMACTVUESQCI8";
    case COUNTERID_AVGNUMACTVUESQCI9: return "COUNTERID_AVGNUMACTVUESQCI9";

    case COUNTERID_PKTUULOSSRATEDLQCI1: return "COUNTERID_PKTUULOSSRATEDLQCI1";
    case COUNTERID_PKTUULOSSRATEDLQCI2: return "COUNTERID_PKTUULOSSRATEDLQCI2";
    case COUNTERID_PKTUULOSSRATEDLQCI3: return "COUNTERID_PKTUULOSSRATEDLQCI3";
    case COUNTERID_PKTUULOSSRATEDLQCI4: return "COUNTERID_PKTUULOSSRATEDLQCI4";
    case COUNTERID_PKTUULOSSRATEDLQCI5: return "COUNTERID_PKTUULOSSRATEDLQCI5";
    case COUNTERID_PKTUULOSSRATEDLQCI6: return "COUNTERID_PKTUULOSSRATEDLQCI6";
    case COUNTERID_PKTUULOSSRATEDLQCI7: return "COUNTERID_PKTUULOSSRATEDLQCI7";
    case COUNTERID_PKTUULOSSRATEDLQCI8: return "COUNTERID_PKTUULOSSRATEDLQCI8";
    case COUNTERID_PKTUULOSSRATEDLQCI9: return "COUNTERID_PKTUULOSSRATEDLQCI9";

    case COUNTERID_PKTDELAYDLQCI1: return "COUNTERID_PKTDELAYDLQCI1";
    case COUNTERID_PKTDELAYDLQCI2: return "COUNTERID_PKTDELAYDLQCI2";
    case COUNTERID_PKTDELAYDLQCI3: return "COUNTERID_PKTDELAYDLQCI3";
    case COUNTERID_PKTDELAYDLQCI4: return "COUNTERID_PKTDELAYDLQCI4";
    case COUNTERID_PKTDELAYDLQCI5: return "COUNTERID_PKTDELAYDLQCI5";
    case COUNTERID_PKTDELAYDLQCI6: return "COUNTERID_PKTDELAYDLQCI6";
    case COUNTERID_PKTDELAYDLQCI7: return "COUNTERID_PKTDELAYDLQCI7";
    case COUNTERID_PKTDELAYDLQCI8: return "COUNTERID_PKTDELAYDLQCI8";
    case COUNTERID_PKTDELAYDLQCI9: return "COUNTERID_PKTDELAYDLQCI9";

    case COUNTERID_PKTDISCRATEDLQCI1: return "COUNTERID_PKTDISCRATEDLQCI1";
    case COUNTERID_PKTDISCRATEDLQCI2: return "COUNTERID_PKTDISCRATEDLQCI2";
    case COUNTERID_PKTDISCRATEDLQCI3: return "COUNTERID_PKTDISCRATEDLQCI3";
    case COUNTERID_PKTDISCRATEDLQCI4: return "COUNTERID_PKTDISCRATEDLQCI4";
    case COUNTERID_PKTDISCRATEDLQCI5: return "COUNTERID_PKTDISCRATEDLQCI5";
    case COUNTERID_PKTDISCRATEDLQCI6: return "COUNTERID_PKTDISCRATEDLQCI6";
    case COUNTERID_PKTDISCRATEDLQCI7: return "COUNTERID_PKTDISCRATEDLQCI7";
    case COUNTERID_PKTDISCRATEDLQCI8: return "COUNTERID_PKTDISCRATEDLQCI8";
    case COUNTERID_PKTDISCRATEDLQCI9: return "COUNTERID_PKTDISCRATEDLQCI9";

    case COUNTERID_PKTLOSSULQCI1: return "COUNTERID_PKTLOSSULQCI1";
    case COUNTERID_PKTLOSSULQCI2: return "COUNTERID_PKTLOSSULQCI2";
    case COUNTERID_PKTLOSSULQCI3: return "COUNTERID_PKTLOSSULQCI3";
    case COUNTERID_PKTLOSSULQCI4: return "COUNTERID_PKTLOSSULQCI4";
    case COUNTERID_PKTLOSSULQCI5: return "COUNTERID_PKTLOSSULQCI5";
    case COUNTERID_PKTLOSSULQCI6: return "COUNTERID_PKTLOSSULQCI6";
    case COUNTERID_PKTLOSSULQCI7: return "COUNTERID_PKTLOSSULQCI7";
    case COUNTERID_PKTLOSSULQCI8: return "COUNTERID_PKTLOSSULQCI8";
    case COUNTERID_PKTLOSSULQCI9: return "COUNTERID_PKTLOSSULQCI9";

    case COUNTERID_PRBUSAGEDLQCI1: return "COUNTERID_PRBUSAGEDLQCI1";
    case COUNTERID_PRBUSAGEDLQCI2: return "COUNTERID_PRBUSAGEDLQCI2";
    case COUNTERID_PRBUSAGEDLQCI3: return "COUNTERID_PRBUSAGEDLQCI3";
    case COUNTERID_PRBUSAGEDLQCI4: return "COUNTERID_PRBUSAGEDLQCI5";
    case COUNTERID_PRBUSAGEDLQCI5: return "COUNTERID_PRBUSAGEDLQCI5";
    case COUNTERID_PRBUSAGEDLQCI6: return "COUNTERID_PRBUSAGEDLQCI6";
    case COUNTERID_PRBUSAGEDLQCI7: return "COUNTERID_PRBUSAGEDLQCI7";
    case COUNTERID_PRBUSAGEDLQCI8: return "COUNTERID_PRBUSAGEDLQCI8";
    case COUNTERID_PRBUSAGEDLQCI9: return "COUNTERID_PRBUSAGEDLQCI9";

    case COUNTERID_PRBUSAGEULQCI1: return "COUNTERID_PRBUSAGEULQCI1";
    case COUNTERID_PRBUSAGEULQCI2: return "COUNTERID_PRBUSAGEULQCI2";
    case COUNTERID_PRBUSAGEULQCI3: return "COUNTERID_PRBUSAGEULQCI3";
    case COUNTERID_PRBUSAGEULQCI4: return "COUNTERID_PRBUSAGEULQCI4";
    case COUNTERID_PRBUSAGEULQCI5: return "COUNTERID_PRBUSAGEULQCI5";
    case COUNTERID_PRBUSAGEULQCI6: return "COUNTERID_PRBUSAGEULQCI6";
    case COUNTERID_PRBUSAGEULQCI7: return "COUNTERID_PRBUSAGEULQCI7";
    case COUNTERID_PRBUSAGEULQCI8: return "COUNTERID_PRBUSAGEULQCI8";
    case COUNTERID_PRBUSAGEULQCI9: return "COUNTERID_PRBUSAGEULQCI9";

    case COUNTERID_NUMACTVUESDLQCI1: return "COUNTERID_NUMACTVUESDLQCI1";
    case COUNTERID_NUMACTVUESDLQCI2: return "COUNTERID_NUMACTVUESDLQCI2";
    case COUNTERID_NUMACTVUESDLQCI3: return "COUNTERID_NUMACTVUESDLQCI3";
    case COUNTERID_NUMACTVUESDLQCI4: return "COUNTERID_NUMACTVUESDLQCI4";
    case COUNTERID_NUMACTVUESDLQCI5: return "COUNTERID_NUMACTVUESDLQCI5";
    case COUNTERID_NUMACTVUESDLQCI6: return "COUNTERID_NUMACTVUESDLQCI6";
    case COUNTERID_NUMACTVUESDLQCI7: return "COUNTERID_NUMACTVUESDLQCI7";
    case COUNTERID_NUMACTVUESDLQCI8: return "COUNTERID_NUMACTVUESDLQCI8";
    case COUNTERID_NUMACTVUESDLQCI9: return "COUNTERID_NUMACTVUESDLQCI9";

    case COUNTERID_NUMACTVUESULQCI1: return "COUNTERID_NUMACTVUESULQCI1";
    case COUNTERID_NUMACTVUESULQCI2: return "COUNTERID_NUMACTVUESULQCI2";
    case COUNTERID_NUMACTVUESULQCI3: return "COUNTERID_NUMACTVUESULQCI3";
    case COUNTERID_NUMACTVUESULQCI4: return "COUNTERID_NUMACTVUESULQCI4";
    case COUNTERID_NUMACTVUESULQCI5: return "COUNTERID_NUMACTVUESULQCI5";
    case COUNTERID_NUMACTVUESULQCI6: return "COUNTERID_NUMACTVUESULQCI6";
    case COUNTERID_NUMACTVUESULQCI7: return "COUNTERID_NUMACTVUESULQCI7";
    case COUNTERID_NUMACTVUESULQCI8: return "COUNTERID_NUMACTVUESULQCI8";
    case COUNTERID_NUMACTVUESULQCI9: return "COUNTERID_NUMACTVUESULQCI9";

    case COUNTERID_TOTALPRBUSAGEDL: return "COUNTERID_TOTALPRBUSAGEDL";
    case COUNTERID_TOTALPRBUSAGEUL: return "COUNTERID_TOTALPRBUSAGEUL";
    case COUNTERID_RECVRAPREAMBLESDEDICATED: return "COUNTERID_RECVRAPREAMBLESDEDICATED";
    case COUNTERID_RECVRAPREAMBLESLOWRANGE:  return "COUNTERID_RECVRAPREAMBLESLOWRANGE";
    case COUNTERID_RECVRAPREAMBLESHIGHRANGE: return "COUNTERID_RECVRAPREAMBLESHIGHRANGE";
    case COUNTERID_MAX:                      return "COUNTERID_MAX";

    default: return"Unknown Counter Id";
  }
}

char *getMeasurementStoppedCauseStr(
  MeasurementStopCause cause
  )
{
  switch (cause)
  {
    case OPSTOP_RECEIVED:            return "OPSTOP_RECEIVED";
    case MEASUREMENT_COMPLETED:      return "MEASUREMENT_COMPLETED";
    case OPERATOR_INITIATED:         return "OPERATOR_INITIATED";
    case REPORTING_TIMER_EXPIRED:    return "REPORTING_TIMER_EXPIRED";
    case UNEXPECTED_SEQ_NUM_RCVD:    return "UNEXPECTED_SEQ_NUM_RCVD";
    case SAMPLING_TIMER_EXPIRED:     return "SAMPLING_TIMER_EXPIRED";
    case FAILURE_FROM_L2:            return "FAILURE_FROM_L2";
    case ENODEB_LOCK:                return "ENODEB_LOCK";
  }
  return "Undefined cause";
}
