/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef ALARMHISTORY_H
#define ALARMHISTORY_H

/* function declarations */
void init_alarmHistory(void);
void initialize_table_alarmHistoryTable(void);

/* column number definitions for table alarmHistoryTable */
       #define COLUMN_ALARMHISTORY_INDEX		1
       #define COLUMN_ALARMHISTORY_ALARMNOTIFICATIONTYPE		2
       #define COLUMN_ALARMHISTORY_NOTIFICATIONSEQUENCENUMBER		3
       #define COLUMN_ALARMHISTORY_DATEANDTIMESTAMP		4
       #define COLUMN_ALARMHISTORY_ALARMTYPE		5
       #define COLUMN_ALARMHISTORY_ALARMID		6
       #define COLUMN_ALARMHISTORY_ALARMSEVERITY		7
       #define COLUMN_ALARMHISTORY_ALARMCAUSE		8
       #define COLUMN_ALARMHISTORY_ALARMLOCATION	9
       #define COLUMN_ALARMHISTORY_ALARMADDITIONALTEXT	10

#define ALARMHISTORY_MAX_COL	COLUMN_ALARMHISTORY_ALARMADDITIONALTEXT
#define ALARMHISTORY_DATEANDTIMESTAMP_MAX_LEN       18
#define ALARMHISTORY_ALARMLOCATION_MAX_LEN          257
#define ALARMHISTORY_ALARMADDITIONALTEXT_MAX_LEN    257

    /* Typical data structure for a row entry */
struct alarmHistoryTable_entry {
    /* Index values */
    unsigned int index;

    /* Column values */
    unsigned int alarmNotificationType;
    unsigned int notificationSequenceNumber;
    char dateAndTimeStamp[ALARMHISTORY_DATEANDTIMESTAMP_MAX_LEN];
    size_t dateAndTimeStamp_len;
    unsigned int alarmType;
    unsigned int alarmId;
    unsigned int alarmSeverity;
    unsigned int alarmCause;
    char alarmLocation[ALARMHISTORY_ALARMLOCATION_MAX_LEN];
    size_t alarmLocation_len;
    char alarmAdditionalText[ALARMHISTORY_ALARMADDITIONALTEXT_MAX_LEN];
    size_t alarmAdditionalText_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct alarmHistoryTable_entry *next;
};

#endif /* ALARMHISTORY_H */
