/* @file    msg_desc.c
 * @brief DESCRIPTION
 *          This description is mandatory; otherwise IMC would not work.
 *          So, whenever a new message is defined, this file should be updated.
 *
 * @details Copyright PowerWave Technologies, Inc., 2009
 *
 * AutHor :  LTE Team
 * Date   :
 * Change History:   09-Sep-2010  - Shweta
 *                   - Removed messages and modules interface functions which
 *                     are not required.
 *                     10-Dec-2010 Shweta - Indented the entire file. Added all missing print functions.
 *
 */

#include "msg_desc.h"

static void initPrmIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_TIMEKEEPER_PRM_TIMEOUT_IND, MODID_PRM, MODID_PRM, sizeof(MsgTimeoutInd), DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPrmIntExitMsgDescTable()
{
  initElementInMsgDescTable( MSG_IMC_PRM_PHYSHUTDOWN_CMD, MODID_PRM, MODID_PRM, sizeof(MsgPrmModExitCmd), DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initBsmIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_TIMEKEEPER_BSM_TIMEOUT_IND, MODID_BSM, MODID_BSM, sizeof(MsgTimeoutInd), DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initDehIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_TIMEKEEPER_DEH_TIMEOUT_IND, MODID_DEH, MODID_DEH, sizeof(MsgTimeoutInd), DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPmhIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_TIMEKEEPER_PMH_TIMEOUT_IND, MODID_PMH, MODID_PMH, sizeof(MsgTimeoutInd), DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initWihIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_TIMEKEEPER_WIH_TIMEOUT_IND, MODID_WIH, MODID_WIH, sizeof(MsgTimeoutInd), DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initLthIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_TIMEKEEPER_LTH_TIMEOUT_IND, MODID_LTH, MODID_LTH, sizeof(MsgTimeoutInd), DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}
static void initSihIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_TIMEKEEPER_SIH_TIMEOUT_IND, MODID_SIH, MODID_SIH, sizeof(MsgTimeoutInd), DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}
static void initFthIntMsgDescTable()
{
	initElementInMsgDescTable( MSG_TIMEKEEPER_FTH_TIMEOUT_IND, MODID_FTH, MODID_FTH, sizeof(MsgTimeoutInd), DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPrmBsmIntMsgDescTable()
{
   /* PRM -> BSM Interface */
   initElementInMsgDescTable( MSG_PRM_BSM_EXIT_CMD,          MODID_PRM, MODID_BSM, sizeof(MsgPrmModExitCmd),        DEFAULT_MAX_MSG_INST, printMsgExitCmd,               MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC);
   initElementInMsgDescTable( MSG_PRM_BSM_HELLO,             MODID_PRM, MODID_BSM, sizeof(MsgPrmModHello),          DEFAULT_MAX_MSG_INST, printMsgHello,                 MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_PRM_BSM_ALL_MODULES_UP_IND,MODID_PRM, MODID_BSM, sizeof(MsgPrmBsmAllModulesUpInd),DEFAULT_MAX_MSG_INST, printMsgPrmBsmAllModulesUpInd, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_PRM_BSM_MOD_UP_IND,        MODID_PRM, MODID_BSM, sizeof(MsgPrmBsmModUpInd),       DEFAULT_MAX_MSG_INST, printMsgModUpInd,              MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_PRM_BSM_MOD_DOWN_IND,      MODID_PRM, MODID_BSM, sizeof(MsgPrmBsmModDownInd),     DEFAULT_MAX_MSG_INST, printMsgModDownInd,            MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_PRM_BSM_SW_ACTIVATE_SUCC,  MODID_PRM, MODID_BSM, sizeof(MsgPrmBsmSwActivateSucc), DEFAULT_MAX_MSG_INST, printMsgPrmBrmSwActSucc,       MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_PRM_BSM_SW_ACTIVATE_FAIL,  MODID_PRM, MODID_BSM, sizeof(MsgPrmBsmSwActivateFail), DEFAULT_MAX_MSG_INST, printMsgPrmBrmSwActFail,       MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_PRM_BSM_SW_ACTIVATE_RSP,   MODID_PRM, MODID_BSM, 0 /*encBuf.len*/               , DEFAULT_MAX_MSG_INST, printSetObjRspSuccMsg,         MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_PRM_BSM_SW_ACTIVATE_REJ,   MODID_PRM, MODID_BSM, 0 /*encBuf.len*/               , DEFAULT_MAX_MSG_INST, printSetObjRspFailMsg,         MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_PRM_BSM_GET_OBJ_SUCC,      MODID_PRM, MODID_BSM, 0 /*encBuf.len*/,                DEFAULT_MAX_MSG_INST, printGetObjRspSuccMsg,         MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

   /* BSM -> PRM Interface */
   initElementInMsgDescTable( MSG_BSM_PRM_RESTART_REQ,      MODID_BSM, MODID_PRM, 0,                                    DEFAULT_MAX_MSG_INST, NULL,                           MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_BSM_PRM_SW_ACTIVATE_REQ,  MODID_BSM, MODID_PRM, 0 /*encBuf.len*/,                     DEFAULT_MAX_MSG_INST, printSetObjReqMsg,              MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_BSM_PRM_REBOOT_REQ,       MODID_BSM, MODID_PRM, 0,                                    DEFAULT_MAX_MSG_INST, NULL,                           MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_BSM_PRM_HELLO_ACK,        MODID_BSM, MODID_PRM, sizeof(MsgModPrmHelloAck),            DEFAULT_MAX_MSG_INST, printMsgHelloAck,               MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_BSM_PRM_START_IND,        MODID_BSM, MODID_PRM, sizeof(MsgStartInd),                  DEFAULT_MAX_MSG_INST, printStartIndMsg,               MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_BSM_PRM_GET_OBJ_REQ,      MODID_BSM, MODID_PRM, 0 /*encBuf.len*/,                     DEFAULT_MAX_MSG_INST, printGetObjReqMsg,              MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_BSM_PRM_SET_MSG_TRACE,    MODID_BSM, MODID_PRM, sizeof(MsgTrace),                     DEFAULT_MAX_MSG_INST, printMsgSetMsgTrace,            MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_BSM_PRM_SW_INSTALL_REQ,   MODID_BSM, MODID_PRM, 0 /*encBuf.len*/,                     DEFAULT_MAX_MSG_INST, printSetObjReqMsg,              MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_PRM_BSM_SW_INSTALL_ACCEPTED,   MODID_PRM, MODID_BSM, 0 /*encBuf.len*/,                DEFAULT_MAX_MSG_INST, printSetObjRspSuccMsg,          MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_PRM_BSM_SW_INSTALL_SUCC,  MODID_PRM, MODID_BSM, sizeof(MsgPrmBsmSwInstallSucc),       DEFAULT_MAX_MSG_INST, printMsgPrmBsmSwInstallCmpl,    MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_PRM_BSM_SW_INSTALL_REJ,   MODID_PRM, MODID_BSM, 0 /*encBuf.len*/,                     DEFAULT_MAX_MSG_INST, printSetObjRspFailMsg,          MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_PRM_BSM_SW_INSTALL_FAIL,  MODID_PRM, MODID_BSM, sizeof(MsgPrmBsmSwInstallFail),       DEFAULT_MAX_MSG_INST, printMsgPrmBsmSwInstallFail,    MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_PRM_BSM_CONFIG_INSTALL_REQ,  MODID_PRM, MODID_BSM, sizeof(MsgPrmBsmConfigInstallReq), DEFAULT_MAX_MSG_INST, printMsgPrmBsmConfigInstallReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_BSM_PRM_CONFIG_INSTALL_SUCC, MODID_BSM, MODID_PRM, sizeof(MsgBsmPrmConfigInstallSucc),DEFAULT_MAX_MSG_INST, PrintMsgBsmPrmConfigInstallSucc,MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_BSM_PRM_CONFIG_INSTALL_FAIL, MODID_BSM, MODID_PRM, sizeof(MsgBsmPrmConfigInstallFail),DEFAULT_MAX_MSG_INST, PrintMsgBsmPrmConfigInstallFail,MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_BSM_PRM_SET_LOG_CFG, MODID_BSM, MODID_PRM, sizeof(MsgBsmPrmSetLogCfg),DEFAULT_MAX_MSG_INST, PrintMsgSetLogConfig, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_BSM_PRM_SET_OBJ_REQ, MODID_BSM, MODID_PRM, 0 /*encBuf.len*/, DEFAULT_MAX_MSG_INST, printSetObjReqMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
   initElementInMsgDescTable( MSG_PRM_BSM_SET_OBJ_SUCC, MODID_PRM, MODID_BSM, 0 /*encBuf.len*/, DEFAULT_MAX_MSG_INST, printSetObjRspSuccMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPrmDehIntMsgDescTable()
{
  /* PRM -> DEH Interface */
  initElementInMsgDescTable( MSG_PRM_DEH_EXIT_CMD,  MODID_PRM, MODID_DEH, sizeof(MsgPrmModExitCmd), DEFAULT_MAX_MSG_INST, printMsgExitCmd,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_DEH_HELLO,     MODID_PRM, MODID_DEH, sizeof(MsgPrmModHello),   DEFAULT_MAX_MSG_INST, printMsgHello,     MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  /* DEH -> PRM Interface */
  initElementInMsgDescTable( MSG_DEH_PRM_HELLO_ACK, MODID_DEH, MODID_PRM, sizeof(MsgModPrmHelloAck),DEFAULT_MAX_MSG_INST, printMsgHelloAck,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_PRM_START_IND, MODID_DEH, MODID_PRM, sizeof(MsgStartInd),      DEFAULT_MAX_MSG_INST, printStartIndMsg,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_PRM_DEH_RH_SW_INSTALL_REQ,  MODID_PRM, MODID_DEH, sizeof(MsgPrmDehRhSwInstallReq), DEFAULT_MAX_MSG_INST, printMsgPrmDehRhSwInstallReq,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_PRM_RH_SW_INSTALL_SUCC, MODID_DEH, MODID_PRM, sizeof(MsgDehPrmRhSwInstallSucc),DEFAULT_MAX_MSG_INST, printMsgDehPrmRhSwInstallSucc,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_PRM_RH_SW_INSTALL_FAIL, MODID_DEH, MODID_PRM, sizeof(MsgDehPrmRhSwInstallFail),DEFAULT_MAX_MSG_INST, printMsgDehPrmRhSwInstallFail,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_PRM_DEH_RH_SW_ACTIVATE_REQ,  MODID_PRM, MODID_DEH, sizeof(MsgPrmDehRhSwActivateReq), DEFAULT_MAX_MSG_INST, printMsgPrmDehRhSwActivateReq,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_PRM_RH_SW_ACTIVATE_SUCC, MODID_DEH, MODID_PRM, sizeof(MsgDehPrmRhSwActivateSucc),DEFAULT_MAX_MSG_INST, printMsgDehPrmRhSwActivateSucc,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_PRM_RH_SW_ACTIVATE_FAIL, MODID_DEH, MODID_PRM, sizeof(MsgDehPrmRhSwActivateFail),DEFAULT_MAX_MSG_INST, printMsgDehPrmRhSwActivateFail,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_DEH_PRM_RH_VERSION_INFO, MODID_DEH, MODID_PRM, sizeof(MsgDehPrmRhVersionInfo),DEFAULT_MAX_MSG_INST, printMsgDehPrmRhVersionInfo,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPrmEgtpIntMsgDescTable()
{
  /* PRM -> DEH Interface */
  initElementInMsgDescTable( MSG_PRM_EGTP_EXIT_CMD,  MODID_PRM, MODID_EGTP, sizeof(MsgPrmModExitCmd), DEFAULT_MAX_MSG_INST, printMsgExitCmd, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_EGTP_HELLO,     MODID_PRM, MODID_EGTP, sizeof(MsgPrmModHello),   DEFAULT_MAX_MSG_INST, printMsgHello,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  /* DEH -> PRM Interface */
  initElementInMsgDescTable( MSG_EGTP_PRM_HELLO_ACK, MODID_EGTP, MODID_PRM, sizeof(MsgModPrmHelloAck),DEFAULT_MAX_MSG_INST, printMsgHelloAck,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_EGTP_PRM_START_IND, MODID_EGTP, MODID_PRM, sizeof(MsgStartInd),      DEFAULT_MAX_MSG_INST, printStartIndMsg,MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPrmFthIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PRM_FTH_EXIT_CMD,  MODID_PRM, MODID_FTH, sizeof(MsgPrmModExitCmd), DEFAULT_MAX_MSG_INST, printMsgExitCmd,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_FTH_HELLO,     MODID_PRM, MODID_FTH, sizeof(MsgPrmModHello),   DEFAULT_MAX_MSG_INST, printMsgHello,     MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  /* FTH -> PRM Interface */
  initElementInMsgDescTable( MSG_FTH_PRM_HELLO_ACK, MODID_FTH, MODID_PRM, sizeof(MsgModPrmHelloAck),DEFAULT_MAX_MSG_INST, printMsgHelloAck,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_FTH_PRM_START_IND, MODID_FTH, MODID_PRM, sizeof(MsgStartInd),      DEFAULT_MAX_MSG_INST, printStartIndMsg,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPrmTuclIntMsgDescTable()
{
  /* PRM -> DEH Interface */
  initElementInMsgDescTable( MSG_PRM_TUCL_EXIT_CMD,  MODID_PRM, MODID_TUCL, sizeof(MsgPrmModExitCmd), DEFAULT_MAX_MSG_INST, printMsgExitCmd, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_TUCL_HELLO,     MODID_PRM, MODID_TUCL, sizeof(MsgPrmModHello),   DEFAULT_MAX_MSG_INST, printMsgHello,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  /* DEH -> PRM Interface */
  initElementInMsgDescTable( MSG_TUCL_PRM_HELLO_ACK, MODID_TUCL, MODID_PRM, sizeof(MsgModPrmHelloAck),DEFAULT_MAX_MSG_INST, printMsgHelloAck,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_TUCL_PRM_START_IND, MODID_TUCL, MODID_PRM, sizeof(MsgStartInd),      DEFAULT_MAX_MSG_INST, printStartIndMsg,MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPrmUehIntMsgDescTable()
{
  /* PRM -> UEH Interface */
  initElementInMsgDescTable( MSG_PRM_UEH_EXIT_CMD,  MODID_PRM, MODID_UEH, sizeof(MsgPrmModExitCmd), DEFAULT_MAX_MSG_INST, printMsgExitCmd,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_UEH_HELLO,     MODID_PRM, MODID_UEH, sizeof(MsgPrmModHello),   DEFAULT_MAX_MSG_INST, printMsgHello,   MSGTRACELEVEL_MSGWITHPARAMS,  MSGTRACEDIRECTION_MSGINBOTHDIREC );
  /* UEH -> PRM Interface */
  initElementInMsgDescTable( MSG_UEH_PRM_HELLO_ACK, MODID_UEH, MODID_PRM, sizeof(MsgModPrmHelloAck),DEFAULT_MAX_MSG_INST, printMsgHelloAck,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UEH_PRM_START_IND, MODID_UEH, MODID_PRM, sizeof(MsgStartInd),      DEFAULT_MAX_MSG_INST, printStartIndMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initBsmUehIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_BSM_UEH_GET_ACTIVE_UE_STATUS_REQ,   MODID_BSM, MODID_UEH, sizeof(MsgBsmUehActiveUeStatusReq), DEFAULT_MAX_MSG_INST, printMsgActiveUeStatusReq,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UEH_BSM_GET_ACTIVE_UE_STATUS_RSP,   MODID_UEH, MODID_BSM, sizeof(MsgUehBsmActiveUeStatusRsp), DEFAULT_MAX_MSG_INST, printMsgActiveUeStatusRsp,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_UEH_GET_UE_EVENT_HISTORY_REQ,   MODID_BSM, MODID_UEH, sizeof(MsgBsmUehUeEventHistoryReq), DEFAULT_MAX_MSG_INST, printMsgBsmUehUeEventHistoryReq,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UEH_BSM_GET_UE_EVENT_HISTORY_RSP,   MODID_UEH, MODID_BSM, sizeof(MsgUehBsmUeEventHistoryRsp), DEFAULT_MAX_MSG_INST, printMsgUehBsmUeEventHistoryRsp,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_UEH_MOD_STATE_REQ,        MODID_BSM, MODID_UEH, sizeof(MsgBsmUehModStateReq),     DEFAULT_MAX_MSG_INST, printMsgBsmUehModStateReq,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UEH_BSM_MOD_STATE_RSP,        MODID_UEH, MODID_BSM, sizeof(MsgUehBsmModStateRsp),     DEFAULT_MAX_MSG_INST, printMsgUehBsmModStateRsp,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_UEH_UEEVENTHISTORYLOG_CONFIG_REQ,  MODID_BSM, MODID_UEH, sizeof(MsgBsmUehUeEventHistoryLogConfigReq),  DEFAULT_MAX_MSG_INST, printMsgBsmUehUeEventHistoryLogConfigReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UEH_BSM_UEEVENTHISTORYLOG_CONFIG_SUCC,  MODID_UEH, MODID_BSM, sizeof(MsgUehBsmUeEventHistoryLogConfigSucc),  DEFAULT_MAX_MSG_INST, printMsgUehBsmUeEventHistoryLogConfigSucc, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UEH_BSM_UEEVENTHISTORYLOG_CONFIG_FAIL,  MODID_UEH, MODID_BSM, sizeof(MsgUehBsmUeEventHistoryLogConfigFail),  DEFAULT_MAX_MSG_INST, printMsgUehBsmUeEventHistoryLogConfigFail, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_CEM_ENB_CONFIG_REQ,  MODID_BSM, MODID_CEM, sizeof(MsgBsmUehEnbConfigReq),  DEFAULT_MAX_MSG_INST, printMsgBsmUehConfigReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_CEM_BSM_ENB_CONFIG_SUCC, MODID_CEM, MODID_BSM, sizeof(MsgUehBsmEnbConfigSucc), DEFAULT_MAX_MSG_INST, printMsgEnbConfigSucc,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_CEM_BSM_ENB_CONFIG_FAIL, MODID_CEM, MODID_BSM, sizeof(MsgUehBsmEnbConfigFail), DEFAULT_MAX_MSG_INST, printMsgEnbConfigFail,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  /* Events related Cell Manager */
  initElementInMsgDescTable( MSG_BSM_CEM_OPSTART_REQ,     MODID_BSM, MODID_CEM, 0,                              DEFAULT_MAX_MSG_INST, NULL,                      MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_CEM_BSM_OPSTART_SUCC,    MODID_CEM, MODID_BSM, 0,                              DEFAULT_MAX_MSG_INST, NULL,                      MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_CEM_BSM_OPSTART_FAIL,    MODID_CEM, MODID_BSM, sizeof(OpStartFail),            DEFAULT_MAX_MSG_INST, printMsgOpStartFail,       MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_CEM_OPSTOP_REQ,      MODID_BSM, MODID_CEM, sizeof(MsgBsmModOpStopReq),     DEFAULT_MAX_MSG_INST, printMsgOpStopReq,         MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_CEM_BSM_OPSTOP_SUCC,     MODID_CEM, MODID_BSM, 0,                              DEFAULT_MAX_MSG_INST, NULL,                      MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_UEH_SET_MSG_TRACE,   MODID_BSM, MODID_UEH, sizeof(MsgTrace),               DEFAULT_MAX_MSG_INST, printMsgSetMsgTrace,       MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  /* Events related S1 Manager */
  initElementInMsgDescTable( MSG_BSM_S1M_OPSTART_REQ,     MODID_BSM,  MODID_S1M, 0,                               DEFAULT_MAX_MSG_INST, NULL,                          MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_S1M_BSM_OPSTART_SUCC,    MODID_S1M, MODID_BSM,  0,                               DEFAULT_MAX_MSG_INST, NULL,                          MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_S1M_BSM_OPSTART_FAIL,    MODID_S1M, MODID_BSM,  sizeof(OpStartFail),             DEFAULT_MAX_MSG_INST, printMsgOpStartFail,           MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_S1M_OPSTOP_REQ,      MODID_BSM, MODID_S1M,  sizeof(MsgBsmModOpStopReq),      DEFAULT_MAX_MSG_INST, printMsgOpStopReq,             MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_S1M_BSM_OPSTOP_SUCC,     MODID_S1M, MODID_BSM,  0,                               DEFAULT_MAX_MSG_INST, NULL,                          MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_S1M_BSM_LINK_UP_IND,     MODID_S1M, MODID_BSM,  sizeof(MsgS1apBsmLinkUpInd),     DEFAULT_MAX_MSG_INST, printMsgS1apBsmS1LinkUpInd,    MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_S1M_BSM_LINK_DOWN_IND,   MODID_S1M, MODID_BSM,  sizeof(MsgS1apBsmLinkDownInd),   DEFAULT_MAX_MSG_INST, printMsgS1apBsmS1LinkDownInd,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_S1M_BSM_RESET_IND,       MODID_S1M, MODID_BSM,  sizeof(MsgS1apBsmS1ResetInd),    DEFAULT_MAX_MSG_INST, printMsgS1apBsmS1ResetInd,     MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_S1M_BSM_LINK_CLOSED_IND, MODID_S1M, MODID_BSM,  sizeof(MsgS1apBsmLinkClosedInd), DEFAULT_MAX_MSG_INST, printMsgS1apBsmS1LinkClosedInd,MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_S1M_CONFIG_REQ,      MODID_BSM,  MODID_S1M, sizeof(MsgBsmS1apConfigReq),     DEFAULT_MAX_MSG_INST, printMsgBsmS1apConfigReq,      MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_S1M_BSM_CONFIG_SUCC,     MODID_S1M, MODID_BSM,  sizeof(MsgS1apBsmConfigSucc),    DEFAULT_MAX_MSG_INST, printMsgEnbConfigSucc,         MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_S1M_BSM_CONFIG_FAIL,     MODID_S1M, MODID_BSM,  sizeof(MsgS1apBsmConfigFail),    DEFAULT_MAX_MSG_INST, printMsgEnbConfigFail,         MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_S1M_BSM_UNKNOWN_ENB_UE_ID, MODID_UEH, MODID_BSM,  sizeof(MsgUehBsmUnknownEnbUeS1apId),    DEFAULT_MAX_MSG_INST, printMsgEnbConfigFail,         MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_CEM_CELL_BAR_REQ,     MODID_BSM, MODID_CEM, sizeof(MsgBsmUehCellBarReq),    DEFAULT_MAX_MSG_INST, printMsgBsmUehCellBarReq,    MSGTRACELEVEL_MSGWITHPARAMS,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_CEM_BSM_CELL_BAR_SUCC,    MODID_CEM, MODID_BSM, sizeof(MsgUehBsmCellBarSucc),   DEFAULT_MAX_MSG_INST, printMsgUehBsmCellBarSucc,   MSGTRACELEVEL_MSGWITHPARAMS,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_CEM_CELL_UNBAR_REQ,   MODID_BSM, MODID_CEM, sizeof(MsgBsmUehCellUnbarReq),  DEFAULT_MAX_MSG_INST, printMsgBsmUehCellUnbarReq,  MSGTRACELEVEL_MSGWITHPARAMS,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_CEM_BSM_CELL_UNBAR_SUCC,  MODID_CEM, MODID_BSM, sizeof(MsgUehBsmCellUnbarSucc), DEFAULT_MAX_MSG_INST, printMsgUehBsmCellUnbarSucc, MSGTRACELEVEL_MSGWITHPARAMS,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPrmWihIntMsgDescTable()
{
  /* PRM -> WIH Interface */
  initElementInMsgDescTable( MSG_PRM_WIH_EXIT_CMD,  MODID_PRM, MODID_WIH, sizeof(MsgPrmModExitCmd), DEFAULT_MAX_MSG_INST, printMsgExitCmd,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_WIH_HELLO,     MODID_PRM, MODID_WIH, sizeof(MsgPrmModHello),   DEFAULT_MAX_MSG_INST, printMsgHello,   MSGTRACELEVEL_MSGWITHPARAMS,  MSGTRACEDIRECTION_MSGINBOTHDIREC );
  /* WIH -> PRM Interface */
  initElementInMsgDescTable( MSG_WIH_PRM_HELLO_ACK, MODID_WIH, MODID_PRM, sizeof(MsgModPrmHelloAck),DEFAULT_MAX_MSG_INST, printMsgHelloAck,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_WIH_PRM_START_IND, MODID_WIH, MODID_PRM, sizeof(MsgStartInd),      DEFAULT_MAX_MSG_INST, printStartIndMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initLthRrcIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_LTH_SM_TRACE_START_REQ, MODID_LTH, MODID_SM, sizeof(MsgLthSmTraceCntrlReq), DEFAULT_MAX_MSG_INST, printMsgTraceCntrlReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_LTH_TRACE_START_SUCC, MODID_SM, MODID_LTH, sizeof(MsgSmLthTraceCntrlCfm), DEFAULT_MAX_MSG_INST, printMsgTraceCntrlCfm, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_LTH_SM_TRACE_STOP_REQ, MODID_LTH, MODID_SM, sizeof(MsgLthSmTraceCntrlReq), DEFAULT_MAX_MSG_INST, printMsgTraceCntrlReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_LTH_TRACE_STOP_SUCC, MODID_SM, MODID_LTH, sizeof(MsgSmLthTraceCntrlCfm), DEFAULT_MAX_MSG_INST, printMsgTraceCntrlCfm, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initLthS1apIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_LTH_SM_TRACE_START_REQ,        MODID_LTH, MODID_SM,   sizeof(MsgLthSmTraceCntrlReq), DEFAULT_MAX_MSG_INST, printMsgTraceCntrlReq,         MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_LTH_TRACE_START_SUCC,        MODID_SM,  MODID_LTH,  sizeof(MsgSmLthTraceCntrlCfm), DEFAULT_MAX_MSG_INST, printMsgTraceCntrlCfm,         MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_LTH_SM_TRACE_STOP_REQ,        MODID_LTH, MODID_SM,   sizeof(MsgLthSmTraceCntrlReq), DEFAULT_MAX_MSG_INST, printMsgTraceCntrlReq,         MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_LTH_TRACE_STOP_SUCC,        MODID_SM,  MODID_LTH,  sizeof(MsgSmLthTraceCntrlCfm), DEFAULT_MAX_MSG_INST, printMsgTraceCntrlCfm,         MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

}

static void initBsmS1apIntMsgDescTable()
{

  initElementInMsgDescTable( MSG_BSM_SM_S1AP_INIT_CONFIG_REQ,  MODID_BSM, MODID_SM,   sizeof(MsgBsmS1apInitConfigReq),     DEFAULT_MAX_MSG_INST, printMsgBsmS1apInitConfigReq,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_BSM_S1AP_INIT_CONFIG_SUCC, MODID_SM,  MODID_BSM,  sizeof(MsgS1apBsmInitConfigSucc),    DEFAULT_MAX_MSG_INST, printMsgEnbConfigSucc,          MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_BSM_S1AP_INIT_CONFIG_FAIL, MODID_SM,  MODID_BSM,  sizeof(MsgS1apBsmInitConfigFail),    DEFAULT_MAX_MSG_INST, printMsgEnbConfigFail,          MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initSctpBsmIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_BSM_SM_SCTP_INIT_CONFIG_REQ,  MODID_BSM, MODID_SM,  sizeof(MsgBsmSctpInitConfigReq),  DEFAULT_MAX_MSG_INST, printMsgBsmSctpInitConfigReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_BSM_SCTP_INIT_CONFIG_SUCC, MODID_SM, MODID_BSM,  sizeof(MsgSctpBsmInitConfigSucc), DEFAULT_MAX_MSG_INST, printMsgEnbConfigSucc,        MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_BSM_SCTP_INIT_CONFIG_FAIL, MODID_SM, MODID_BSM,  sizeof(MsgSctpBsmInitConfigFail), DEFAULT_MAX_MSG_INST, printMsgEnbConfigFail,        MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initBsmEgtpIntMsgDescTable()
{

  initElementInMsgDescTable( MSG_BSM_SM_EGTP_INIT_CONFIG_REQ,   MODID_BSM,  MODID_SM, sizeof(MsgBsmEgtpInitConfigReq),  DEFAULT_MAX_MSG_INST, printMsgBsmEgtpInitConfigReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_BSM_EGTP_INIT_CONFIG_SUCC,  MODID_SM, MODID_BSM,  sizeof(MsgEgtpBsmInitConfigSucc), DEFAULT_MAX_MSG_INST, printMsgEnbConfigSucc,        MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_BSM_EGTP_INIT_CONFIG_FAIL,  MODID_SM, MODID_BSM,  sizeof(MsgEgtpBsmInitConfigFail), DEFAULT_MAX_MSG_INST, printMsgEnbConfigFail,        MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initBsmPmhIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_BSM_PMH_GET_OBJ_REQ,  MODID_BSM, MODID_PMH, 0 /* encBuf.len*/, DEFAULT_MAX_MSG_INST, printGetObjReqMsg,     MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PMH_BSM_GET_OBJ_SUCC, MODID_PMH, MODID_BSM, 0 /* encBuf.len*/, DEFAULT_MAX_MSG_INST, printGetObjRspSuccMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PMH_BSM_GET_OBJ_FAIL, MODID_PMH, MODID_BSM, 0 /* encBuf.len*/, DEFAULT_MAX_MSG_INST, printGetObjRspFailMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_PMH_SET_OBJ_REQ,  MODID_BSM, MODID_PMH, 0 /* encBuf.len*/, DEFAULT_MAX_MSG_INST, printSetObjReqMsg,     MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PMH_BSM_SET_OBJ_SUCC, MODID_PMH, MODID_BSM, 0 /* encBuf.len*/, DEFAULT_MAX_MSG_INST, printSetObjRspSuccMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PMH_BSM_SET_OBJ_FAIL, MODID_PMH, MODID_BSM, 0 /* encBuf.len*/, DEFAULT_MAX_MSG_INST, printSetObjRspFailMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_PMH_BSM_COUNTER_FILE_AVAILABLE,    MODID_PMH, MODID_BSM, sizeof(MsgPmhBsmCntrFileAvailable),      DEFAULT_MAX_MSG_INST, printCntrFileAvailableMsg,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PMH_BSM_COUNTER_COLLECTION_FAILED, MODID_PMH, MODID_BSM, sizeof(MsgPmhBsmCntrCollectFail),        DEFAULT_MAX_MSG_INST, printCntrCollectionFailMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_PMH_PM_FILE_UPLOADED,          MODID_BSM, MODID_PMH, sizeof(MsgBsmPmhPmFileUploaded),         DEFAULT_MAX_MSG_INST, printCntrFileUploadedMsg,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PMH_BSM_MEASUREMENT_CMPL_IND,      MODID_PMH, MODID_BSM, sizeof(MsgPmhBsmMeasurementCompleteInd), DEFAULT_MAX_MSG_INST, printMsgPmhBsmMeasurementCompleteInd, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  /* PMH Configuration */
  initElementInMsgDescTable( MSG_BSM_PMH_CONFIG_REQ,  MODID_BSM, MODID_PMH, sizeof(MsgBsmPmhConfigReq),  DEFAULT_MAX_MSG_INST, printMsgBsmPmhConfigReq,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PMH_BSM_CONFIG_SUCC, MODID_PMH, MODID_BSM, sizeof(MsgPmhBsmConfigSucc), DEFAULT_MAX_MSG_INST, printMsgEnbConfigSucc,    MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PMH_BSM_CONFIG_FAIL, MODID_PMH, MODID_BSM, sizeof(MsgPmhBsmConfigFail), DEFAULT_MAX_MSG_INST, printMsgEnbConfigFail,    MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  /* PMH Counter Input Configuration */
  initElementInMsgDescTable( MSG_BSM_PMH_COUNTER_INPUT_CONFIG_REQ,  MODID_BSM, MODID_PMH, sizeof(MsgBsmPmhCntrInputConfigReq),  DEFAULT_MAX_MSG_INST, printMsgBsmPmhCntrInputConfigReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PMH_BSM_COUNTER_INPUT_CONFIG_SUCC, MODID_PMH, MODID_BSM, sizeof(MsgPmhBsmCntrInputConfigSucc), DEFAULT_MAX_MSG_INST, printMsgEnbConfigSucc,            MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PMH_BSM_COUNTER_INPUT_CONFIG_FAIL, MODID_PMH, MODID_BSM, sizeof(MsgPmhBsmCntrInputConfigFail), DEFAULT_MAX_MSG_INST, printMsgEnbConfigFail,            MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  /* HAndling OPSTART message */
  initElementInMsgDescTable( MSG_BSM_PMH_OPSTART_REQ,  MODID_BSM, MODID_PMH, 0,                               DEFAULT_MAX_MSG_INST, NULL,                      MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PMH_BSM_OPSTART_SUCC, MODID_PMH, MODID_BSM, 0,                               DEFAULT_MAX_MSG_INST, NULL,                      MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PMH_BSM_OPSTART_FAIL, MODID_PMH, MODID_BSM, sizeof(OpStartFail),             DEFAULT_MAX_MSG_INST, printMsgOpStartFail,       MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  /* HAndling OPSTOP message */
  initElementInMsgDescTable( MSG_BSM_PMH_OPSTOP_REQ,  MODID_BSM, MODID_PMH, sizeof(MsgBsmModOpStopReq),       DEFAULT_MAX_MSG_INST, printMsgOpStopReq,         MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PMH_BSM_OPSTOP_SUCC, MODID_PMH, MODID_BSM, 0,                                DEFAULT_MAX_MSG_INST, NULL,                      MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_PMH_COUNTER_CLEAR_REQ,  MODID_BSM, MODID_PMH, sizeof(MsgBsmPmhCounterClearReq),  DEFAULT_MAX_MSG_INST, printMsgCounterClearReq,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PMH_BSM_COUNTER_CLEAR_SUCC, MODID_PMH, MODID_BSM, sizeof(MsgPmhBsmCounterClearSucc), DEFAULT_MAX_MSG_INST, printMsgCounterClearSucc, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PMH_BSM_COUNTER_CLEAR_FAIL, MODID_PMH, MODID_BSM, sizeof(MsgPmhBsmCounterClearFail), DEFAULT_MAX_MSG_INST, printMsgCounterClearFail, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_PMH_DIAG_COUNTER_CMD,      MODID_BSM, MODID_PMH, sizeof(MsgBsmPmhDiagCounterCmd),    DEFAULT_MAX_MSG_INST, printMsgBsmPmhDiagCounterCmd,    MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PMH_BSM_DIAG_COUNTER_CMD_CMPL, MODID_PMH, MODID_BSM, sizeof(MsgPmhBsmDiagCounterCmdRsp), DEFAULT_MAX_MSG_INST, printMsgPmhBsmDiagCounterCmdRsp, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  /* Message for log level change */
  initElementInMsgDescTable( MSG_BSM_PMH_SET_LOG_CFG,  MODID_BSM, MODID_PMH, sizeof(MsgBsmPmhSetLogCfg), DEFAULT_MAX_MSG_INST, PrintMsgSetLogConfig, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

}



static void initLthRlcIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_LTH_SM_TRACE_START_REQ, MODID_LTH, MODID_SM, sizeof(MsgLthSmTraceCntrlReq), DEFAULT_MAX_MSG_INST, printMsgTraceCntrlReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_LTH_TRACE_START_SUCC, MODID_SM, MODID_LTH, sizeof(MsgSmLthTraceCntrlCfm), DEFAULT_MAX_MSG_INST, printMsgTraceCntrlCfm, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_LTH_SM_TRACE_STOP_REQ, MODID_LTH, MODID_SM, sizeof(MsgLthSmTraceCntrlReq), DEFAULT_MAX_MSG_INST, printMsgTraceCntrlReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_LTH_TRACE_STOP_SUCC, MODID_SM, MODID_LTH, sizeof(MsgSmLthTraceCntrlCfm), DEFAULT_MAX_MSG_INST, printMsgTraceCntrlCfm, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}


static void initLthPdcpIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_LTH_SM_TRACE_START_REQ, MODID_LTH, MODID_SM, sizeof(MsgLthSmTraceCntrlReq), DEFAULT_MAX_MSG_INST, printMsgTraceCntrlReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_LTH_TRACE_START_SUCC, MODID_SM, MODID_LTH, sizeof(MsgSmLthTraceCntrlCfm), DEFAULT_MAX_MSG_INST, printMsgTraceCntrlCfm, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_LTH_SM_TRACE_STOP_REQ, MODID_LTH, MODID_SM, sizeof(MsgLthSmTraceCntrlReq), DEFAULT_MAX_MSG_INST, printMsgTraceCntrlReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_LTH_TRACE_STOP_SUCC, MODID_SM, MODID_LTH, sizeof(MsgSmLthTraceCntrlCfm), DEFAULT_MAX_MSG_INST, printMsgTraceCntrlCfm, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPrmLthIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_LTH_PRM_START_IND, MODID_LTH, MODID_PRM, sizeof(MsgStartInd),      DEFAULT_MAX_MSG_INST, printStartIndMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_LTH_HELLO,     MODID_PRM, MODID_LTH, sizeof(MsgPrmModHello),   DEFAULT_MAX_MSG_INST, printMsgHello,    MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_LTH_PRM_HELLO_ACK, MODID_LTH, MODID_PRM, sizeof(MsgModPrmHelloAck),DEFAULT_MAX_MSG_INST, printMsgHelloAck, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_LTH_EXIT_CMD,  MODID_PRM, MODID_LTH, sizeof(MsgPrmModExitCmd), DEFAULT_MAX_MSG_INST, printMsgExitCmd,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPrmPmhIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PMH_PRM_START_IND, MODID_PMH, MODID_PRM, sizeof(MsgStartInd),      DEFAULT_MAX_MSG_INST, printStartIndMsg,MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_PMH_HELLO,     MODID_PRM, MODID_PMH, sizeof(MsgPrmModHello),   DEFAULT_MAX_MSG_INST, printMsgHello,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PMH_PRM_HELLO_ACK, MODID_PMH, MODID_PRM, sizeof(MsgModPrmHelloAck),DEFAULT_MAX_MSG_INST, printMsgHelloAck,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_PMH_EXIT_CMD,  MODID_PRM, MODID_PMH, sizeof(MsgPrmModExitCmd), DEFAULT_MAX_MSG_INST, printMsgExitCmd, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPrmUdhIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_UDH_PRM_START_IND, MODID_UDH, MODID_PRM, sizeof(MsgStartInd),      DEFAULT_MAX_MSG_INST, printStartIndMsg,MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_UDH_HELLO,     MODID_PRM, MODID_UDH, sizeof(MsgPrmModHello),   DEFAULT_MAX_MSG_INST, printMsgHello,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UDH_PRM_HELLO_ACK, MODID_UDH, MODID_PRM, sizeof(MsgModPrmHelloAck),DEFAULT_MAX_MSG_INST, printMsgHelloAck,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_UDH_EXIT_CMD,  MODID_PRM, MODID_UDH, sizeof(MsgPrmModExitCmd), DEFAULT_MAX_MSG_INST, printMsgExitCmd, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}
static void initBsmUdhIntMsgDescTable()
{
  /* HAndling OPSTOP message */
  initElementInMsgDescTable( MSG_BSM_UDH_OPSTOP_REQ,  MODID_BSM, MODID_UDH, sizeof(MsgBsmModOpStopReq),       DEFAULT_MAX_MSG_INST, printMsgOpStopReq,         MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UDH_BSM_OPSTOP_SUCC, MODID_UDH, MODID_BSM, 0,                                DEFAULT_MAX_MSG_INST, NULL,                      MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  /* HAndling OPSTART message */
  initElementInMsgDescTable( MSG_BSM_UDH_OPSTART_REQ,  MODID_BSM, MODID_UDH, 0,                               DEFAULT_MAX_MSG_INST, NULL,                      MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UDH_BSM_OPSTART_SUCC, MODID_UDH, MODID_BSM, 0,                               DEFAULT_MAX_MSG_INST, NULL,                      MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UDH_BSM_OPSTART_FAIL, MODID_UDH, MODID_BSM, sizeof(OpStartFail),             DEFAULT_MAX_MSG_INST, printMsgOpStartFail,       MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  /* UDH Configuration */
  initElementInMsgDescTable( MSG_BSM_UDH_CONFIG_REQ,  MODID_BSM, MODID_UDH, sizeof(MsgBsmUdhCfgReq),  DEFAULT_MAX_MSG_INST, printMsgBsmUdhCfgReq,     MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UDH_BSM_CONFIG_SUCC, MODID_UDH, MODID_BSM, sizeof(MsgUdhBsmCfgSucc), DEFAULT_MAX_MSG_INST, printMsgEnbConfigSucc,    MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_UDH_GET_ACTIVE_RAB_STATUS_REQ,  MODID_BSM, MODID_UDH, sizeof(MsgBsmUdhActiveRabStatusReq),DEFAULT_MAX_MSG_INST, printMsgActiveRabStatusReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UDH_BSM_GET_ACTIVE_RAB_STATUS_RSP,  MODID_UDH, MODID_BSM, sizeof(MsgUdhBsmActiveRabStatusRsp),DEFAULT_MAX_MSG_INST, printMsgActiveRabStatusRsp, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_UDH_GET_RAB_HISTORY_REQ,   MODID_BSM, MODID_UDH, sizeof(MsgBsmUdhRabHistoryReq),     DEFAULT_MAX_MSG_INST, printMsgBsmUdhRabHistoryReq,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UDH_BSM_GET_RAB_HISTORY_RSP,   MODID_UDH, MODID_BSM, sizeof(MsgUdhBsmRabHistoryRsp),     DEFAULT_MAX_MSG_INST, printMsgUdhBsmRabHistoryRsp,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_UDH_MOD_STATE_REQ,  MODID_BSM, MODID_UDH, sizeof(MsgBsmUdhModStateReq),DEFAULT_MAX_MSG_INST, printMsgBsmUdhModStateReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UDH_BSM_MOD_STATE_RSP,  MODID_UDH, MODID_BSM, sizeof(MsgUdhBsmModStateRsp),DEFAULT_MAX_MSG_INST, printMsgUdhBsmModStateRsp, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

}
static void initLthBsmIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_LTH_BSM_SET_OBJ_SUCC, MODID_LTH, MODID_BSM, 0,                               DEFAULT_MAX_MSG_INST, NULL,                        MSGTRACELEVEL_MSGIDONLY,      MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_LTH_BSM_SET_OBJ_FAIL, MODID_LTH, MODID_BSM, sizeof(MsgLthBsmStartTraceFail), DEFAULT_MAX_MSG_INST, NULL,   MSGTRACELEVEL_MSGWITHPARAMS,  MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_LTH_SET_OBJ_REQ,  MODID_BSM, MODID_LTH, 0, DEFAULT_MAX_MSG_INST, printMsgBsmLthStartTraceReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_LTH_GET_OBJ_REQ,  MODID_BSM, MODID_LTH, 0, DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_LTH_BSM_GET_OBJ_SUCC,  MODID_LTH, MODID_BSM, 0, DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_LTH_INIT_CONFIG_REQ,  MODID_BSM, MODID_LTH, 0, DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_LTH_BSM_INIT_CONFIG_SUCC,  MODID_LTH, MODID_BSM, 0, DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_LTH_BSM_INIT_CONFIG_FAIL,  MODID_LTH, MODID_BSM, 0, DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  /* Message for log level change */
  initElementInMsgDescTable( MSG_BSM_LTH_SET_LOG_CFG, MODID_BSM, MODID_LTH, sizeof(MsgBsmLthSetLogCfg), DEFAULT_MAX_MSG_INST, PrintMsgSetLogConfig, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPdcpLthIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_SM_LTH_TRACE_IND, MODID_SM, MODID_LTH, 0, DEFAULT_MAX_MSG_INST, printMsgTraceInd , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPmhPdcpIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PMH_SM_PDCP_GEN_STAT_REQ, MODID_PMH, MODID_SM, sizeof(MsgPmhSmPdcpGenStatReq), DEFAULT_MAX_MSG_INST, printMsgPmhSmPdcpGenStatReq,  MSGTRACELEVEL_MSGWITHPARAMS,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_PMH_PDCP_GEN_STAT_RSP, MODID_SM, MODID_PMH, sizeof(MsgSmPmhPdcpGenStatRsp), DEFAULT_MAX_MSG_INST, printMsgSmPmhPdcpGenStatRsp , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_PMH_SM_PDCP_UPLANE_STAT_REQ, MODID_PMH,  MODID_SM, sizeof(MsgPmhSmPdcpUplaneStatReq), DEFAULT_MAX_MSG_INST, printMsgPmhSmPdcpUplaneStatReq, MSGTRACELEVEL_MSGWITHPARAMS,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_PMH_PDCP_UPLANE_STAT_RSP, MODID_SM, MODID_PMH,  sizeof(MsgSmPmhPdcpUplaneStatRsp), DEFAULT_MAX_MSG_INST, printMsgSmPmhPdcpUplaneStatRsp, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPmhGtpIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PMH_SM_EGTP_GEN_STAT_REQ, MODID_PMH,  MODID_SM, sizeof(MsgPmhSmGtpGenStatReq),DEFAULT_MAX_MSG_INST, printMsgPmhGtpGenStatReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_PMH_EGTP_GEN_STAT_RSP, MODID_SM, MODID_PMH, sizeof(MsgSmPmhGtpGenStatRsp), DEFAULT_MAX_MSG_INST, printMsgGtpPmhGenStatRsp, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPmhRlcIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PMH_SM_RLC_GEN_STAT_REQ, MODID_PMH, MODID_SM, sizeof(MsgPmhSmRlcGenStatReq), DEFAULT_MAX_MSG_INST, printMsgPmhSmRlcGenStatReq , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_PMH_RLC_GEN_STAT_RSP, MODID_SM, MODID_PMH, sizeof(MsgSmPmhRlcGenStatRsp), DEFAULT_MAX_MSG_INST, printMsgSmPmhRlcGenStatRsp , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPmhSctpIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PMH_SM_SCTP_GEN_STAT_REQ, MODID_PMH, MODID_SM, sizeof(MsgPmhSmSctpGenStatReq), DEFAULT_MAX_MSG_INST, printMsgPmhSmSctpGenStatReq , MSGTRACELEVEL_MSGWITHPARAMS,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_PMH_SCTP_GEN_STAT_RSP, MODID_SM, MODID_PMH, sizeof(MsgSmPmhSctpGenStatRsp), DEFAULT_MAX_MSG_INST, printMsgSmPmhSctpGenStatRsp , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPmhRrcIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PMH_SM_RRC_GEN_STAT_REQ, MODID_PMH, MODID_SM, sizeof(MsgPmhSmRrcGenStatReq),   DEFAULT_MAX_MSG_INST, printMsgPmhSmRrcGenStatReq ,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_PMH_RRC_GEN_STAT_RSP, MODID_SM, MODID_PMH, sizeof(MsgSmPmhRrcGenStatRsp),   DEFAULT_MAX_MSG_INST, printMsgSmPmhRrcGenStatRsp ,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_PMH_SM_RRC_CELL_STAT_REQ, MODID_PMH, MODID_SM,  sizeof(MsgPmhSmRrcCellStatReq), DEFAULT_MAX_MSG_INST, printMsgPmhSmRrcCellStatReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_PMH_RRC_CELL_STAT_RSP, MODID_SM,  MODID_PMH, sizeof(MsgSmPmhRrcCellStatRsp), DEFAULT_MAX_MSG_INST, printMsgRrcPmhCellStatRsp, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  }

static void initMacPmhIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PMH_SM_MAC_GEN_STAT_REQ, MODID_PMH, MODID_SM, sizeof(MsgPmhSmMacGenStatReq), DEFAULT_MAX_MSG_INST, printMsgPmhSmMacGenStatReq , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_PMH_MAC_GEN_STAT_RSP, MODID_SM, MODID_PMH, sizeof(MsgSmPmhMacGenStatRsp), DEFAULT_MAX_MSG_INST, printMsgSmPmhMacGenStatRsp,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_PMH_SM_MAC_RLCSAP_STAT_REQ, MODID_PMH, MODID_SM, sizeof(MsgPmhSmMacRlcsapStatReq), DEFAULT_MAX_MSG_INST, printMsgPmhSmMacRlcsapStatReq , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_PMH_MAC_RLCSAP_STAT_RSP, MODID_SM, MODID_PMH, sizeof(MsgSmPmhMacRlcsapStatRsp), DEFAULT_MAX_MSG_INST, printMsgSmPmhMacRlcsapStatRsp , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_PMH_SM_MAC_PHYSAP_STAT_REQ, MODID_PMH, MODID_SM, sizeof(MsgPmhSmMacPhysapStatReq), DEFAULT_MAX_MSG_INST, printMsgPmhSmMacPhysapStatReq , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_PMH_MAC_PHYSAP_STAT_RSP, MODID_SM, MODID_PMH, sizeof(MsgSmPmhMacPhysapStatRsp), DEFAULT_MAX_MSG_INST, printMsgSmPmhMacPhysapStatRsp , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initS1apPmhIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PMH_SM_S1AP_GEN_STAT_REQ, MODID_PMH,  MODID_SM, sizeof(MsgPmhSmS1apGenStatReq), DEFAULT_MAX_MSG_INST, printMsgPmhSmS1apGenStatReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_PMH_S1AP_GEN_STAT_RSP, MODID_SM, MODID_PMH,  sizeof(MsgSmPmhS1apGenStatRsp), DEFAULT_MAX_MSG_INST, printMsgSmPmhS1apGenStatRsp, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_PMH_SM_S1AP_PEER_NODE_STAT_REQ, MODID_PMH,  MODID_SM, sizeof(MsgPmhSmS1apPeerNodeStatReq), DEFAULT_MAX_MSG_INST, printMsgPmhSmS1apPeerNodeStatReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SM_PMH_S1AP_PEER_NODE_STAT_RSP, MODID_SM, MODID_PMH,  sizeof(MsgSmPmhS1apPeerNodeStatRsp), DEFAULT_MAX_MSG_INST, printMsgSmPmhS1apPeerNodeStatRsp, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

}

static void initUehPmhIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PMH_UEH_RRM_STAT_REQ, MODID_PMH, MODID_UEH, sizeof(MsgPmhUehRrmStatReq), DEFAULT_MAX_MSG_INST, printMsgPmhUehRrmStatReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UEH_PMH_RRM_STAT_RSP, MODID_UEH, MODID_PMH, sizeof(MsgUehPmhRrmStatRsp), DEFAULT_MAX_MSG_INST, printMsgUehPmhRrmStatRsp, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_PMH_UEH_COUNTER_START_REQ, MODID_PMH, MODID_UEH, sizeof(MsgPmhUehCounterStartReq), DEFAULT_MAX_MSG_INST, printMsgPmhUehCounterStartReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UEH_PMH_COUNTER_START_SUCC, MODID_UEH, MODID_PMH, sizeof(MsgUehPmhCounterStartSucc), DEFAULT_MAX_MSG_INST, printMsgUehPmhCounterStartSucc, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UEH_PMH_COUNTER_START_FAIL, MODID_UEH, MODID_PMH, sizeof(MsgUehPmhCounterStartFail), DEFAULT_MAX_MSG_INST, printMsgUehPmhCounterStartFail, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_PMH_UEH_COUNTER_STOP_REQ, MODID_PMH, MODID_UEH, sizeof(MsgPmhUehCounterStopReq), DEFAULT_MAX_MSG_INST, printMsgPmhUehCounterStopReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UEH_PMH_COUNTER_STOP_SUCC, MODID_UEH, MODID_PMH, sizeof(MsgUehPmhCounterStopSucc), DEFAULT_MAX_MSG_INST, printMsgUehPmhCounterStopSucc, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_UEH_PMH_COUNTER_REPORT_IND, MODID_UEH, MODID_PMH, sizeof(MsgUehPmhCounterReportInd), DEFAULT_MAX_MSG_INST, printMsgUehPmhCounterReportInd, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UEH_PMH_COUNTER_STOP_IND, MODID_UEH, MODID_PMH, sizeof(MsgUehPmhCounterStopInd), DEFAULT_MAX_MSG_INST, printMsgUehPmhCounterStopInd, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initUdhPmhIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PMH_UDH_DSTATS_REQ, MODID_PMH, MODID_UDH, sizeof(MsgPmhUdhDStatsCfgReq), DEFAULT_MAX_MSG_INST, printMsgPmhUdhDStatReq, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_UDH_PMH_DSTATS_IND, MODID_UDH, MODID_PMH, sizeof(MsgUdhPmhDStatsInd), DEFAULT_MAX_MSG_INST, printMsgUdhPmhDStatInd, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initRlcLthIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_SM_LTH_TRACE_IND, MODID_SM, MODID_LTH, 0, DEFAULT_MAX_MSG_INST, printMsgTraceInd , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initMacLthIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_SM_LTH_TRACE_IND, MODID_SM, MODID_LTH, 0, DEFAULT_MAX_MSG_INST, printMsgTraceInd , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initRrcLthIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_SM_LTH_TRACE_IND, MODID_SM, MODID_LTH, 0, DEFAULT_MAX_MSG_INST, printMsgTraceInd , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initS1apLthIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_SM_LTH_TRACE_IND, MODID_SM, MODID_LTH, 0, DEFAULT_MAX_MSG_INST, printMsgTraceInd , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initEgtpLthIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_SM_LTH_TRACE_IND, MODID_EGTP, MODID_LTH, 0, DEFAULT_MAX_MSG_INST, printMsgTraceInd , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initBsmFthIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_BSM_FTH_SET_LOG_CFG,        MODID_BSM, MODID_FTH, sizeof(MsgBsmFthSetLogCfg),DEFAULT_MAX_MSG_INST, PrintMsgSetLogConfig, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_FTH_SET_MSG_TRACE,      MODID_BSM, MODID_FTH, sizeof(MsgTrace),                 DEFAULT_MAX_MSG_INST, printMsgSetMsgTrace,             MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_FTH_GET_OBJ_REQ,        MODID_BSM, MODID_FTH, 0 /* encBuf.len*/,                DEFAULT_MAX_MSG_INST, printGetObjReqMsg,               MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_FTH_BSM_GET_OBJ_SUCC,       MODID_FTH, MODID_BSM, 0 /* encBuf.len*/,                DEFAULT_MAX_MSG_INST, printGetObjRspSuccMsg,           MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_FTH_SET_OBJ_REQ,        MODID_BSM, MODID_FTH, 0 /* encBuf.len*/,                DEFAULT_MAX_MSG_INST, printSetObjReqMsg,               MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_FTH_BSM_SET_OBJ_SUCC,       MODID_FTH, MODID_BSM, 0 /* encBuf.len*/,                DEFAULT_MAX_MSG_INST, printSetObjRspSuccMsg,           MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_FTH_BSM_SET_OBJ_FAIL,       MODID_FTH, MODID_BSM, 0 /* encBuf.len*/,                DEFAULT_MAX_MSG_INST, printSetObjRspFailMsg,           MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_FTH_BSM_DOWNLOAD_CMPL_IND,  MODID_FTH, MODID_BSM, sizeof(MsgFthBsmDownloadCmpInd),  DEFAULT_MAX_MSG_INST, printMsgFthBsmSwDownloadCmpInd,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_FTH_BSM_DOWNLOAD_FAIL,      MODID_FTH, MODID_BSM, sizeof(MsgFthBsmDownloadFail),    DEFAULT_MAX_MSG_INST, printMsgFthBsmSwDownloadFail,    MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_FTH_BSM_UPLOAD_CMPL_IND,    MODID_FTH, MODID_BSM, sizeof(MsgFthBsmUploadCmpInd),    DEFAULT_MAX_MSG_INST, printMsgFthBsmSwUploadCmpInd,    MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_FTH_BSM_UPLOAD_FAIL,        MODID_FTH, MODID_BSM, sizeof(MsgFthBsmUploadFail),      DEFAULT_MAX_MSG_INST, printMsgFthBsmSwUploadFail,      MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initBsmDehIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_BSM_DEH_SET_LED_COLOR,         MODID_BSM, MODID_DEH, sizeof(MsgBsmDehSetLedColor),    DEFAULT_MAX_MSG_INST, printMsgSetDeviceColor,       MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_DEH_GET_ENB_ADDR_REQ,   MODID_BSM, MODID_DEH, sizeof(MsgBsmDehGetEnbAddrReq),  DEFAULT_MAX_MSG_INST, printMsgBsmDehGetEnbAddrReq,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_GET_ENB_ADDR_RSP,   MODID_DEH, MODID_BSM, sizeof(MsgDehBsmGetEnbAddrRsp),  DEFAULT_MAX_MSG_INST, printMsgDehBsmGetEnbAddrRsp,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_GET_ENB_ADDR_FAIL,  MODID_DEH, MODID_BSM, sizeof(MsgDehBsmGetEnbAddrFail), DEFAULT_MAX_MSG_INST, printMsgDehBsmGetEnbAddrFail, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );


  initElementInMsgDescTable( MSG_DEH_BSM_COMPONENT_DOWN_IND,  MODID_DEH, MODID_BSM, sizeof(MsgDehBsmComponentDownInd),DEFAULT_MAX_MSG_INST, printMsgDehBsmComponentDownInd,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_COMPONENT_UP_IND,  MODID_DEH, MODID_BSM,   sizeof(MsgDehBsmComponentUpInd),  DEFAULT_MAX_MSG_INST, printMsgDehBsmComponentUpInd,    MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_DEH_DEVICE_INIT_REQ, MODID_BSM, MODID_DEH, 0,                               DEFAULT_MAX_MSG_INST, NULL,                      MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_DEVICE_INIT_SUCC,MODID_DEH, MODID_BSM, sizeof(MsgDehBsmDeviceInitSucc), DEFAULT_MAX_MSG_INST, printMsgDeviceInitSucc,    MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_DEVICE_INIT_FAIL,MODID_DEH, MODID_BSM, sizeof(MsgDehBsmDeviceInitFail), DEFAULT_MAX_MSG_INST, printMsgDeviceInitFail,    MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_DEH_OPSTART_REQ,  MODID_BSM, MODID_DEH, 0,                               DEFAULT_MAX_MSG_INST, NULL,                      MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_OPSTART_SUCC, MODID_DEH, MODID_BSM, 0,                               DEFAULT_MAX_MSG_INST, NULL,                      MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_OPSTART_FAIL, MODID_DEH, MODID_BSM, sizeof(OpStartFail),             DEFAULT_MAX_MSG_INST, printMsgOpStartFail,       MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_DEH_OPSTOP_REQ,  MODID_BSM, MODID_DEH, sizeof(MsgBsmModOpStopReq),       DEFAULT_MAX_MSG_INST, printMsgOpStopReq,         MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_OPSTOP_SUCC, MODID_DEH, MODID_BSM, 0,                                DEFAULT_MAX_MSG_INST, NULL,                      MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );

  /*BSM-DEH Get Request message Interface*/
  initElementInMsgDescTable( MSG_BSM_DEH_GET_OBJ_REQ,  MODID_BSM, MODID_DEH, 0 /* encBuf.len*/,               DEFAULT_MAX_MSG_INST, printGetObjReqMsg,         MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_GET_OBJ_SUCC, MODID_DEH, MODID_BSM, 0 /* encBuf.len*/,               DEFAULT_MAX_MSG_INST, printGetObjRspSuccMsg,     MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_GET_OBJ_FAIL, MODID_DEH, MODID_BSM, 0 /* encBuf.len*/,               DEFAULT_MAX_MSG_INST, printGetObjRspFailMsg,     MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  /*BSM-DEH Set Request message Interface*/
  initElementInMsgDescTable( MSG_BSM_DEH_SET_OBJ_REQ,  MODID_BSM, MODID_DEH, 0 /* encBuf.len*/,               DEFAULT_MAX_MSG_INST, printSetObjReqMsg,         MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_SET_OBJ_SUCC, MODID_DEH, MODID_BSM, 0 /* encBuf.len*/,               DEFAULT_MAX_MSG_INST, printSetObjRspSuccMsg,     MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_SET_OBJ_FAIL, MODID_DEH, MODID_BSM, 0 /* encBuf.len*/,               DEFAULT_MAX_MSG_INST, printSetObjRspFailMsg,     MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  /* Radio Head(LK) Init Configuration */
  initElementInMsgDescTable( MSG_BSM_DEH_INIT_CONFIG_REQ,  MODID_BSM, MODID_DEH, sizeof(MsgBsmDehRhInitConfigReq),  DEFAULT_MAX_MSG_INST, printMsgBsmDehRhConfigReq,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_INIT_CONFIG_SUCC, MODID_DEH, MODID_BSM, sizeof(MsgDehBsmRhInitConfigSucc), DEFAULT_MAX_MSG_INST, printMsgEnbConfigSucc,      MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_INIT_CONFIG_FAIL, MODID_DEH, MODID_BSM, sizeof(MsgDehBsmRhInitConfigFail), DEFAULT_MAX_MSG_INST, printMsgEnbConfigFail,      MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  /* Radio Head(LK) Configuration */
  initElementInMsgDescTable( MSG_BSM_DEH_RH_CONFIG_REQ,  MODID_BSM, MODID_DEH, sizeof(MsgBsmDehRhConfigReq),  DEFAULT_MAX_MSG_INST, printMsgBsmDehRhConfigReq,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_RH_CONFIG_SUCC, MODID_DEH, MODID_BSM, sizeof(MsgDehBsmRhConfigSucc), DEFAULT_MAX_MSG_INST, printMsgEnbConfigSucc,      MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_RH_CONFIG_FAIL, MODID_DEH, MODID_BSM, sizeof(MsgDehBsmRhConfigFail), DEFAULT_MAX_MSG_INST, printMsgEnbConfigFail,      MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  /* GPS detail */
  initElementInMsgDescTable( MSG_BSM_DEH_GPS_DETAIL_REQ,  MODID_BSM, MODID_DEH, 0,                               DEFAULT_MAX_MSG_INST, NULL,                       MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_GPS_DETAIL_SUCC, MODID_DEH, MODID_BSM, sizeof(MsgDehBsmGpsDetailSucc),  DEFAULT_MAX_MSG_INST, printMsgDehBsmGpsDetSucc,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_GPS_DETAIL_FAIL, MODID_DEH, MODID_BSM, sizeof(MsgDehBsmGpsDetailFail),  DEFAULT_MAX_MSG_INST, printMsgDehBsmGpsDetFail,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_DEH_SET_MSG_TRACE,    MODID_BSM, MODID_DEH, sizeof(MsgTrace),              DEFAULT_MAX_MSG_INST, printMsgSetMsgTrace,        MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_DEH_RH_RECONFIG_IND,  MODID_BSM, MODID_DEH, 0,                             DEFAULT_MAX_MSG_INST, NULL,                       MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  /* Message for Log level change */
  initElementInMsgDescTable( MSG_BSM_DEH_SET_LOG_CFG,  MODID_BSM, MODID_DEH, sizeof(MsgBsmDehSetLogCfg), DEFAULT_MAX_MSG_INST, PrintMsgSetLogConfig, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_DEH_SET_IP_ADDR_REQ, MODID_BSM, MODID_DEH, sizeof(MsgBsmDehSetIpAddrReq), DEFAULT_MAX_MSG_INST, printMsgBsmDehSetIpAddrReq,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_DEH_BSM_SET_IP_ADDR_RSP, MODID_DEH, MODID_BSM, sizeof(MsgDehBsmSetIpAddrRsp), DEFAULT_MAX_MSG_INST, printMsgDehBsmSetIpAddrRsp,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

}

static void initCih1IntMsgDescTable()
{
  /* CIH Specific Timeout Response Message */
  initElementInMsgDescTable( MSG_TIMEKEEPER_CIH1_TIMEOUT_IND, MODID_CIH1, MODID_CIH1, sizeof(MsgTimeoutInd), DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC  );
}

static void initCih2IntMsgDescTable()
{
  /* CIH Specific Timeout Response Message */
  initElementInMsgDescTable( MSG_TIMEKEEPER_CIH2_TIMEOUT_IND, MODID_CIH2, MODID_CIH2, sizeof(MsgTimeoutInd), DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC  );
}

static void initCih3IntMsgDescTable()
{
  /* CIH Specific Timeout Response Message */
  initElementInMsgDescTable( MSG_TIMEKEEPER_CIH3_TIMEOUT_IND, MODID_CIH3, MODID_CIH3, sizeof(MsgTimeoutInd), DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC  );
}
static void initBsmCihIntMsgDescTable()
{
  /* CLI - BSM Interface */
  initElementInMsgDescTable( MSG_CIH1_BSM_SET_OBJ_REQ,   MODID_CIH1, MODID_BSM, 0 /* encBuf.len*/,  DEFAULT_MAX_MSG_INST, printSetObjReqMsg,     MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_CIH2_BSM_SET_OBJ_REQ,   MODID_CIH2, MODID_BSM, 0 /* encBuf.len*/,  DEFAULT_MAX_MSG_INST, printSetObjReqMsg,     MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_CIH3_BSM_SET_OBJ_REQ,   MODID_CIH3, MODID_BSM, 0 /* encBuf.len*/,  DEFAULT_MAX_MSG_INST, printSetObjReqMsg,     MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_CIH1_BSM_GET_OBJ_REQ,   MODID_CIH1, MODID_BSM, 0 /* encBuf.len*/,  DEFAULT_MAX_MSG_INST, printGetObjReqMsg,     MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_CIH2_BSM_GET_OBJ_REQ,   MODID_CIH2, MODID_BSM, 0 /* encBuf.len*/,  DEFAULT_MAX_MSG_INST, printGetObjReqMsg,     MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_CIH3_BSM_GET_OBJ_REQ,   MODID_CIH3, MODID_BSM, 0 /* encBuf.len*/,  DEFAULT_MAX_MSG_INST, printGetObjReqMsg,     MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_CIH1_SET_OBJ_SUCC,  MODID_BSM, MODID_CIH1, 0 /* encBuf.len*/,  DEFAULT_MAX_MSG_INST, printSetObjRspSuccMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_CIH2_SET_OBJ_SUCC,  MODID_BSM, MODID_CIH2, 0 /* encBuf.len*/,  DEFAULT_MAX_MSG_INST, printSetObjRspSuccMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_CIH3_SET_OBJ_SUCC,  MODID_BSM, MODID_CIH3, 0 /* encBuf.len*/,  DEFAULT_MAX_MSG_INST, printSetObjRspSuccMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_CIH1_SET_OBJ_FAIL,  MODID_BSM, MODID_CIH1, 0 /* encBuf.len*/,  DEFAULT_MAX_MSG_INST, printSetObjRspFailMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_CIH2_SET_OBJ_FAIL,  MODID_BSM, MODID_CIH2, 0 /* encBuf.len*/,  DEFAULT_MAX_MSG_INST, printSetObjRspFailMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_CIH3_SET_OBJ_FAIL,  MODID_BSM, MODID_CIH3, 0 /* encBuf.len*/,  DEFAULT_MAX_MSG_INST, printSetObjRspFailMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_CIH1_GET_OBJ_SUCC,  MODID_BSM, MODID_CIH1, 0 /* encBuf.len*/,  DEFAULT_MAX_MSG_INST, printGetObjRspSuccMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_CIH2_GET_OBJ_SUCC,  MODID_BSM, MODID_CIH2, 0 /* encBuf.len*/,  DEFAULT_MAX_MSG_INST, printGetObjRspSuccMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_CIH3_GET_OBJ_SUCC,  MODID_BSM, MODID_CIH3, 0 /* encBuf.len*/,  DEFAULT_MAX_MSG_INST, printGetObjRspSuccMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_CIH1_GET_OBJ_FAIL,  MODID_BSM, MODID_CIH1, 0 /* encBuf.len*/,  DEFAULT_MAX_MSG_INST, printGetObjRspFailMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_CIH2_GET_OBJ_FAIL,  MODID_BSM, MODID_CIH2, 0 /* encBuf.len*/,  DEFAULT_MAX_MSG_INST, printGetObjRspFailMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_CIH3_GET_OBJ_FAIL,  MODID_BSM, MODID_CIH3, 0 /* encBuf.len*/,  DEFAULT_MAX_MSG_INST, printGetObjRspFailMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_CIH1_SET_MSG_TRACE,  MODID_BSM, MODID_CIH1, sizeof(MsgTrace),  DEFAULT_MAX_MSG_INST, printMsgSetMsgTrace,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_CIH2_SET_MSG_TRACE,  MODID_BSM, MODID_CIH2, sizeof(MsgTrace),  DEFAULT_MAX_MSG_INST, printMsgSetMsgTrace,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_CIH3_SET_MSG_TRACE,  MODID_BSM, MODID_CIH3, sizeof(MsgTrace),  DEFAULT_MAX_MSG_INST, printMsgSetMsgTrace,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initBsmSihIntMsgDescTable()
{
  /** SIH -> BSM Interface **/
  initElementInMsgDescTable( MSG_SIH_BSM_SET_OBJ_REQ,        MODID_SIH, MODID_BSM, 0 /* encBuf.len*/,               DEFAULT_MAX_MSG_INST, printSetObjReqMsg,     MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SIH_BSM_GET_OBJ_REQ,        MODID_SIH, MODID_BSM, 0 /* encBuf.len*/,               DEFAULT_MAX_MSG_INST, printGetObjReqMsg,     MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SIH_BSM_INIT_CONFIG_SUCC,   MODID_SIH, MODID_BSM, sizeof(MsgSihBsmInitConfigSucc), DEFAULT_MAX_MSG_INST, printMsgEnbConfigSucc, MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SIH_BSM_INIT_CONFIG_FAIL,   MODID_SIH, MODID_BSM, sizeof(MsgSihBsmInitConfigFail), DEFAULT_MAX_MSG_INST, printMsgEnbConfigFail, MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );

  /** BSM -> SIH Interface **/
  initElementInMsgDescTable( MSG_BSM_SIH_INIT_CONFIG_REQ, MODID_BSM, MODID_SIH, sizeof(MsgBsmSihInitConfigReq),DEFAULT_MAX_MSG_INST, printMsgSihConfigReq,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_SIH_SET_OBJ_SUCC,    MODID_BSM, MODID_SIH, 0 /* encBuf.len*/,             DEFAULT_MAX_MSG_INST, printSetObjRspSuccMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_SIH_SET_OBJ_FAIL,    MODID_BSM, MODID_SIH, 0 /* encBuf.len*/,             DEFAULT_MAX_MSG_INST, printSetObjRspFailMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_SIH_GET_OBJ_SUCC,    MODID_BSM, MODID_SIH, 0 /* encBuf.len*/,             DEFAULT_MAX_MSG_INST, printGetObjRspSuccMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_SIH_GET_OBJ_FAIL,    MODID_BSM, MODID_SIH, 0 /* encBuf.len*/,             DEFAULT_MAX_MSG_INST, printGetObjRspFailMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_SIH_NOTI_IND,        MODID_BSM, MODID_SIH, 0 /* encBuf.len*/,             DEFAULT_MAX_MSG_INST, printNotiObjReqMsg,    MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_SIH_STOP_TRACE_IND,  MODID_BSM, MODID_SIH, 0,                             DEFAULT_MAX_MSG_INST, NULL,                  MSGTRACELEVEL_MSGIDONLY,     MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_SIH_SET_MSG_TRACE,   MODID_BSM, MODID_SIH, sizeof(MsgTrace),              DEFAULT_MAX_MSG_INST, printMsgSetMsgTrace,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  /* Message for log level change */
  initElementInMsgDescTable( MSG_BSM_SIH_SET_LOG_CFG,   MODID_BSM, MODID_SIH, sizeof(MsgBsmSihSetLogCfg), DEFAULT_MAX_MSG_INST, PrintMsgSetLogConfig, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initPrmSihIntMsgDescTable()
{
  /* PRM -> SIH Interface */
  initElementInMsgDescTable( MSG_PRM_SIH_EXIT_CMD,  MODID_PRM, MODID_SIH, sizeof(MsgPrmModExitCmd), DEFAULT_MAX_MSG_INST, printMsgExitCmd,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_SIH_HELLO,     MODID_PRM, MODID_SIH, sizeof(MsgPrmModHello),   DEFAULT_MAX_MSG_INST, printMsgHello,   MSGTRACELEVEL_MSGWITHPARAMS,  MSGTRACEDIRECTION_MSGINBOTHDIREC );

  /* SIH -> PRM Interface */
  initElementInMsgDescTable( MSG_SIH_PRM_HELLO_ACK, MODID_SIH, MODID_PRM, sizeof(MsgModPrmHelloAck),DEFAULT_MAX_MSG_INST, printMsgHelloAck,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SIH_PRM_START_IND, MODID_SIH, MODID_PRM, sizeof(MsgStartInd),      DEFAULT_MAX_MSG_INST, printStartIndMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initBsmWihIntMsgDescTable()
{
  /* WIH - BSM Interface */
  initElementInMsgDescTable( MSG_WIH_BSM_SET_OBJ_REQ,   MODID_WIH, MODID_BSM, 0 /* encBuf.len*/, DEFAULT_MAX_MSG_INST, printSetObjReqMsg,      MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_WIH_BSM_GET_OBJ_REQ,   MODID_WIH, MODID_BSM, 0 /* encBuf.len*/, DEFAULT_MAX_MSG_INST, printGetObjReqMsg,      MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_WIH_SET_OBJ_SUCC,  MODID_BSM, MODID_WIH, 0 /* encBuf.len*/, DEFAULT_MAX_MSG_INST, printSetObjRspSuccMsg,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_WIH_SET_OBJ_FAIL,  MODID_BSM, MODID_WIH, 0 /* encBuf.len*/, DEFAULT_MAX_MSG_INST, printSetObjRspFailMsg,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_WIH_GET_OBJ_SUCC,  MODID_BSM, MODID_WIH, 0 /* encBuf.len*/, DEFAULT_MAX_MSG_INST, printGetObjRspSuccMsg,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_BSM_WIH_GET_OBJ_FAIL,  MODID_BSM, MODID_WIH, 0 /* encBuf.len*/, DEFAULT_MAX_MSG_INST, printGetObjRspFailMsg,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_BSM_WIH_SET_MSG_TRACE, MODID_BSM, MODID_WIH, sizeof(MsgTrace),  DEFAULT_MAX_MSG_INST, printMsgSetMsgTrace,    MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  /* Message for log level change */
  initElementInMsgDescTable( MSG_BSM_WIH_SET_LOG_CFG, MODID_BSM, MODID_WIH, sizeof(LogConfig), DEFAULT_MAX_MSG_INST, PrintMsgSetLogConfig, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

/*CCPU modules*/
static void initEgtpPrmIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PRM_EGTP_HELLO,     MODID_PRM,  MODID_EGTP, sizeof(MsgPrmModHello),   DEFAULT_MAX_MSG_INST, printMsgHello,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_EGTP_EXIT_CMD,  MODID_PRM,  MODID_EGTP, sizeof(MsgPrmModExitCmd), DEFAULT_MAX_MSG_INST, printMsgExitCmd, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_EGTP_PRM_HELLO_ACK, MODID_EGTP, MODID_PRM, sizeof(MsgModPrmHelloAck),DEFAULT_MAX_MSG_INST,  printMsgHelloAck, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_EGTP_PRM_START_IND, MODID_EGTP, MODID_PRM, sizeof(MsgStartInd),       DEFAULT_MAX_MSG_INST, printStartIndMsg, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initRlcPrmIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PRM_RLC_HELLO,     MODID_PRM, MODID_RLC, sizeof(MsgPrmModHello),      DEFAULT_MAX_MSG_INST, printMsgHello,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_RLC_EXIT_CMD,  MODID_PRM, MODID_RLC, sizeof(MsgPrmModExitCmd),    DEFAULT_MAX_MSG_INST, printMsgExitCmd, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_RLC_PRM_HELLO_ACK, MODID_RLC, MODID_PRM, sizeof(MsgModPrmHelloAck),DEFAULT_MAX_MSG_INST, printMsgHelloAck,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_RLC_PRM_START_IND, MODID_RLC, MODID_PRM, sizeof(MsgStartInd),         DEFAULT_MAX_MSG_INST, printStartIndMsg,MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}


static void initPdcpPrmIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PRM_PDCP_HELLO,     MODID_PRM,  MODID_PDCP, sizeof(MsgPrmModHello),   DEFAULT_MAX_MSG_INST, printMsgHello,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_PDCP_EXIT_CMD,  MODID_PRM,  MODID_PDCP, sizeof(MsgPrmModExitCmd), DEFAULT_MAX_MSG_INST, printMsgExitCmd, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_PDCP_PRM_HELLO_ACK, MODID_PDCP, MODID_PRM, sizeof(MsgModPrmHelloAck),DEFAULT_MAX_MSG_INST, printMsgHelloAck,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PDCP_PRM_START_IND, MODID_PDCP, MODID_PRM, sizeof(MsgStartInd),       DEFAULT_MAX_MSG_INST, printStartIndMsg,MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}


static void initTuclPrmIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PRM_TUCL_HELLO,     MODID_PRM,  MODID_TUCL, sizeof(MsgPrmModHello),   DEFAULT_MAX_MSG_INST, printMsgHello,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_TUCL_EXIT_CMD,  MODID_PRM,  MODID_TUCL, sizeof(MsgPrmModExitCmd), DEFAULT_MAX_MSG_INST, printMsgExitCmd, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_TUCL_PRM_HELLO_ACK, MODID_TUCL, MODID_PRM, sizeof(MsgModPrmHelloAck),DEFAULT_MAX_MSG_INST, printMsgHelloAck,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_TUCL_PRM_START_IND, MODID_TUCL, MODID_PRM, sizeof(MsgStartInd),       DEFAULT_MAX_MSG_INST, printStartIndMsg,MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initMacPrmIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PRM_MAC_HELLO,     MODID_PRM, MODID_MAC, sizeof(MsgPrmModHello),   DEFAULT_MAX_MSG_INST, printMsgHello,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_MAC_EXIT_CMD,  MODID_PRM, MODID_MAC, sizeof(MsgPrmModExitCmd), DEFAULT_MAX_MSG_INST, printMsgExitCmd, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_MAC_PRM_HELLO_ACK, MODID_MAC, MODID_PRM, sizeof(MsgModPrmHelloAck),DEFAULT_MAX_MSG_INST, printMsgHelloAck,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_MAC_PRM_START_IND, MODID_MAC, MODID_PRM, sizeof(MsgStartInd),      DEFAULT_MAX_MSG_INST, printStartIndMsg,MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initTfuPrmIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PMH_TFU_DSTATS_CFG_REQ, MODID_PMH, MODID_TFU, sizeof(MsgPmhTfuDStatsCfgReq),   DEFAULT_MAX_MSG_INST, PrintMsgDstatsCfg,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_TFU_PMH_DSTATS_IND, MODID_TFU, MODID_PMH, sizeof(MsgTfuPmhDStatsInd),   DEFAULT_MAX_MSG_INST, PrintMsgDstatsInd,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}
static void initRrcPrmIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PRM_RRC_HELLO,     MODID_PRM, MODID_RRC, sizeof(MsgPrmModHello),   DEFAULT_MAX_MSG_INST, printMsgHello,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_RRC_EXIT_CMD,  MODID_PRM, MODID_RRC, sizeof(MsgPrmModExitCmd), DEFAULT_MAX_MSG_INST, printMsgExitCmd, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_RRC_PRM_HELLO_ACK, MODID_RRC, MODID_PRM, sizeof(MsgModPrmHelloAck),DEFAULT_MAX_MSG_INST, printMsgHelloAck,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_RRC_PRM_START_IND, MODID_RRC, MODID_PRM, sizeof(MsgStartInd),      DEFAULT_MAX_MSG_INST, printStartIndMsg,MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initSctpPrmIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PRM_SCTP_HELLO,     MODID_PRM,  MODID_SCTP, sizeof(MsgPrmModHello),   DEFAULT_MAX_MSG_INST, printMsgHello,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_SCTP_EXIT_CMD,  MODID_PRM,  MODID_SCTP, sizeof(MsgPrmModExitCmd), DEFAULT_MAX_MSG_INST, printMsgExitCmd, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_SCTP_PRM_START_IND, MODID_SCTP, MODID_PRM, sizeof(MsgStartInd),       DEFAULT_MAX_MSG_INST, printStartIndMsg,MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_SCTP_PRM_HELLO_ACK, MODID_SCTP, MODID_PRM, sizeof(MsgModPrmHelloAck),DEFAULT_MAX_MSG_INST, printMsgHelloAck,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initS1apPrmIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_PRM_S1AP_HELLO,    MODID_PRM, MODID_S1AP, sizeof(MsgPrmModHello),   DEFAULT_MAX_MSG_INST, printMsgHello,   MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_PRM_S1AP_EXIT_CMD, MODID_PRM, MODID_S1AP, sizeof(MsgPrmModExitCmd), DEFAULT_MAX_MSG_INST, printMsgExitCmd, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_S1AP_PRM_HELLO_ACK,MODID_S1AP, MODID_PRM, sizeof(MsgModPrmHelloAck),DEFAULT_MAX_MSG_INST, printMsgHelloAck,  MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_S1AP_PRM_START_IND,MODID_S1AP, MODID_PRM, sizeof(MsgStartInd),      DEFAULT_MAX_MSG_INST, printStartIndMsg,MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}

static void initBsmSmIntMsgDescTable()
{
  initElementInMsgDescTable( MSG_BSM_SM_SET_LOG_CFG, MODID_BSM, MODID_SM, sizeof( SetLogConfig ), DEFAULT_MAX_MSG_INST, PrintMsgSetLogConfig, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}
void initMsgDescTable(
  IN ModuleId  modId
  )
{
  switch( modId )
  {
    case MODID_CIH1:
      initCih1IntMsgDescTable();
      initBsmCihIntMsgDescTable();
      break;
    case MODID_CIH2:
      initCih2IntMsgDescTable();
      initBsmCihIntMsgDescTable();
      break;
    case MODID_CIH3:
      initCih3IntMsgDescTable();
      initBsmCihIntMsgDescTable();
      break;
    case MODID_SIH:
      initSihIntMsgDescTable();
      initBsmSihIntMsgDescTable();
      initPrmSihIntMsgDescTable();
      break;
    case MODID_WIH:
      initWihIntMsgDescTable();
      initBsmWihIntMsgDescTable();
      initPrmWihIntMsgDescTable();
      break;
    case MODID_BSM:
      initBsmPmhIntMsgDescTable();
      initBsmFthIntMsgDescTable();
      initBsmDehIntMsgDescTable();
      initBsmCihIntMsgDescTable();
      initBsmWihIntMsgDescTable();
      initPrmBsmIntMsgDescTable();
      initBsmSihIntMsgDescTable();
      initBsmUehIntMsgDescTable();
#ifdef GEN_TPUT_TESTER /* Required for throughput testing */
      initTputIntMsgDescTable();
#endif
      initBsmIntMsgDescTable();

      initBsmS1apIntMsgDescTable();
      initBsmEgtpIntMsgDescTable();
      initSctpBsmIntMsgDescTable();

      initLthBsmIntMsgDescTable();
      initMacLthIntMsgDescTable();

      initBsmUdhIntMsgDescTable();
      initBsmSmIntMsgDescTable();
      break;
    case MODID_FTH:
			initFthIntMsgDescTable();
      initBsmFthIntMsgDescTable();
      initPrmFthIntMsgDescTable();
      break;
    case MODID_UEH:
      initPrmUehIntMsgDescTable();
      initBsmUehIntMsgDescTable();
      initUehPmhIntMsgDescTable();
      break;
    case MODID_PRM:
      initPrmIntMsgDescTable();
      initPrmIntExitMsgDescTable();
      initPrmBsmIntMsgDescTable();
      initPrmDehIntMsgDescTable();
      initPrmFthIntMsgDescTable();
      initPrmUehIntMsgDescTable();
      initPrmWihIntMsgDescTable();
      initPrmSihIntMsgDescTable();
      /* CCPU Modules */
      initEgtpPrmIntMsgDescTable();
      initTuclPrmIntMsgDescTable();
      initMacPrmIntMsgDescTable();
      initRrcPrmIntMsgDescTable();
      initSctpPrmIntMsgDescTable();
      initS1apPrmIntMsgDescTable();
      initRlcPrmIntMsgDescTable();
      initPdcpPrmIntMsgDescTable();
      initPrmLthIntMsgDescTable();
      initPrmPmhIntMsgDescTable();
      initPrmUdhIntMsgDescTable();
      break;
    case MODID_DEH:
      initDehIntMsgDescTable();
      initBsmDehIntMsgDescTable();
      initPrmDehIntMsgDescTable();
      break;
    case MODID_LTH:
      initPrmLthIntMsgDescTable();
      initLthBsmIntMsgDescTable();
      initMacLthIntMsgDescTable();
      initRrcLthIntMsgDescTable();
      initS1apLthIntMsgDescTable();
      initRlcLthIntMsgDescTable();
      initPdcpLthIntMsgDescTable();
      initEgtpLthIntMsgDescTable();
      initLthRrcIntMsgDescTable();
      initLthRlcIntMsgDescTable();
      initLthPdcpIntMsgDescTable();
      initLthS1apIntMsgDescTable();
      initLthIntMsgDescTable();
      break;
    case MODID_EGTP:
      initPrmEgtpIntMsgDescTable();
      initBsmEgtpIntMsgDescTable();
      initPmhGtpIntMsgDescTable();
      initEgtpLthIntMsgDescTable();
      break;
    case MODID_TUCL:
      initPrmTuclIntMsgDescTable();
      break;
    case MODID_RLC:
       initRlcPrmIntMsgDescTable();
       initLthRlcIntMsgDescTable();
       initRlcLthIntMsgDescTable();
       initPmhRlcIntMsgDescTable();
     break;
     case MODID_PDCP:
       initPdcpPrmIntMsgDescTable();
       initLthPdcpIntMsgDescTable();
       initPdcpLthIntMsgDescTable();
       initPmhPdcpIntMsgDescTable();
      break;
    case MODID_MAC:
      initMacPrmIntMsgDescTable();

      initMacLthIntMsgDescTable();
      initMacPmhIntMsgDescTable();
      break;
    case MODID_RRC:
      initRrcPrmIntMsgDescTable();
      initLthRrcIntMsgDescTable();
      initRrcLthIntMsgDescTable();
      initPmhRrcIntMsgDescTable();
      break;
    case MODID_SCTP:
      initSctpPrmIntMsgDescTable();
      initSctpBsmIntMsgDescTable();
      initPmhSctpIntMsgDescTable();
      break;
    case MODID_S1AP:
      initBsmS1apIntMsgDescTable();
      initS1apPrmIntMsgDescTable();
      initS1apLthIntMsgDescTable();
      initS1apPmhIntMsgDescTable();
    break;
    case MODID_PMH:
      initPmhIntMsgDescTable();
      initBsmPmhIntMsgDescTable();
      initPmhPdcpIntMsgDescTable();
      initPmhGtpIntMsgDescTable();
      initPmhRlcIntMsgDescTable();
      initPmhSctpIntMsgDescTable();
      initPmhRrcIntMsgDescTable();
      initPrmPmhIntMsgDescTable();
      initMacPmhIntMsgDescTable();
      initS1apPmhIntMsgDescTable();
      initUehPmhIntMsgDescTable();
      initUdhPmhIntMsgDescTable();
      initTfuPrmIntMsgDescTable();
      break;
    case MODID_UDH:
      initPrmUdhIntMsgDescTable();
      initBsmUdhIntMsgDescTable();
      initUdhPmhIntMsgDescTable();
      break;
    case MODID_SM:
      initBsmSmIntMsgDescTable();
      break;
    case MODID_TFU:
      initTfuPrmIntMsgDescTable();
#ifdef GEN_TPUT_TESTER /* Required for throughput testing */
    case MODID_TPUT_TESTER_COORD:
    case MODID_TPUT_TESTER_NODE_B:
    case MODID_TPUT_TESTER_NODE_A:
      initTputIntMsgDescTable();
      break;
#endif
    default:
      BS_ERROR_UNKNOWN_MOD_ID(modId);
      break;
  }
}

#ifdef GEN_TPUT_TESTER /* Required for throughput testing */
static void initTputIntMsgDescTable()
{
  /* Performance Module */
  initElementInMsgDescTable( MSG_COORD_NODEA_SESSION_CREATE_REQ,    MODID_TPUT_TESTER_COORD,  MODID_TPUT_TESTER_NODE_A,   0, DEFAULT_MAX_MSG_INST, printMsgCoordNodeXSessionCreateReq , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_NODEA_COORD_SESSION_CREATE_SUCC,   MODID_TPUT_TESTER_NODE_A, MODID_TPUT_TESTER_COORD,   0, DEFAULT_MAX_MSG_INST,  printMsgNodeXCoordSessionCreateSucc, MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_NODEA_COORD_SESSION_CREATE_FAIL,   MODID_TPUT_TESTER_NODE_A, MODID_TPUT_TESTER_COORD,   0, DEFAULT_MAX_MSG_INST, printMsgNodeXCoordSessionCreateFail , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_COORD_NODEB_SESSION_CREATE_REQ,    MODID_TPUT_TESTER_COORD,  MODID_TPUT_TESTER_NODE_B,   0, DEFAULT_MAX_MSG_INST, printMsgCoordNodeXSessionCreateReq , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_NODEB_COORD_SESSION_CREATE_SUCC,   MODID_TPUT_TESTER_NODE_B, MODID_TPUT_TESTER_COORD,   0, DEFAULT_MAX_MSG_INST, printMsgNodeXCoordSessionCreateSucc , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_NODEB_COORD_SESSION_CREATE_FAIL,   MODID_TPUT_TESTER_NODE_B, MODID_TPUT_TESTER_COORD,   0, DEFAULT_MAX_MSG_INST, printMsgNodeXCoordSessionCreateFail , MSGTRACELEVEL_MSGWITHPARAMS, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_COORD_NODEA_START_DATA_TX,         MODID_TPUT_TESTER_COORD,  MODID_TPUT_TESTER_NODE_A,   0, DEFAULT_MAX_MSG_INST, printMsgCoordNodeXStartDataTx , MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_COORD_NODEB_START_DATA_TX,         MODID_TPUT_TESTER_COORD,  MODID_TPUT_TESTER_NODE_B,   0, DEFAULT_MAX_MSG_INST, printMsgCoordNodeXStartDataTx , MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_NODEA_COORD_DATA_TX_RX_COMPLETE,   MODID_TPUT_TESTER_NODE_A,  MODID_TPUT_TESTER_COORD,   0, DEFAULT_MAX_MSG_INST, printMsgNodeXCoordDataTxRxComplete , MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_NODEB_COORD_DATA_TX_RX_COMPLETE,   MODID_TPUT_TESTER_NODE_B,  MODID_TPUT_TESTER_COORD,   0, DEFAULT_MAX_MSG_INST, printMsgNodeXCoordDataTxRxComplete , MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_COORD_NODEA_SESSION_INFO_REQ,      MODID_TPUT_TESTER_COORD, MODID_TPUT_TESTER_NODE_A,   0, DEFAULT_MAX_MSG_INST, printMsgCoordNodeXSessionInfoReq , MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_NODEA_COORD_SESSION_INFO_RSP,      MODID_TPUT_TESTER_NODE_A, MODID_TPUT_TESTER_COORD,   0, DEFAULT_MAX_MSG_INST, printMsgNodeXCoordSessionInfoRsp , MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_COORD_NODEB_SESSION_INFO_REQ,      MODID_TPUT_TESTER_COORD, MODID_TPUT_TESTER_NODE_B,   0, DEFAULT_MAX_MSG_INST, printMsgCoordNodeXSessionInfoReq , MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_NODEB_COORD_SESSION_INFO_RSP,      MODID_TPUT_TESTER_NODE_B, MODID_TPUT_TESTER_COORD,   0, DEFAULT_MAX_MSG_INST, printMsgNodeXCoordSessionInfoRsp , MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_COORD_NODEA_SESSION_DEL_REQ,       MODID_TPUT_TESTER_COORD, MODID_TPUT_TESTER_NODE_A,   0, DEFAULT_MAX_MSG_INST, printMsgCoordNodeXSessionDelReq , MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_NODEA_COORD_SESSION_DEL_SUCC,      MODID_TPUT_TESTER_NODE_A, MODID_TPUT_TESTER_COORD,   0, DEFAULT_MAX_MSG_INST, printMsgNodeXCoordSessionDelSucc , MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_NODEA_COORD_SESSION_DEL_FAIL,      MODID_TPUT_TESTER_NODE_A, MODID_TPUT_TESTER_COORD,   0, DEFAULT_MAX_MSG_INST, printMsgNodeXCoordSessionDelFail , MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_COORD_NODEB_SESSION_DEL_REQ,       MODID_TPUT_TESTER_COORD, MODID_TPUT_TESTER_NODE_B,   0, DEFAULT_MAX_MSG_INST, printMsgCoordNodeXSessionDelReq , MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_NODEB_COORD_SESSION_DEL_SUCC,      MODID_TPUT_TESTER_NODE_B, MODID_TPUT_TESTER_COORD,   0, DEFAULT_MAX_MSG_INST, printMsgNodeXCoordSessionDelSucc , MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_NODEB_COORD_SESSION_DEL_FAIL,      MODID_TPUT_TESTER_NODE_B, MODID_TPUT_TESTER_COORD,   0, DEFAULT_MAX_MSG_INST, printMsgNodeXCoordSessionDelFail , MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );

  initElementInMsgDescTable( MSG_TIMEKEEPER_SHOW_USAGE_TIMEOUT_IND,          MODID_TPUT_TESTER_COORD,  MODID_TPUT_TESTER_NODE_A,   sizeof(MsgTimeoutInd), DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_TIMEKEEPER_COORD_DATA_COMPLETE_TIMEOUT_IND, MODID_TPUT_TESTER_COORD,  MODID_TPUT_TESTER_COORD,    sizeof(MsgTimeoutInd), DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_TIMEKEEPER_NODEB_RCV_DATA_TIMEOUT_IND,      MODID_TPUT_TESTER_NODE_B, MODID_TPUT_TESTER_NODE_B,   sizeof(MsgTimeoutInd), DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_TIMEKEEPER_NODEA_RCV_DATA_TIMEOUT_IND,      MODID_TPUT_TESTER_NODE_A, MODID_TPUT_TESTER_NODE_A,   sizeof(MsgTimeoutInd), DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_TIMEKEEPER_NODEA_SEND_DATA_TIMEOUT_IND,     MODID_TPUT_TESTER_NODE_A, MODID_TPUT_TESTER_NODE_A,   sizeof(MsgTimeoutInd), DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
  initElementInMsgDescTable( MSG_TIMEKEEPER_NODEB_SEND_DATA_TIMEOUT_IND,     MODID_TPUT_TESTER_NODE_B, MODID_TPUT_TESTER_NODE_B,   sizeof(MsgTimeoutInd), DEFAULT_MAX_MSG_INST, NULL, MSGTRACELEVEL_MSGIDONLY, MSGTRACEDIRECTION_MSGINBOTHDIREC );
}
#endif
