/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef MSGTRACE_H
#define MSGTRACE_H

/* function declarations */
void init_msgTrace(void);
void initialize_table_msgTraceTable(void);

/* column number definitions for table msgTraceTable */
       #define COLUMN_MSGID		1
       #define COLUMN_MSGTRACELEVEL		2
       #define COLUMN_MSGTRACEDIRECTION		3

#define MSG_TRACE_MAX_COL   COLUMN_MSGTRACEDIRECTION

    /* Typical data structure for a row entry */
typedef struct msgTraceTable_entry {
    /* Index values */
    unsigned int msgId;

    /* Column values */
    unsigned int msgTraceLevel;
    unsigned int msgTraceDirection;

    /* Illustrate using a simple linked list */
    int   valid;
    struct msgTraceTable_entry *next;
}msgTraceTableEntry;

#endif /* MSGTRACE_H */
