cs-make OS=LINUX TOOLCHAIN=CS BOARD=C4KEVM FOURG=LTE-RCT MACTYPE=UE clean
cs-make OS=LINUX TOOLCHAIN=CS BOARD=C4KEVM FOURG=LTE-RCT MACTYPE=ENODEB clean
cs-make OS=LINUX TOOLCHAIN=CS BOARD=C4KEVM FOURG=LTE-RCT MACTYPE=STUB clean
