# X2AP command file
#
# line syntax:
#  name <text string>
#  part <media part number> <text string>
#  file <file name>
#  options <options>
#
name X2AP
options 01
part 1000373-01 Product Files (cz)
file cz.h
file cz.x
file cz_bmp.c
file cz_db.c
file cz_edm.c
file cz_err.h
file cz_ex_ms.c
file cz_ex_pt.c
file cz_gpm.c
file cz_ldm.c
file cz_id.c
file cz_lim.c
file cz_lmm.c
file cz_nmm.c
file cz_ptli.c
file cz_ptmi.c
file cz_ptui.c
file cz_tmr.c
file cz_tpm.c
file cz_tst.c
file cz_uim.c
file cz_utl.c
file cz.mak
part 1000373-02 Common Files (cm)
file lcz.h
file lcz.x
file lcz.c
file czt_asn.h
file czt_asn.x
file czt.c
file czt.h
file czt_pk.c
file czt_pk.x
file czt_unpk.c
file czt_unpk.x
file czt.x
file sct.h
file sct.x
file sct.c
file cm_tpt.h
file cm_tpt.x
file cm_tpt.c
file envopt.h 
file envdep.h
file envind.h
file gen.h
file gen.x
file ssi.h
file ssi.x
file sm_bdy1.c
file sm_ex_ms.c
file cm5.h
file cm5.x
file cm_lib.x
file cm_lib.c
file cm_hash.h
file cm_hash.x
file cm_hash.c
file cm_inet.h
file cm_inet.x
file cm_inet.c
file cm_dns.c
file cm_dns.h
file cm_dns.x
file cm_bdy5.c
file cm_mblk.h 
file cm_mblk.x 
file cm_mblk.c 
file cm_llist.h
file cm_llist.x
file cm_llist.c
file cm_mem.h
file cm_mem.x
file cm_mem.c
file cm_pint.h
file cm_pint.x
file cm_perr.h
file cm_pasn.h
file cm_pasn.x
file cm_pasn1.c
file cm_pasn2.c
file cm_pasn3.c
file cm_pasn4.c
file cm_err.h
file cm_tkns.h
file cm_tkns.x
file cm_tkns.c
file cm_gen.h
file cm_gen.c
file ss_ptsp.c
file cm_xta_checkfile.py
file cm_xta_cmdmap.py
file cm_xta_genattr.py
file cm_xta_gen_cmd.py
file cm_xta_gen_tc_num.py
file cm_xta_pyattr.py
file cm_xta_pycmd.py
file cm_xta_py.py
file cm_xta_tc_doc.py
file cm_xta_tc_xmldoc.py
file cm_xta_ex_ms.c
file cm_xta_flag.c
file cm_xta.h
file cm_xta_inthdl.c
file cm_xta_intreg.c
file cm_xta_intutl.c
file cm_xta_ipc.c
file cm_xta_ldfsm.c
file cm_xta_log.c
file cm_xta_master.c
file cm_xta_py.c
file cm_xta_py.x
file cm_xta_queue.c
file cm_xta_reg.c
file cm_xta_res.c
file cm_xta_slave.c
file cm_xta_tafsm.c
file cm_xta_tcfsm.c
file cm_xta_tgfsm.c
file cm_xta_tmr.c
file cm_xta_tst.c
file cm_xta_txn.c
file cm_xta.x
file cm_xta_xml.c
part 1000373-03 Sample Files (acc)
file cm_xta_app.h
file cm_xta_app.x
file czac_flag.c
file czac_prof.c
file czac_slave.c
file czac_tst.c
file czac_acc.h
file czac_acc.x
file czac_lhihdl.c
file czac_lhireg.c
file czac_lhicb.c
file czac_lhiutl.c
file czac_lhi.x
file czac_lsb.x
file czac_sb_ex_ms.c
file czac_lsbcb.c
file czac_lsbhdl.c
file czac_lsbutl.c
file czac_lsbreg.c
file czac_sct.x
file czac_sctcb.c
file czac_sctutl.c
file czac_sctptui.c
file czac_scthdl.c
file czac_sctreg.c
file czac_lczutl.c
file czac_lczhdl.c
file czac_lczcb.c
file czac_lczreg.c
file czac_lcz.x
file czac_czld.c
file czac_cztreg.c
file czac_czthdl.c
file czac_cztutl.c
file czac_cztcb.c
file czac_czt.x
file czac_cmd1.xml
file czac_tc1.xml
file czac_cmd2.xml
file czac_tg1.xml
file czac_pycmd.py
part 1000373-04 Sample Files (sm)
file envopt.acc
file envopt.acc.00
file smczbdy1.c
file smcz_err.h
file smczexms.c
file smczptmi.c
file rs_ex_ms.c
file rs_ptli.c
file rs.x
part 1000373-05 Documentation Files
file 1091373.31
file 1092373.31
file 1093373.31
file 1094373.31
file 1095373.31
file 1225373.31
file 1111001.311a
file 1111011.11
file 1100092.31
file 1092373.31.chm
file 1100092.31.chm
file 1100031.110
file 1100036.16
