/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef TIMERSCONFIG_H
#define TIMERSCONFIG_H

/* function declarations */
void init_timersConfig(void);
void initialize_table_timersConfigTable(void);

/* column number definitions for table timersConfigTable */
       #define COLUMN_TIMERNAME		1
       #define COLUMN_TIMEUNIT		2
       #define COLUMN_DURATION		3
       #define COLUMN_DESCRIPTION		4
       #define COLUMN_USEDBY		5

#define TIMERS_CONFIG_MAX_COL COLUMN_USEDBY


#define TIMERS_CONFIG_DESC_BUF_LEN_MAX    32
#define TIMERS_BUFFER_LEN_MAX           33

    /* Typical data structure for a row entry */
typedef struct timersConfigTable_entry {
    /* Index values */
    unsigned int timerName;

    /* Column values */
    unsigned int timeUnit;
    unsigned int duration;
    char description[TIMERS_BUFFER_LEN_MAX];
    size_t description_len;
    unsigned int usedBy;

    /* Illustrate using a simple linked list */
    int   valid;
    struct timersConfigTable_entry *next;
}timersConfigTableEntry;

#endif /* TIMERSCONFIG_H */
