/**
* @file    sfi_init.c
* @brief This module contians Messge ID mapping from Event and Source entitiy.
*        This file is generated from OAM sheet make changes in SfiInitMsg.sheet.
* @details Copyright Powerwave Technologies, Inc., 2010
*
*/
#include  "pst_events.h"
#include  "msg_ids.h"
#include  "bs_modules.h"
#include  "sfi.h"
#include  "libconfig.h"
#include  "log.h"
#include  "msg_names.h"


void sfiInitMsgIdByEventAndSrcEntity(
  SfiCb *sfiCb
  )
{
/* -'- PWAV_START_EVENT' is being used to reduce the size of array.
* PWAV defined events starting from PWAV_START_EVENT as (0 to PWAV_START_EVENT) range is used by CCPU.
*/

/*Start Indication messages from all modules to PRM */
  sfiCb->msgIdFromEventAndEntityArray[ENTSZ][EVT_START_IND - PWAV_START_EVENT] = 		MSG_S1AP_PRM_START_IND;
  sfiCb->msgIdFromEventAndEntityArray[ENTHI][EVT_START_IND - PWAV_START_EVENT] = 		MSG_TUCL_PRM_START_IND;
  sfiCb->msgIdFromEventAndEntityArray[ENTSB][EVT_START_IND - PWAV_START_EVENT] = 		MSG_SCTP_PRM_START_IND;
  sfiCb->msgIdFromEventAndEntityArray[ENTEG][EVT_START_IND - PWAV_START_EVENT] = 		MSG_EGTP_PRM_START_IND;
  sfiCb->msgIdFromEventAndEntityArray[ENTPJ][EVT_START_IND - PWAV_START_EVENT] = 		MSG_PDCP_PRM_START_IND;
  sfiCb->msgIdFromEventAndEntityArray[ENTKW][EVT_START_IND - PWAV_START_EVENT] = 		MSG_RLC_PRM_START_IND;
  sfiCb->msgIdFromEventAndEntityArray[ENTRG][EVT_START_IND - PWAV_START_EVENT] = 		MSG_MAC_PRM_START_IND;
  sfiCb->msgIdFromEventAndEntityArray[ENTNH][EVT_START_IND - PWAV_START_EVENT] = 		MSG_RRC_PRM_START_IND;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_START_IND - PWAV_START_EVENT] = 		MSG_UEH_PRM_START_IND;
  sfiCb->msgIdFromEventAndEntityArray[ENTUDH][EVT_START_IND - PWAV_START_EVENT] = 		MSG_UDH_PRM_START_IND;

/*Hello Ack message from all modules to PRM */
  sfiCb->msgIdFromEventAndEntityArray[ENTSZ][EVT_HELLO_ACK - PWAV_START_EVENT] = 		MSG_S1AP_PRM_HELLO_ACK;
  sfiCb->msgIdFromEventAndEntityArray[ENTHI][EVT_HELLO_ACK - PWAV_START_EVENT] = 		MSG_TUCL_PRM_HELLO_ACK;
  sfiCb->msgIdFromEventAndEntityArray[ENTSB][EVT_HELLO_ACK - PWAV_START_EVENT] = 		MSG_SCTP_PRM_HELLO_ACK;
  sfiCb->msgIdFromEventAndEntityArray[ENTEG][EVT_HELLO_ACK - PWAV_START_EVENT] = 		MSG_EGTP_PRM_HELLO_ACK;
  sfiCb->msgIdFromEventAndEntityArray[ENTPJ][EVT_HELLO_ACK - PWAV_START_EVENT] = 		MSG_PDCP_PRM_HELLO_ACK;
  sfiCb->msgIdFromEventAndEntityArray[ENTKW][EVT_HELLO_ACK - PWAV_START_EVENT] = 		MSG_RLC_PRM_HELLO_ACK;
  sfiCb->msgIdFromEventAndEntityArray[ENTRG][EVT_HELLO_ACK - PWAV_START_EVENT] = 		MSG_MAC_PRM_HELLO_ACK;
  sfiCb->msgIdFromEventAndEntityArray[ENTNH][EVT_HELLO_ACK - PWAV_START_EVENT] = 		MSG_RRC_PRM_HELLO_ACK;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_HELLO_ACK - PWAV_START_EVENT] = 		MSG_UEH_PRM_HELLO_ACK;
  sfiCb->msgIdFromEventAndEntityArray[ENTUDH][EVT_HELLO_ACK - PWAV_START_EVENT] = 		MSG_UDH_PRM_HELLO_ACK;

/*CEM - OPSTART ,OPSTOP and Config messages*/
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_CEM_BSM_OPSTART_SUCC - PWAV_START_EVENT] = 		MSG_CEM_BSM_OPSTART_SUCC;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_CEM_BSM_OPSTART_FAIL - PWAV_START_EVENT] = 		MSG_CEM_BSM_OPSTART_FAIL;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_CEM_BSM_OPSTOP_CMPL - PWAV_START_EVENT] = 		MSG_CEM_BSM_OPSTOP_SUCC;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_CEM_BSM_CFG_SUCC - PWAV_START_EVENT] = 		MSG_CEM_BSM_ENB_CONFIG_SUCC;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_CEM_BSM_CFG_FAIL - PWAV_START_EVENT] = 		MSG_CEM_BSM_ENB_CONFIG_FAIL;

/*S1M - OPSTART ,OPSTOP,S1 link and Config messages*/
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_S1M_LINK_UP_IND - PWAV_START_EVENT] = 		MSG_S1M_BSM_LINK_UP_IND;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_S1M_LINK_DOWN_IND - PWAV_START_EVENT] = 		MSG_S1M_BSM_LINK_DOWN_IND;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_S1M_LINK_CLOSED_IND - PWAV_START_EVENT] = 		MSG_S1M_BSM_LINK_CLOSED_IND;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_S1M_RESET_IND - PWAV_START_EVENT] = 		MSG_S1M_BSM_RESET_IND;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_S1M_BSM_CFG_SUCC - PWAV_START_EVENT] = 		MSG_S1M_BSM_CONFIG_SUCC;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_S1M_BSM_CFG_FAIL - PWAV_START_EVENT] = 		MSG_S1M_BSM_CONFIG_FAIL;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_S1M_BSM_OPSTART_SUCC - PWAV_START_EVENT] = 		MSG_S1M_BSM_OPSTART_SUCC;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_S1M_BSM_OPSTART_FAIL - PWAV_START_EVENT] = 		MSG_S1M_BSM_OPSTART_FAIL;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_S1M_BSM_OPSTOP_CMPL - PWAV_START_EVENT] = 		MSG_S1M_BSM_OPSTOP_SUCC;

/*UDH - OPSTART ,OPSTOP and Config messages*/
  sfiCb->msgIdFromEventAndEntityArray[ENTUDH][EVT_UDH_BSM_OPSTART_SUCC - PWAV_START_EVENT] = 		MSG_UDH_BSM_OPSTART_SUCC;
  sfiCb->msgIdFromEventAndEntityArray[ENTUDH][EVT_UDH_BSM_OPSTART_FAIL - PWAV_START_EVENT] = 		MSG_UDH_BSM_OPSTART_FAIL;
  sfiCb->msgIdFromEventAndEntityArray[ENTUDH][EVT_UDH_BSM_OPSTOP_CMPL - PWAV_START_EVENT] = 		MSG_UDH_BSM_OPSTOP_SUCC;
  sfiCb->msgIdFromEventAndEntityArray[ENTUDH][EVT_UDH_BSM_CFG_SUCC - PWAV_START_EVENT] = 		MSG_UDH_BSM_CONFIG_SUCC;
  sfiCb->msgIdFromEventAndEntityArray[ENTUDH][EVT_UDH_BSM_CFG_FAIL - PWAV_START_EVENT] = 		MSG_UDH_BSM_CONFIG_FAIL;

/*Init Config requests*/
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_BSM_S1AP_CFG_SUCC - PWAV_START_EVENT] = 		MSG_SM_BSM_S1AP_INIT_CONFIG_SUCC;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_BSM_S1AP_CFG_FAIL - PWAV_START_EVENT] = 		MSG_SM_BSM_S1AP_INIT_CONFIG_FAIL;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_BSM_SCTP_CFG_SUCC - PWAV_START_EVENT] = 		MSG_SM_BSM_SCTP_INIT_CONFIG_SUCC;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_BSM_SCTP_CFG_FAIL - PWAV_START_EVENT] = 		MSG_SM_BSM_SCTP_INIT_CONFIG_FAIL;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_BSM_EGTP_CFG_SUCC - PWAV_START_EVENT] = 		MSG_SM_BSM_EGTP_INIT_CONFIG_SUCC;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_BSM_EGTP_CFG_FAIL - PWAV_START_EVENT] = 		MSG_SM_BSM_EGTP_INIT_CONFIG_FAIL;

/*ACTIVE UE, RAB STATUS*/
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_UEH_BSM_ACTIVE_UE_STATUS_RSP - PWAV_START_EVENT] = 		MSG_UEH_BSM_GET_ACTIVE_UE_STATUS_RSP;
  sfiCb->msgIdFromEventAndEntityArray[ENTUDH][EVT_UDH_BSM_ACTIVE_RAB_STATUS_RSP - PWAV_START_EVENT] = 		MSG_UDH_BSM_GET_ACTIVE_RAB_STATUS_RSP;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_UEH_BSM_UE_EVENT_HISTORY_RSP - PWAV_START_EVENT] = 		MSG_UEH_BSM_GET_UE_EVENT_HISTORY_RSP;
  sfiCb->msgIdFromEventAndEntityArray[ENTUDH][EVT_UDH_BSM_RAB_HISTORY_RSP - PWAV_START_EVENT] = 		MSG_UDH_BSM_GET_RAB_HISTORY_RSP;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_UEH_BSM_UEEVENTHISTORYLOG_CONFIG_SUCC - PWAV_START_EVENT] = MSG_UEH_BSM_UEEVENTHISTORYLOG_CONFIG_SUCC;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_UEH_BSM_UEEVENTHISTORYLOG_CONFIG_FAIL - PWAV_START_EVENT] = MSG_UEH_BSM_UEEVENTHISTORYLOG_CONFIG_FAIL;

/*TRACE Indications*/
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_LTH_TRC_IND - PWAV_START_EVENT] = 		MSG_SM_LTH_TRACE_IND;

/*TRACE REQ Confirmations*/
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_LTH_TRC_START_SUCC - PWAV_START_EVENT] = 		MSG_SM_LTH_TRACE_START_SUCC;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_LTH_TRC_START_FAIL - PWAV_START_EVENT] = 		MSG_SM_LTH_TRACE_START_FAIL;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_LTH_TRC_STOP_SUCC - PWAV_START_EVENT] = 		MSG_SM_LTH_TRACE_STOP_SUCC;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_LTH_TRC_STOP_FAIL - PWAV_START_EVENT] = 		MSG_SM_LTH_TRACE_STOP_FAIL;

/*STATS Response*/
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_PMH_PDCP_GEN_STAT_RSP - PWAV_START_EVENT] = 		MSG_SM_PMH_PDCP_GEN_STAT_RSP;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_PMH_PDCP_UPLANE_STAT_RSP - PWAV_START_EVENT] = 		MSG_SM_PMH_PDCP_UPLANE_STAT_RSP;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_PMH_SCTP_GEN_STAT_RSP - PWAV_START_EVENT] = 		MSG_SM_PMH_SCTP_GEN_STAT_RSP;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_PMH_GTP_GEN_STAT_RSP - PWAV_START_EVENT] = 		MSG_SM_PMH_EGTP_GEN_STAT_RSP;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_PMH_RLC_GEN_STAT_RSP - PWAV_START_EVENT] = 		MSG_SM_PMH_RLC_GEN_STAT_RSP;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_PMH_RRC_GEN_STAT_RSP - PWAV_START_EVENT] = 		MSG_SM_PMH_RRC_GEN_STAT_RSP;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_PMH_RRC_CELL_STAT_RSP - PWAV_START_EVENT] = 		MSG_SM_PMH_RRC_CELL_STAT_RSP;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_PMH_S1AP_GEN_STAT_RSP - PWAV_START_EVENT] = 		MSG_SM_PMH_S1AP_GEN_STAT_RSP;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_PMH_S1AP_PEER_NODE_STAT_RSP - PWAV_START_EVENT] = 		MSG_SM_PMH_S1AP_PEER_NODE_STAT_RSP;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_PMH_MAC_GEN_STAT_RSP - PWAV_START_EVENT] = 		MSG_SM_PMH_MAC_GEN_STAT_RSP;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_PMH_MAC_RLCSAP_STAT_RSP - PWAV_START_EVENT] = 	MSG_SM_PMH_MAC_RLCSAP_STAT_RSP;
  sfiCb->msgIdFromEventAndEntityArray[ENTSM][EVT_SM_PMH_MAC_PHYSAP_STAT_RSP - PWAV_START_EVENT] = 	MSG_SM_PMH_MAC_PHYSAP_STAT_RSP;
  sfiCb->msgIdFromEventAndEntityArray[ENTUDH][EVT_UDH_PMH_DSTAT_RSP - PWAV_START_EVENT] = 		MSG_UDH_PMH_DSTATS_IND;

/*enb Status Rsp*/
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_UEH_BSM_MOD_STATE_RSP - PWAV_START_EVENT] = 		MSG_UEH_BSM_MOD_STATE_RSP;
  sfiCb->msgIdFromEventAndEntityArray[ENTUDH][EVT_UDH_BSM_MOD_STATE_RSP - PWAV_START_EVENT] = 		MSG_UDH_BSM_MOD_STATE_RSP;

/*RRM Counter Rsp*/
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_UEH_PMH_RRM_CELL_STAT_RSP - PWAV_START_EVENT] = 		MSG_UEH_PMH_RRM_STAT_RSP;
  sfiCb->msgIdFromEventAndEntityArray[ENTYS][EVT_TFU_PMH_DSTATS_IND - PWAV_START_EVENT] = 		MSG_TFU_PMH_DSTATS_IND;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_UEH_BSM_UNKWN_ENB_UE_ID_IND - PWAV_START_EVENT] =     MSG_S1M_BSM_UNKNOWN_ENB_UE_ID; 
  /*BS-1799 cell barring procedure*/
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_CEM_BSM_CELL_BAR_SUCC - PWAV_START_EVENT] =     MSG_CEM_BSM_CELL_BAR_SUCC; 
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_CEM_BSM_CELL_UNBAR_SUCC - PWAV_START_EVENT] =     MSG_CEM_BSM_CELL_UNBAR_SUCC; 

/* L2M */
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_UEH_PMH_COUNTER_START_SUCC - PWAV_START_EVENT] =     MSG_UEH_PMH_COUNTER_START_SUCC;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_UEH_PMH_COUNTER_START_FAIL - PWAV_START_EVENT] =     MSG_UEH_PMH_COUNTER_START_FAIL;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_UEH_PMH_COUNTER_STOP_SUCC - PWAV_START_EVENT] =     MSG_UEH_PMH_COUNTER_STOP_SUCC;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_UEH_PMH_COUNTER_REPORT_IND - PWAV_START_EVENT] =     MSG_UEH_PMH_COUNTER_REPORT_IND;
  sfiCb->msgIdFromEventAndEntityArray[ENTUEH][EVT_UEH_PMH_COUNTER_STOP_IND - PWAV_START_EVENT] =     MSG_UEH_PMH_COUNTER_STOP_IND;


}
