/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "bs_modules.h"
#include "all_cfg.h"
#include "all_cmn.h"
#include "tlv_enc_dec.h"

#include "sih.h"
#include "syslog.h"

#include "timersConfig.h"

Netsnmp_Node_Handler timersConfigTable_handler;
Netsnmp_First_Data_Point  timersConfigTable_get_first_data_point;
Netsnmp_Next_Data_Point   timersConfigTable_get_next_data_point;

struct timersConfigTable_entry  *timersConfigTable_head = NULL;
static TBOOL g_sihTimersConfigSetReqProcessed = FALSE;
static TBOOL g_sihTimersConfigGetReqProcessed = FALSE;
static UINT32 g_prevTimersConfigReqCount = 0;
static UINT32 g_timersConfigFirstCall = 0;

/* free_timersConfigTable */
/**
* @details 
*          This is the routine which frees the enodeb config entry. 
*/
void free_timersConfigTable(void)
{
  timersConfigTableEntry  *current = timersConfigTable_head;
  timersConfigTableEntry  *temp = NULL;

  if(current)
  {
    while(current->next != NULL)
    {
        temp = current->next;
        SNMP_FREE( current );
        current = temp;
    }

    SNMP_FREE( current );
    timersConfigTable_head = NULL;
  }
  return;
}


/**
* @details 
*          This is the routine which handles get response from SIH Get Processor
*          and prepare the SNMP GET response for EMS. 
* @param tlvArray contains pointer to TLV array.     
*/
TBOOL sendTimersConfigSnmpGetResponse (
  IO TlvArray    *tlvArray
  )
{
  int  totalNumRow, totalNumCol, i=0, colmn=0, pos=0;
  timersConfigTableEntry *prevPtr = NULL;

  printTLV(tlvArray);

  /* Total no. of Colmns */
  totalNumCol = TIMERS_CONFIG_MAX_COL;
  /* Total no. of Row = (No. of TLV)/(No. of Columns) */
  totalNumRow = tlvArray->numTlvs/totalNumCol;

  for (i=1;  i <= totalNumRow;  i++) 
      {
      timersConfigTableEntry *ptr=(timersConfigTableEntry *)malloc(sizeof(timersConfigTableEntry));

      clearBytes(ptr,sizeof(timersConfigTableEntry));

      /* Fill Data in TLV */
      for(colmn = 1 ; colmn <= totalNumCol ; colmn++, pos++)
        {
       if (colmn EQ COLUMN_TIMERNAME)
           {
            ptr->timerName = getUint32FromArray(tlvArray->tlvInfo[pos].data);
            continue;
           }        
       if (colmn EQ COLUMN_TIMEUNIT)
           {
           ptr->timeUnit = getUint32FromArray(tlvArray->tlvInfo[pos].data);
            continue;
           }        
       if (colmn EQ COLUMN_DURATION)
           {
            ptr->duration = getUint32FromArray(tlvArray->tlvInfo[pos].data);
            continue;
           }        
        if (colmn EQ COLUMN_DESCRIPTION)
           {
            clearBytes (ptr->description, TIMERS_BUFFER_LEN_MAX);
            if (tlvArray->tlvInfo[pos].len > 0) 
                {    
                 copyBytes (tlvArray->tlvInfo[pos].data, tlvArray->tlvInfo[pos].len, ptr->description);
                }
            ptr->description_len = strlen(ptr->description);
            continue;
           }
        if (colmn EQ COLUMN_USEDBY)
           {
            ptr->usedBy = getUint32FromArray(tlvArray->tlvInfo[pos].data);
            continue;
           }       
        }

       ptr->next = NULL;

      if (prevPtr == NULL) {
           timersConfigTable_head =  prevPtr = ptr;
       }

      prevPtr->next = ptr;
      prevPtr = ptr;
     }
    prevPtr->next = NULL;

    if (timersConfigTable_head)
        return TRUE;
    else
        return FALSE;
}

/**
* @details 
*          This routine sends enodeb config set request to BSM, it uses SIH Set 
*          Processor to create and send the message to BSM. 
* @param sihTagInfo is used to have the tag information for set request.
*/
TBOOL sendTimersConfigSnmpSetRequest ( 
      IO TagInfo  sihTagInfo,
      IO struct timersConfigTable_entry  *timersConfig_entry,
      IO TlvArray *tlvArray
      )
{
   timersConfigTableEntry *setReqData = NULL;   
   TBOOL status = FALSE;
   int colmn = 0;
   unsigned char *ipAddr;
   struct in_addr ip;
 
   setReqData = timersConfig_entry;

   /* Fill Data in TLV */
   for(colmn = 0; colmn < tlvArray->numTlvs; colmn++)
   {
       if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_TIMERNAME)
       {
           putUint32InArray( setReqData->timerName, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->timerName);     
       }
       if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_TIMEUNIT)
       {
           putUint32InArray( setReqData->timeUnit, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->timeUnit);     
       }
       if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_DURATION)
       {
           putUint32InArray( setReqData->duration, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->duration); 
       }
       if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_DESCRIPTION)
       {
           copyBytes (setReqData->description, strlen(setReqData->description), tlvArray->tlvInfo[colmn].data);
           tlvArray->tlvInfo[colmn].len = TIMERS_CONFIG_DESC_BUF_LEN_MAX; 
       }
       if(tlvArray->tlvInfo[colmn].tag.colId EQ COLUMN_USEDBY)
       {
           putUint8InArray( setReqData->usedBy, tlvArray->tlvInfo[colmn].data );
           tlvArray->tlvInfo[colmn].len = sizeof(setReqData->usedBy);     
       }
   }

   /* Invoke SIH Set Processor */
   status = sihSetProcessor (sihTagInfo, tlvArray);
   if (status EQ TRUE)
     {
      g_sihTimersConfigSetReqProcessed = TRUE;
      g_sihTimersConfigGetReqProcessed = FALSE;
      /* free the resources */      
      free_timersConfigTable(); 
     }
   return status;
}


/**
* @details 
*          This is the routine for initializing timersConfig module.
*/
void
init_timersConfig(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_timersConfigTable();
}

/* Determine the first/last column names

 Initialize the timersConfigTable table by defining its contents and how it's structured */
void
initialize_table_timersConfigTable(void)
{
    const oid timersConfigTable_oid[] = {1,3,6,1,4,1,9344,501,TIMERSCONFIG,1};
    const size_t timersConfigTable_oid_len   = OID_LENGTH(timersConfigTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("timersConfig:init", "initializing table timersConfigTable\n"));

    reg = netsnmp_create_handler_registration(
              "timersConfigTable",     timersConfigTable_handler,
              timersConfigTable_oid, timersConfigTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: timerName */
                           0);
    table_info->min_column = COLUMN_TIMERNAME;
    table_info->max_column = COLUMN_USEDBY;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = timersConfigTable_get_first_data_point;
    iinfo->get_next_data_point  = timersConfigTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

#ifndef PWAV_SIH 
/* create a new row in the (unsorted) table */
struct timersConfigTable_entry *
timersConfigTable_createEntry(
                 long  timerName,
                ) {
    struct timersConfigTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct timersConfigTable_entry);
    if (!entry)
        return NULL;

    entry->timerName = timerName;
    entry->next = timersConfigTable_head;
    timersConfigTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
timersConfigTable_removeEntry( struct timersConfigTable_entry *entry ) {
    struct timersConfigTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = timersConfigTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        timersConfigTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}
#endif /* PWAV_SIH */


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
timersConfigTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    TagInfo sihTagInfo;
    TBOOL status = FALSE;

    if (g_sihTimersConfigGetReqProcessed EQ FALSE)
        {
        /* Set SIH Get Request Tag Info */
        sihTagInfo.tableId = TIMERSCONFIG;
        sihTagInfo.rowId = CONFIG_ROW_ID_NONE; 
        sihTagInfo.colId = CONFIG_COL_ID_NONE;                

        status = sihGetProcessor (sihTagInfo);
        if ( status EQ TRUE )
            {
            logInfo("%s","Get Processor Succedded");
            if (timersConfigTable_head)
                {
		g_timersConfigFirstCall = 1;
                g_sihTimersConfigGetReqProcessed = TRUE;
                }
            }
        else
            logError("%s","Get Processor Failed");
        }        
    
    *my_loop_context = timersConfigTable_head;
    return timersConfigTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
timersConfigTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct timersConfigTable_entry *entry = (struct timersConfigTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->timerName );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the timersConfigTable table */
int
timersConfigTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request = NULL;
    netsnmp_table_request_info *table_info = NULL;
    struct timersConfigTable_entry          *table_entry = NULL;
    int loopCount = 0;
    int ret;
    TagInfo sihTagInfo;
    TlvArray tlvArray;
    int rowIndex = 0, colId = 0;
    TBOOL status = FALSE;    

    DEBUGMSGTL(("timersConfig:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {

            loopCount++;
            if (request->processed != 0)
            {
	     g_prevTimersConfigReqCount = 0;	
             g_sihTimersConfigGetReqProcessed = FALSE;

             /* free the resources */
             free_timersConfigTable(); 
             /* Here loopCount is decremented, Due to calling of free function two times in SNMP-GETNEXT
              * on single parameter -- 20/07/11 */
             loopCount--;
             continue;
            }

            /* perform anything here that you need to do before each
               request is processed. */           

            /* the following extracts the my_data_context pointer set in
               the loop functions above.  You can then use the results to
               help return data for the columns of the timersConfigTable table 
               in question */    

            table_entry = (struct timersConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);

            if ( table_entry == NULL) {
                if (reqinfo->mode == MODE_GET) {
                    netsnmp_set_request_error(reqinfo, request,SNMP_NOSUCHINSTANCE);
                    continue;
                }
                /* XXX: no row existed, if you support creation and this is a
                   set, start dealing with it here, else continue */
            }

            table_info  =     netsnmp_extract_table_info(      request);

            /* table_info->colnum contains the column number requested */
            /* table_info->indexes contains a linked list of snmp variable
               bindings for the indexes of the table.  Values in the list
               have been set corresponding to the indexes of the
               request */
            if (table_info==NULL) {
                continue;
            }       
    
            switch (table_info->colnum) {
            case COLUMN_TIMERNAME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->timerName);
                break;
            case COLUMN_TIMEUNIT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->timeUnit);
                break;
            case COLUMN_DURATION:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->duration);
                break;
            case COLUMN_DESCRIPTION:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->description,
                                          table_entry->description_len);
                break;
            case COLUMN_USEDBY:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->usedBy);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
	if(g_timersConfigFirstCall EQ 1)
         {
            g_timersConfigFirstCall = 0;
            g_prevTimersConfigReqCount = loopCount;
            // This will occur in case of, when SNMP-GET or SNMP-GETNEXT of Single Parameter occurred.
            // In the first call itself loopCount becomes one.
            // In General Case, the loopCount will be always > 1 because every table contains 
            // index column to fetch the row and remaining columns contain table attributes.
            if(loopCount EQ 1)
            {
               //Setting it to false in case of SNMP-GET request for single parameter.
               g_sihTimersConfigGetReqProcessed = FALSE;
               // Free all resources.
               free_timersConfigTable();
            }
         }
         else if(loopCount > 1 || g_prevTimersConfigReqCount > 1)
         {
            //update g_prevReqCount with current loopCount for next call of Table_handler
            g_prevTimersConfigReqCount = loopCount;
         }
         else if(loopCount EQ 1)
         {
            //Setting it to false in case of SNMP-GET request for single parameter.
            g_sihTimersConfigGetReqProcessed = FALSE;
            // Free all resources.
            free_timersConfigTable();
         }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
#ifndef PWAV_SIH   
        for (request=requests; request; request=request->next) {
            table_entry = (struct timersConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_TIMEUNIT:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_DURATION:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
#endif /* PWAV_SIH */         
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        g_sihTimersConfigSetReqProcessed = FALSE; 

        clearBytes(&sihTagInfo, sizeof(TagInfo));
        clearBytes(&tlvArray, sizeof(TlvArray));
   
        for (request=requests; request; request=request->next) {
            table_entry = (struct timersConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            if(table_entry == NULL){
                logInfo(" %s\n", "table_entry is NULL");
                if (reqinfo->mode == MODE_SET_ACTION) {
                    netsnmp_set_request_error(reqinfo, request,SNMP_NOSUCHINSTANCE);
                    continue;
                }
                /* XXX: no row existed, if you support creation and this is a
                   set, start dealing with it here, else continue */
            }

            if(table_info == NULL){
                logInfo(" %s\n", "table_info is NULL");
                continue;
            }

            colId = table_info->colnum;
            /* set the row index */
            rowIndex = requests->requestvb->name_loc[OID_ROW_POSITION];
    
            switch (table_info->colnum) {
            case COLUMN_TIMERNAME:
                table_entry->timerName     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, TIMERSCONFIG, rowIndex, COLUMN_TIMERNAME);
                tlvArray.numTlvs++;
                break;
            case COLUMN_TIMEUNIT:
                table_entry->timeUnit     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, TIMERSCONFIG, rowIndex, COLUMN_TIMEUNIT);
                tlvArray.numTlvs++;
                break;
            case COLUMN_DURATION:
                table_entry->duration     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, TIMERSCONFIG, rowIndex, COLUMN_DURATION);
                tlvArray.numTlvs++;
                break;
            case COLUMN_DESCRIPTION:
               memset( table_entry->description, 0,
                        sizeof(table_entry->description));
                memcpy( table_entry->description,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->description_len =
                        request->requestvb->val_len;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, TIMERSCONFIG, rowIndex, COLUMN_DESCRIPTION);
                tlvArray.numTlvs++;
                break;
            case COLUMN_USEDBY:
                table_entry->usedBy     = *request->requestvb->val.integer;
                fillTableInfo(&tlvArray.tlvInfo[tlvArray.numTlvs].tag, TIMERSCONFIG, rowIndex, COLUMN_USEDBY);
                tlvArray.numTlvs++;
                break;
            }
        }

       if ((request == NULL) && (g_sihTimersConfigSetReqProcessed EQ FALSE))
            /* Processed all requests and table entry is filled with
             * requested data. */
            {
            /* Set SIH Set Request Tag Info */
            sihTagInfo.tableId = TIMERSCONFIG;

            sihTagInfo.rowId = rowIndex; 

            status = sendTimersConfigSnmpSetRequest (sihTagInfo, table_entry, &tlvArray);
            if (status EQ TRUE)
                {
                logInfo("%s","SET Succedded");
                }
            else
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_GENERR );
            }
        break;

    case MODE_SET_UNDO:
#ifndef PWAV_SIH 
        for (request=requests; request; request=request->next) {
            table_entry = (struct timersConfigTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_TIMEUNIT:
                table_entry->timeUnit     = table_entry->old_timeUnit;
                table_entry->old_timeUnit = 0;
                break;
            case COLUMN_DURATION:
                table_entry->duration     = table_entry->old_duration;
                table_entry->old_duration = 0;
                break;
            }
        }
#endif /* PWAV_SIH */
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}
