/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 19302 2010-08-13 12:19:42Z dts12 $
 */
#ifndef GPSSTATUS_H
#define GPSSTATUS_H

/* function declarations */
void init_gpsStatus(void);
void initialize_table_gpsStatusTable(void);

/* column number definitions for table gpsStatusTable */
       #define COLUMN_GPS_STATUS_INDEX		1
       #define COLUMN_GPSLATITUDE		2
       #define COLUMN_GPSLONGITUDE		3
       #define COLUMN_GPSDATEANDTIME	4

#define GPS_STATUS_MAX_COL  COLUMN_GPSDATEANDTIME
#define GPS_STATUS_LATI_MAX_BUF_LEN        13
#define GPS_STATUS_LONG_MAX_BUF_LEN        14
#define GPS_STATUS_DATE_AND_TIME_BUF_LEN_MAX 17

    /* Typical data structure for a row entry */
typedef struct gpsStatusTable_entry {
    /* Index values */
    unsigned int index;

    /* Column values */
    char gpsLatitude[GPS_STATUS_LATI_MAX_BUF_LEN];
    size_t gpsLatitude_len;
    char gpsLongitude[GPS_STATUS_LONG_MAX_BUF_LEN];
    size_t gpsLongitude_len;
    char gpsDateAndTime[GPS_STATUS_DATE_AND_TIME_BUF_LEN_MAX];
    size_t gpsDateAndTime_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct gpsStatusTable_entry *next;
}gpsStatusTableEntry;

#endif /* GPSSTATUS_H */
